### ISSUE TITLE
App icon library tabs adds a pixel under tabs when scrolling

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#1009]
Look under “Library” tab on scroll

<img width="577" alt="Screen Shot 2021-09-07 at 6 24 46 PM" src="https://user-images.githubusercontent.com/32881239/132422723-2e85c7c7-2317-42b2-98e8-f7c78195c683.png">

<img width="277" alt="Screen Shot 2021-09-07 at 6 24 54 PM" src="https://user-images.githubusercontent.com/32881239/132422735-c8b6727f-131a-4a07-8ac9-2d535f9c6fb9.png">

**Comment by mjabbink** [comment]
@peter-garvin @sadekbazaraa

**Comment by sadekbazaraa** [comment]
Hmmm... @mjabbink  I'm not sure what's causing that offset but I do see it.
@vpicone @alisonjoseph ?
