### ISSUE TITLE
Color switcher style bugs

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#101]
Switcher should not have short vertical dividers and the horizontal line under the switcher button seems too light? Assign to Sadek. 

The switcher should be sticky in mobile and desktop with a 16 px space (background color) above the switcher. See DL desktop.
![image](https://user-images.githubusercontent.com/2753488/61239866-833d0480-a705-11e9-95ba-52df3d5a5c91.png)

![image](https://user-images.githubusercontent.com/2753488/61239874-87692200-a705-11e9-9828-13af9a967989.png)

**Comment by mjabbink** [comment]
@jeanservaas also the white horizontal line underneath switcher seems harsh. Do we need it if drop shadow is there?
