### ISSUE TITLE
Update IDL charts page - Add missing charts to Charts page

### ISSUE THREAD

**Issue by DanaPaslaru** [carbon-design-system/design-language-website#1016]
add following charts:
- Tree diagram
- Alluvial
- Network diagram (update thumbnail, remove tag)

+ Proportional meter, currently there's no thumbnail

**Comment by DanaPaslaru** [comment]
update the IDL charts to match ones from carbon design website:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/64195956/134038305-094c8c1e-c6dc-466c-a0bb-32443bda3d38.png">

**Comment by DanaPaslaru** [comment]
@mjabbink @sadekbazaraa Hi, I've updated the IDL Chart page with network diagram, tree diagram and updated url for alluvial. Here is the preview url: 
https://design-language-website-git-fork-da-c9be47-carbon-design-system.vercel.app/data-visualization/charts

PR here: https://github.com/carbon-design-system/design-language-website/pull/1022

Thanks!

**Comment by sadekbazaraa** [comment]
Thanks @DanaPaslaru exciting! Looks good by me.

**Comment by mjabbink** [comment]
Thanks @DanaPaslaru! Looking good but seeing this update made me see I failed to also mention we have Histogram as well. Sorry for late notice.

**Comment by DanaPaslaru** [comment]
@mjabbink @sadekbazaraa Hi, I've removed the disable state for Histogram, it's active now:
https://design-language-website-git-fork-da-c9be47-carbon-design-system.vercel.app/data-visualization/charts


Thanks!

**Comment by mjabbink** [comment]
@DanaPaslaru Looking good!

**Comment by mjabbink** [comment]
@DanaPaslaru This looks live so closing.
