### ISSUE TITLE
Update “Universal Experiences“ to “Experience Standards” in site switcher 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#1047]
This needs to happen in 

— IDL and Brand Center
— Carbon

And anywhere else using this content in the site switcher

**Comment by mjabbink** [comment]
<img width="284" alt="Screen Shot 2021-11-18 at 2 01 13 PM" src="https://user-images.githubusercontent.com/32881239/142488840-e57dc62e-efea-4c10-8b55-51bfabfdcd84.png">

**Comment by alisonjoseph** [comment]
@aledavila after we do a theme release just need to pull in the latest to get the switcher update
