### ISSUE TITLE
Broken download link on Technical diagrams page

### ISSUE THREAD

**Issue by mzuliani-ibm** [carbon-design-system/design-language-website#1056]
## Detailed description

RE hidden pages: Technical diagrams
https://www.ibm.com/design/language/infographics/technical-diagrams/design/
https://www.ibm.com/design/language/infographics/technical-diagrams/usage

404 error when trying to download Adobe Illustrator template files at:
https://www.ibm.com/design/language/files/Technical-diagrams-kit_v1.ai
https://www.ibm.com/design/language/files/IT-architecture-diagrams-kit_v1.ai

Files are in "static/files" directory:

https://github.com/carbon-design-system/design-language-website/blob/master/static/files/Technical-diagrams-kit_v1.ai

### Expected behavior

Expected download links to work

### Additional information

- Consider putting the download files outside the static directories: https://www.gatsbyjs.com/docs/how-to/images-and-media/static-folder/

**Comment by mzuliani-ibm** [comment]
Also consider adding a link to corresponding Carbon Charts code:
https://www.carbondesignsystem.com/data-visualization/complex-charts/#network-diagrams

**Comment by alisonjoseph** [comment]
PR Open to fix the download links, I'll defer to the Brand team on adding links and how/where they want to do that.

**Comment by mzuliani-ibm** [comment]
The PR just adds a download icon to the tile, the download URLs for the Illustrator files are still broken as far as I can tell. Can this issue be reopened?
@sstrubberg
