### ISSUE TITLE
Homepage layout bugs

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#108]
- [x] Landing page: Cards should be 1:1 aspect ratio in mobile
- [ ] The ordering of images is also different. Should follow current DL 
- [ ] Match spacing to live site

![image](https://user-images.githubusercontent.com/2753488/61501134-a8df3d80-a993-11e9-91f0-2a08dd76a680.png)

Compare homepage card layout for all cards from live site vs. staging site (https://app.mural.co/t/teamselectrics7779/m/teamselectrics7779/1562855399131/774f26a5b572c855f0ca380cb672334b323ca589)

**Comment by emyarod** [comment]
@alisonjoseph right now this is the same for all viewport sizes because of the `ratio` prop on the `<HomepageTile>`s. can we just want to override the styles set by the `ratio` prop in SCSS or do we want to take a different approach to styling based on viewport size?

**Comment by mjabbink** [comment]
The image with mountains above and card also are getting cropped in mobile

**Comment by alisonjoseph** [comment]
@emyarod for now we will have to override the css for the ratio class at mobile
