### ISSUE TITLE
Add correct bee favicon

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#109]

**Comment by emyarod** [comment]
@alisonjoseph do you have any more details for this ticket like where the correct favicon can be found etc?

**Comment by alisonjoseph** [comment]
Instructions where to set favicon https://gatsby-theme-carbon.now.sh/guides/configuration#favicon

[favicon-512.png.zip](https://github.com/carbon-design-system/design-language-website/files/3422522/favicon-512.png.zip)
