### ISSUE TITLE
Intermittent image loading issues

### ISSUE THREAD

**Issue by Palke** [carbon-design-system/design-language-website#1106]
There has been report from some users that images (mostly on newly created pages) are not loading properly on the first visit.

I have managed to replicate this issue multiple times on various pages, but there is no pattern to follow to replicate it as this issue appears to be somewhat random.

Last time this issue happened (on this page https://www.ibm.com/design/language/infographics/technical-diagrams/design) I have looked up the image responses and it was failing with 301 redirect.

![image](https://user-images.githubusercontent.com/54019675/168539595-68034f99-720f-4d7b-98e9-2e2f3ed748bb.png)

![image](https://user-images.githubusercontent.com/54019675/168539466-d703c770-03ba-47fe-92d9-f83c9066c45c.png)

Images that failed do exist on the server: https://www.ibm.com/design/language/static/ae454282c3f44a8e638c77056da48d2e/a5df1/small_nodes2.png

This issue is not present on the Vercel build and neither on the Cloud url: https://design-language-website-carbon.mybluemix.net/design/language/

cc: @sstrubberg

**Comment by abhilipsasahoo03** [comment]
Just faced similar issue in the Resources page.

### Screenshots

![Screenshot_2022-10-07-23-55-19-274_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/194627016-0bd450f0-561c-4141-90aa-e3dde367b3e2.jpg)

![Screenshot_2022-10-07-23-58-06-775_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/194627044-539c2c30-19bd-4ab4-bcb7-c6e38bdcfd4a.jpg)

![Screenshot_2022-10-08-00-02-00-455_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/194627069-835c2022-dd5b-4c26-846f-4c3f1cbd19b9.jpg)

![Screenshot_2022-10-08-00-02-04-896_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/194627103-dcc432c5-2f82-4699-ac5b-7ef05153d0a2.jpg)

![Screenshot_2022-10-08-00-02-13-858_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/194627131-54d42111-38b1-468f-98a7-0bf9822d3c04.jpg)
