### ISSUE TITLE
404 error on Third Party IBM Logo guidelines

### ISSUE THREAD

**Issue by Danilo-Colonheze-IBM** [carbon-design-system/design-language-website#1145]
## Detailed description

Describe in detail the issue you're having.:
**On the [Third party section](https://www.ibm.com/design/language/ibm-logos/8-bar/#third-party-logo-usage) in the 8-bar logo page, clicking the card results in a 404 page.**

What did you expect to happen? What happened instead? What would you like to see changed?
**It should open in the .pdf linked on the resource card in the same tab.**

What browser are you working in?
**Chromium: 105.0.5195.102**

## Steps to reproduce the issue

1. Step one
Open the page: https://www.ibm.com/design/language/ibm-logos/8-bar/#third-party-logo-usage

2. Step two
Click the resource card named "IBM logo and brand guidelines for third-party users"

3. Step three
404 page will appear

4. Step four
You can return to the [previous page](https://www.ibm.com/design/language/ibm-logos/8-bar/#third-party-logo-usage) and Cmmd+Click the card to open in another tab for it to work. This proves that the file is added correctly, but it's not the desired behavior expect by the client.

## Additional information

The [Pull request](https://github.com/carbon-design-system/design-language-website/pull/1140) that updated this resource card content and added the .pdf to the project.
It had the absolute path to the file (which maybe solve this problem) and it was changed to relative path `/files/filename.pdf`.

**Comment by Huda-TO** [comment]
@Danilo-Colonheze-IBM What is the status of this issue? Is anyone working on this?

**Comment by Huda-TO** [comment]
The 404 error is still there?

**Comment by Danilo-Colonheze-IBM** [comment]
@Huda-TO the issue is solved and the resource card now opens the file correctly!

**Comment by tw15egan** [comment]
@Huda-TO there was probably a delay between the merge being committed and auto-closing the issue and the subsequent deployment run.
