### ISSUE TITLE
Switch App icon library to default in Light theme

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#1153]
https://www.ibm.com/design/language/iconography/app-icons/library/

`FROM:`

<img width="906" alt="Screen Shot 2022-10-06 at 11 15 24 AM" src="https://user-images.githubusercontent.com/32881239/194365333-c0fd22fc-9a66-44b7-9c7e-886063543c8b.png">

v
v
v
v
v

`TO:`

<img width="904" alt="Screen Shot 2022-10-06 at 11 15 13 AM" src="https://user-images.githubusercontent.com/32881239/194365430-44aff959-fbab-495c-96a0-0902306951d3.png">

**Comment by mjabbink** [comment]
FYI @DianaStanciulescu @andreeavintila @DanaPaslaru

**Comment by mjabbink** [comment]
Let’s get this done please

**Comment by ljcarot** [comment]
@aledavila Can you pick this up?
