### ISSUE TITLE
Remove “Design only“ tag from Heatmap thumbnail

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#1167]
https://www.ibm.com/design/language/data-visualization/charts#correlations

<img width="692" alt="Screen Shot 2022-11-29 at 7 05 46 PM" src="https://user-images.githubusercontent.com/32881239/204682593-36b69c51-8d5d-4d0a-a732-03185f709af0.png">

**Comment by abhilipsasahoo03** [comment]
@tay1orjones can I work on this?

**Comment by tay1orjones** [comment]
@abhilipsasahoo03 go for it!

**Comment by tay1orjones** [comment]
cc @theiliad
