### ISSUE TITLE
broken app icon

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#1173]
This one doesnt look quite right

<img width="604" alt="Screenshot 2022-12-02 at 3 33 07 PM" src="https://user-images.githubusercontent.com/47458576/205392312-d2c97bc7-24ef-41d1-838f-7c73084c4825.png">

**Comment by DianaStanciulescu** [comment]
solved in PR https://github.com/carbon-design-system/design-language-website/pull/1256
