### ISSUE TITLE
Firefox won't load homepage video

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/design-language-website#120]
Getting a `All candidate resources failed to load. Media load paused.` warning in the console. I think this might be cause we explicitly set the video type in the video component as well as the src.

Works in dev but not deployed? 🤷‍♂

**Comment by emyarod** [comment]
is this on the stage IDL site? just trying to reproduce the issue

**Comment by vpicone** [comment]
Yeah, the video at the top. Using a webm video fixes it. I'm looking into it atm.

**Comment by emyarod** [comment]
that's weird, I'm not able to reproduce it on FF70. wouldn't the current mp4 have better compatibility than webm though?

**Comment by vpicone** [comment]
@emyarod video elements allow you to specify multiple sources so the webm would be used as a backup. I'm using the latest developer edition of firefox.

**Comment by vpicone** [comment]
Looks like it's still using the old API for the video source??

<img width="858" alt="Screen Shot 2019-07-24 at 10 51 06 AM" src="https://user-images.githubusercontent.com/4078018/61808432-fc70e180-ae00-11e9-8fe5-03a08695989d.png">

**Comment by emyarod** [comment]
this is the stage IDL site right? http://design-language-staging-new.mybluemix.net/design/language/

![firefox_2019-07-24_10-53-55](https://user-images.githubusercontent.com/8265238/61808636-6a1d0d80-ae01-11e9-9b59-60dc2565e242.png)

**Comment by vpicone** [comment]
@emyarod Yeah that's the current design language website. We don't want to rely on that API or those assets. This was a hard coded source pointing to that old API. We put our videos and other static assets in the `static` directory and reference them with `/videos/*` for this project.

**Comment by emyarod** [comment]
I'm just trying to reproduce the issue, we deploy the new IDL site here right? https://design-language-website.netlify.com/

it plays correctly for me, but I'm on FF70 and I think dev edition is currently 68?

![image](https://user-images.githubusercontent.com/8265238/61809574-2fb47000-ae03-11e9-8e7c-a2db47bbb8e2.png)

**Comment by emyarod** [comment]
what's the http request look like for you?
