### ISSUE TITLE
fix(code snippet width): Type specs UI page

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/design-language-website#129]
fix(code snippet width): Type specs UI page

Noticed this issue when previewing another PR
![image](https://user-images.githubusercontent.com/43144260/62085343-f4f67180-b220-11e9-9efb-2abd7c45a772.png)

This was happening in Chrome -- I didn't check other browsers. But code snippets should be the same width as the usage images when they are attached to them.

**Comment by alisonjoseph** [comment]
this was fixed at some point
