### ISSUE TITLE
design-language-website: Iconography, App icons: Remove "null" and "unassigned" section

### ISSUE THREAD

**Issue by gbrlbrb** [carbon-design-system/design-language-website#1296]
Hello,

Not sure what caused this issue but there is this new section at the end of the App icons library (null) that should be removed. The app icons that are part of the null section are already part of the library. I guess the section will dissapear if we remove the empty duplicates. 

⚠️ Make sure you don't remove the good app icons. ⚠️

Thank you!

https://www.ibm.com/design/language/iconography/app-icons/library

<img width="1728" alt="Screenshot 2023-11-07 at 11 58 57" src="https://github.com/carbon-design-system/design-language-website/assets/114246981/dc29c421-3aa0-4111-a9d8-541d86d5761e">

**Comment by conradennis** [comment]
There's also a new `unassigned` category with a single icon, right above the `null` section:

<img width="1185" alt="Screenshot 2023-12-21 at 11 30 32 AM" src="https://github.com/carbon-design-system/design-language-website/assets/16782944/b4baa913-cae2-4d6d-8fa6-a7b080e48885">

**Comment by tay1orjones** [comment]
I'll need to double check, but this seems like an issue of incomplete or invalid metadata.

**Comment by conradennis** [comment]
@tay1orjones Thank you! @DianaStanciulescu looping you in for awareness
