### ISSUE TITLE
Typeface - Type tester - text should be light as default

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#131]
The default should be Plex Light

![image](https://user-images.githubusercontent.com/2753488/62138382-2caafb00-b2ad-11e9-8031-b0424f1032a4.png)

**Comment by emyarod** [comment]
isn't this a dupe of https://github.com/carbon-design-system/design-language-website/issues/84?

**Comment by alisonjoseph** [comment]
Oh yep, good call. Mike just messaged me this, forgot it was in a PR
