### ISSUE TITLE
Color page - image bugs

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#133]
Small swatches should match IDL site size at mobile (currently one wide image, if we split in to two images should be able to fix easily)

![image](https://user-images.githubusercontent.com/2753488/62161624-40218a80-b2dc-11e9-92ff-57e016a8e891.png)

Same issue on Color UI page **figure out if we can remove this page**
![image](https://user-images.githubusercontent.com/2753488/62161686-60514980-b2dc-11e9-9879-1fc89388585b.png)

**Comment by emyarod** [comment]
@alisonjoseph does it need to be an image on the new site? it looks like it's pure css in the current IDL site

**Comment by alisonjoseph** [comment]
Oh good catch, I think its fine either way as long as we get the intended effect.
