### ISSUE TITLE
fix[tab component]: focus state & tablet dropdown

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/design-language-website#135]
## fix[tab component]: focus state & tablet dropdown

- focus state is pulling browser focus, not our custom focus state

**current behavior:**

![image](https://user-images.githubusercontent.com/43144260/62229876-4a985e80-b386-11e9-9327-7e4e5e38a2b5.png)

<br>

**desired behavior** 

_(currently, focus is not enabled in IDL, even on tab, which is not accessible); however if we do enable focus, it should be our custom IDL focus state (2px; color: Blue 60; $focus):_

![image](https://user-images.githubusercontent.com/43144260/62229982-7c112a00-b386-11e9-8ea4-0e0609a9480a.png)

<br>

- dropdown field goes to Gray 10 on click; field color should stay the same as the enabled state: white ($field-01)

**current behavior:**

![image](https://user-images.githubusercontent.com/43144260/62230734-0e65fd80-b388-11e9-804f-73a644a41dff.png)

<br>

**desired behavior** 

![image](https://user-images.githubusercontent.com/43144260/62230861-61d84b80-b388-11e9-9884-bbe6be6af9b2.png)

**Comment by emyarod** [comment]
the second point about the dropdown background color is related to https://github.com/carbon-design-system/carbon/issues/3609
