### ISSUE TITLE
Philosophy page: Body copy needs to be Expressive H3 I believe

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#136]
@jeanservaas can confirm size name just in case I’m wrong.

current:

![Screen Shot 2019-07-31 at 12 51 00 PM](https://user-images.githubusercontent.com/32881239/62231354-e085b680-b391-11e9-8ed9-119823ead982.png)

——————

expected:

![Screen Shot 2019-07-31 at 12 50 54 PM](https://user-images.githubusercontent.com/32881239/62231367-e7acc480-b391-11e9-8a9d-bafa2b4ea401.png)

**Comment by jeanservaas** [comment]
It's actually **$expressive-heading-03** in the .json file but not up on the Carbon site -- we've had an issue in for a while to update the Productive and Expressive type tab designs to reflect the .json file.

Correct values:

https://carbon-elements.netlify.com/type/examples/preview/
