### ISSUE TITLE
Add Plex Math to [What’s new]

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#1362]
When `IBM Plex Math` is released on GitHub, please plan to have this go up soon after for communication purposes.

`Image reference`
<img width="984" alt="Screenshot 2024-07-12 at 1 23 01 PM" src="https://github.com/user-attachments/assets/d559eca8-b8c3-47a2-868d-2308119f722d">

`copy`
> After a year of anticipation, we are excited to introduce IBM Plex® Math. This highly anticipated release includes over 5,000 new glyphs, covering a wide range of mathematical symbols (such as alphanumeric, double-struck, Fraktur, operators, and script), icons, arrows, Greek letters, phonetics, technical and geometric shapes — making it one of the most complete math fonts available today. IBM Plex Math is a game-changer, providing a fresh and comprehensive alternative to STIX and Microsoft’s Cambria. Its compatibility with IBM Plex Serif Regular makes it an ideal choice for IBM researchers and mathematicians.

**Comment by mjabbink** [comment]
FYI @Lingaraj-13

**Comment by Lingaraj-13** [comment]
Hello  @DianaStanciulescu & @Katie-A-IBM 
need your kind attention on this ticket for us to take it further.

**Comment by DianaStanciulescu** [comment]
This looks good, we need an editor to take a look. figma link here: https://www.figma.com/design/A8Aqo87GXAFPJ7gbIvJYkL/%5BIDL%5D-Typeface-%26-What's-new?node-id=603-9791&t=mQ8B8cBdeJGr9sjd-4

**Comment by mjabbink** [comment]
@DianaStanciulescu I updated the text. It’s “...over 5,000 glyphs...”

**Comment by mjabbink** [comment]
`new copy`
> After a year of anticipation, we are excited to introduce IBM Plex® Math. This highly anticipated release includes over 5,000 new glyphs, covering a wide range of mathematical symbols (such as alphanumeric, double-struck, Fraktur, operators, and script), icons, arrows, Greek letters, phonetics, technical and geometric shapes — making it one of the most complete math fonts available today. IBM Plex Math is a game-changer, providing a fresh and comprehensive alternative to STIX and Microsoft’s Cambria Math. Its compatibility with IBM Plex Serif Regular makes it an ideal choice for IBM researchers and mathematicians.

**Comment by Lingaraj-13** [comment]
Closing this issue as the updates are made live
