### ISSUE TITLE
Typeface page: Thai looped getting cropped in "non-Latin scripts" section

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#138]
crops in desktop and mobile

https://design-language-website.netlify.com/elements/typeface

<img width="811" alt="Screen Shot 2019-08-01 at 2 26 15 PM" src="https://user-images.githubusercontent.com/32881239/62317809-7429b680-b468-11e9-9949-bea166b9ac70.png">

**Comment by emyarod** [comment]
I'm not able to reproduce this issue

desktop:

![image](https://user-images.githubusercontent.com/8265238/62373617-ca960400-b4ff-11e9-96ef-73273bd1980d.png)

mobile:

![design-language-website netlify com_elements_typeface_(iPhone X)](https://user-images.githubusercontent.com/8265238/62373631-d4b80280-b4ff-11e9-8efc-5d002463db2f.png)

**Comment by mjabbink** [comment]
If this is correct https://design-language-website.netlify.com/elements/typeface/

It’s happening in both safari and chrome in mobile. It has even become more cropped from my screen grab.

**Comment by mjabbink** [comment]
did you figure this one out?

**Comment by emyarod** [comment]
reopening for minor changes (screenshot from Firefox 70)

![image](https://user-images.githubusercontent.com/8265238/63165780-021da980-bff2-11e9-8670-b949a9d7c861.png)
