### ISSUE TITLE
Sketch kit link 404s

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/design-language-website#140]
We link to https://www.ibm.com/standards/web/design-kit/

a lot. We should use the corresponding link from the [designers getting started](https://www.carbondesignsystem.com/getting-started/designers#get-the-kit) from Carbon.

**Comment by emyarod** [comment]
it looks like it's used a lot as a placeholder page on the homepage

**Comment by vpicone** [comment]
Ah, yeah. It's actually broken on the live idl site homepage right now as well
