### ISSUE TITLE
Landing page: Type scale bugs in a few resource cards

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#145]
[Screen Recording 2019-08-02 at 6.46.00 PM.zip](https://github.com/carbon-design-system/design-language-website/files/3463093/Screen.Recording.2019-08-02.at.6.46.00.PM.zip)

**Comment by alisonjoseph** [comment]
I see the issue in the video but am having trouble duplicating. @emyarod are you able to duplicate? Looks like the font size is jumping on hover on homepage cards

**Comment by emyarod** [comment]
I am unable to reproduce this issue locally on any browser or platform. do you have any more details like browser version, etc?

**Comment by mjabbink** [comment]
this seems to be resolved now. It was happening in Chrome Version 75.0.3770.142 (Official Build) (64-bit)  and Safari 12.1.2.
