### ISSUE TITLE
Dropdowns in mobile should be white not grey 10

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#147]
![CC2EADA4-CD91-4B7F-9FBD-0AD471528DF7](https://user-images.githubusercontent.com/32881239/62411590-355c4380-b5c3-11e9-9a70-3c1ff8cac865.jpeg)

**Comment by emyarod** [comment]
related: https://github.com/carbon-design-system/design-language-website/issues/135

this is an issue with the carbon components and is resolved in https://github.com/carbon-design-system/carbon/pull/3610. we can pull the fix in after the next carbon release is out

**Comment by emyarod** [comment]
this should be closed now that we are on carbon components react 7.5.0
