### ISSUE TITLE
Lead space tabs in mobile should be more narrow

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#148]
@jeanservaas 

Current:

![3082E92A-B2A8-47D5-BE46-BF7A72DB24E6](https://user-images.githubusercontent.com/32881239/62411630-02ff1600-b5c4-11e9-82d0-68f87101bdeb.jpeg)

Expected:

![616A05B9-2B62-4139-BC52-B678A0148675](https://user-images.githubusercontent.com/32881239/62411632-13af8c00-b5c4-11e9-83b1-84c045858bb0.jpeg)

**Comment by mjabbink** [comment]
Not totally wed to this but seems efficient and I though Jeannie liked shorter as well.

**Comment by alisonjoseph** [comment]
This was updated in the theme last week, will be viewable on IDL site once this PR is merged in https://github.com/carbon-design-system/design-language-website/pull/132
