### ISSUE TITLE
GitHub link in footer links to Carbon website repo

### ISSUE THREAD

**Issue by kellychurchill** [carbon-design-system/design-language-website#155]
## Detailed description

GitHub link goes to
https://github.com/carbon-design-system/carbon-website/issues/new/choose

Should go to 
https://github.com/carbon-design-system/design-language-website/issues/new/choose

**Comment by emyarod** [comment]
is this still the case? I'm unable to replicate this issue at https://design-language-website.netlify.com/

**Comment by kellychurchill** [comment]
On https://www.ibm.com/design/language/, it is still the case. Is  https://design-language-website.netlify.com/ a new version that will be going live? If so, then that would resolve this issue.

**Comment by emyarod** [comment]
https://design-language-website.netlify.com/ reflects the current state of this repository which will become the new IDL site later this month
