### ISSUE TITLE
Philosophy: line width

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#157]
@jeanservaas @alisonjoseph 
In mobile: The line width and where words are breaking seems off. Are there hard returns in the text? Some lines extend to right margin and some don’t ever if a word could fit up on the previous line.

![A4A58800-1A9A-481A-B99A-432B1B18BB93](https://user-images.githubusercontent.com/32881239/62593325-e4668b00-b8f3-11e9-882f-395605f6e182.jpeg)
![89B0FDAF-E281-4405-A65C-126F1F36D54E](https://user-images.githubusercontent.com/32881239/62593326-e4668b00-b8f3-11e9-8b9f-25d03791de66.png)

**Comment by jeanservaas** [comment]
Yeah something is weird there... I would have thought it was just keeping a right margin in mobile that we could drop... but you're right, some lines are spanning across.

![image](https://user-images.githubusercontent.com/43144260/62636768-cdc63100-b8ff-11e9-97b5-9092ba82cc6b.png)

**Comment by alisonjoseph** [comment]
Will take a look, likely due to some nesting with the grid components we are using on this page w/ the right sidebar.

**Comment by alisonjoseph** [comment]
![IMG_3855](https://user-images.githubusercontent.com/32881239/62736088-3faa9180-ba4a-11e9-9407-7c0260ce81ff.JPG)

**Comment by emyarod** [comment]
it looks like there are some negative margin and padding rules are causing these line breaks

**Comment by emyarod** [comment]
the styles seem to be coming from the theme, do we want to override it for the site or change it at the theme level?

https://github.com/carbon-design-system/gatsby-theme-carbon/blob/master/packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss#L6-L7

**Comment by alisonjoseph** [comment]
I think this might be an error in the markdown, let me look

**Comment by alisonjoseph** [comment]
@emyarod it was a whitespace issue, I opened a PR that should fix
