### ISSUE TITLE
Remove “Disciplines” from left nav

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#162]
That content is now in the updated switcher so we can remove from left nav.

**Comment by emyarod** [comment]
the links in the left nav appear to be different in the switcher, do we want to make any changes to the switcher links or are we just going to remove the left nav links?

**Comment by alisonjoseph** [comment]
The left nav links go to the landing pages for Product/Digital. Confirming you want to remove these? @mjabbink

<img width="1172" alt="Screen Shot 2019-08-21 at 7 10 51 AM" src="https://user-images.githubusercontent.com/2753488/63430700-d3814380-c3e2-11e9-9e2f-84b64e2fcf56.png">

**Comment by alisonjoseph** [comment]
@emyarod confirmed w/ Jeanne and Mike we can remove these pages/links
