### ISSUE TITLE
nested items within lists dont adhere to grid properly

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#169]
I was able to indent items within my numbered list to get the list to continue. But once things are within the list, they don't align to the grid like we want it to. Seems like we have a couple options:

1 - allow nested list items to be formatted the same as unlisted items
2 - allow lists to continue starting at a specified number after breaking them

This is on the app icons/production page:

<img width="1772" alt="Screen Shot 2019-08-12 at 4 39 10 PM" src="https://user-images.githubusercontent.com/47458576/62902317-de720f00-bd24-11e9-864b-e992223b89ed.png">
<img width="1772" alt="Screen Shot 2019-08-12 at 4 38 50 PM" src="https://user-images.githubusercontent.com/47458576/62902321-e03bd280-bd24-11e9-9ab9-5a179487fef6.png">

<img width="1772" alt="Screen Shot 2019-08-12 at 4 37 01 PM" src="https://user-images.githubusercontent.com/47458576/62902326-e3cf5980-bd24-11e9-8589-c31e745d60a3.png">
<img width="1772" alt="Screen Shot 2019-08-12 at 4 36 19 PM" src="https://user-images.githubusercontent.com/47458576/62902329-e631b380-bd24-11e9-84d2-78952863ae2f.png">

**Comment by peter-garvin** [comment]
I've been looking around for a solution to this, but it seems that markdown just doesnt support starting a list at a certain number. So we can't break the list, then have it continue. But you can have things nested within the list and have the list continue.

Is there any way to have things inside within lists ignore the nested styling?

**Comment by emyarod** [comment]
I think this is an issue with the underlying Carbon component not supporting the `start` attribute, will have to take a closer look

**Comment by peter-garvin** [comment]
@emyarod @alisonjoseph Any chance we can get a fix before the site goes live on Monday? not super high priority but it would be great if we could

**Comment by alisonjoseph** [comment]
Doubtful at this point, since I'm not 100% sure HOW to fix it. We can prioritize looking into it early next week though.

**Comment by vpicone** [comment]
MDX thinks you're seperating two distinct lists with a full-width item. To make something 'belong' to the list item it follows, you just need to add 3 spaces preceding it.

This addresses both the numbering issue and the sizing of the element.

### image
```
1. Parent

![Stroke app icon masking: step 1](/images/3_2-1_MakingAnIcon_Stroke_Step1.png)

2. Next
```

becomes
```
1. Parent

   ![Stroke app icon masking: step 1](/images/3_2-1_MakingAnIcon_Stroke_Step1.png)

2. Next
```

### video (make sure to indent all lines)
```
6. Parent

   <Video
     poster="/images/3_2-3_MakingAnIcon_Stroke_Step6_PosterImage.png"
     src="/videos/3_2-3_MakingAnIcon_Stroke_Step6.mp4"
   />
```
