### ISSUE TITLE
Broken link to IBM Sketch Kit 

### ISSUE THREAD

**Issue by kellychurchill** [carbon-design-system/design-language-website#182]
## Detailed description

> Describe in detail the issue you're having.

The broken link reported below is valid and the link is missing from the design language website's new version: https://design-language-website.netlify.com/elements/pictograms/contribute

-------------------------------------------------------------
Location_Routing: contactibm (D200788G61519M52)
ERMSMailFormat: contactibm
Date: Thu, 15 Aug 2019 17:45:23 +0000

-- Request information --------------------------------------

User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6)
AppleWebKit/605..1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
Remote-host: bi-02pt1.bluebird.ibm.com 129.42.208.182
Country-code:
Referred-from: http://www.ibm.com 

-- Customer information -------------------------------------

Salutation: Mr.
First name: Kevin
Last name: Murray
E-mail address: kmurray@ibm.com
Your country of region: us
Help us answer your message: Employee
Message: The link referenced here: "Look through the pictograms in the
IBM Design Sketch kit to ensure that your proposed new pictogram is not
already represented." on this page:
https://www.ibm.com/design/language/elements/pictograms/contribute/
does not work.
comment:

**Comment by emyarod** [comment]
@alisonjoseph is there supposed to be a link in the "Look through the pictograms in the
IBM Design Sketch kit to ensure that your proposed new pictogram is not
already represented" text? I'm not seeing any broken links

**Comment by alisonjoseph** [comment]
This page is missing links from the live site, https://www.ibm.com/design/language/elements/pictograms/contribute/

**Comment by kellychurchill** [comment]
The link on this page is  still broken: https://www.ibm.com/design/language/elements/pictograms/contribute/

**Comment by alisonjoseph** [comment]
We haven't switched the live site over to the new site yet, so won't be updated until that happens.

**Comment by kellychurchill** [comment]
Any estimation on the timeline for that switch? I need to report back to the bug report from the ibm.com team.

**Comment by alisonjoseph** [comment]
Hoping this week (tomorrow), waiting on Mike final approval.
