### ISSUE TITLE
Typeface page: Sub-families section— Italics not working/using system oblique rather than Plex Italic

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#238]
- [ ]  Sub-families: Plex true italics not working — SAFARI —

.
current:
<img width="1217" alt="Screen Shot 2019-08-29 at 7 11 50 AM" src="https://user-images.githubusercontent.com/32881239/63935872-66962b00-ca2c-11e9-9c14-e7a4ee74015d.png">

**Comment by mjabbink** [comment]
- [ ]  Type tester: The selection from dropdown does not effect type in container. Both the style and weight dropdown. The default should be Plex Light.

.

<img width="1227" alt="Screen Shot 2019-08-29 at 7 10 14 AM" src="https://user-images.githubusercontent.com/32881239/63936063-f045f880-ca2c-11e9-8ee9-320472f3ff1f.png">

**Comment by mjabbink** [comment]
- [ ]  Non-Latin scripts: Arabic, Devanagari, Hebrew, Thai’s not IBM Plex

.
current:
<img width="1221" alt="Screen Shot 2019-08-29 at 7 17 44 AM" src="https://user-images.githubusercontent.com/32881239/63936211-4c108180-ca2d-11e9-9f40-e95302f5ee04.png">


.

<img width="1207" alt="Screen Shot 2019-08-29 at 7 17 51 AM" src="https://user-images.githubusercontent.com/32881239/63936232-5763ad00-ca2d-11e9-80ac-a433cf0fe287.png">

.

<img width="1179" alt="Screen Shot 2019-08-29 at 7 18 04 AM" src="https://user-images.githubusercontent.com/32881239/63936241-5cc0f780-ca2d-11e9-8171-106993f39ee3.png">

**Comment by mjabbink** [comment]
- [ ] Awards: update “TDC 64 2018“ link to —>  https://www.tdc.org/competitions/typeface-design-2018/

**Comment by emyarod** [comment]
![image](https://user-images.githubusercontent.com/8265238/63946601-fc38b700-ca3a-11e9-97fa-8376079ed173.png)

are these request URLs correct? 404s all around

**Comment by emyarod** [comment]
looks like the request URLs should be `http://ibm.com/design/language/fonts/.../` rather than `https://www.ibm.com/fonts/.../`
