### ISSUE TITLE
Style "cookie preferences" button

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#240]
Can we style this button that pops up automatically?
<img width="305" alt="Screen Shot 2019-08-29 at 8 29 54 AM" src="https://user-images.githubusercontent.com/2753488/63944510-3dc76300-ca37-11e9-85f6-8d2f1011e785.png">

**Comment by emyarod** [comment]
most likely yeah, do we have a spec for how we want it to look? also what's injecting that element, is it the tracking script?

**Comment by alisonjoseph** [comment]
![image](https://user-images.githubusercontent.com/2753488/63954441-b8e54500-ca48-11e9-90c5-9728e2b8fe9c.png)

We should match the styling on www.ibm.com/brand  (we can reach out to @william.brinkert1 on slack for questions on how they styled it if needed)
