### ISSUE TITLE
Carousel's not working

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/design-language-website#246]
Not getting anything on the color page carousel, looks like it's used differently there than on the homepage?

**Comment by alisonjoseph** [comment]
<img width="1212" alt="Screen Shot 2019-08-29 at 11 17 28 AM" src="https://user-images.githubusercontent.com/2753488/63957736-9b1ade80-ca4e-11e9-9c8a-e4aba264cb49.png">

adding a little more context. the second image should be rotating through

**Comment by emyarod** [comment]
looks like the prop name is wrong for some reason `autoPlay` vs `autoplay`
