### ISSUE TITLE
[app icons, icons, pictograms] footer nav is broken

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#254]
This was working on staging but its not on the live site. The 'next' footer nav button directs to the wrong pages

<img width="1792" alt="Screen Shot 2019-08-29 at 5 12 17 PM" src="https://user-images.githubusercontent.com/47458576/63980270-b1419280-ca80-11e9-8d43-037126ca74db.png">
<img width="1792" alt="Screen Shot 2019-08-29 at 5 12 31 PM" src="https://user-images.githubusercontent.com/47458576/63980274-b272bf80-ca80-11e9-81a9-b2dabf7a40cc.png">
<img width="1792" alt="Screen Shot 2019-08-29 at 5 12 41 PM" src="https://user-images.githubusercontent.com/47458576/63980280-b43c8300-ca80-11e9-865f-11bc23cad19b.png">

**Comment by alisonjoseph** [comment]
Whoa, weird. this seems to only be an issue on App Icons and Pictograms from what I can tell.

**Comment by alisonjoseph** [comment]
should hopefully be fixed now
