### ISSUE TITLE
Pictogram: contribute tab: number list should be inside body copy 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#258]
https://www.ibm.com/design/language/elements/pictograms/contribute/

![658B5256-3BAF-475D-83CD-70B68B129DD1](https://user-images.githubusercontent.com/32881239/64044707-7c434780-cb35-11e9-9b72-a7a4abed1955.jpeg)

**Comment by alisonjoseph** [comment]
duplicate https://github.com/carbon-design-system/gatsby-theme-carbon/issues/392
