### ISSUE TITLE
missing video

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#262]
https://www.ibm.com/design/language/elements/type-basics#comfortable-reading

**Comment by alisonjoseph** [comment]
Looks like the video is there, we are just missing the "poster" image before the video starts.

**Comment by emyarod** [comment]
any update on which image we should use as the poster?

**Comment by mjabbink** [comment]
Sadek Bazaraa will know. He created the poster in mages for lead videos

**Comment by alisonjoseph** [comment]
@emyarod the image exists looks like its just missing `.gif` on the end in the code 😄 `type-basics-comfortable-reading.gif`
