### ISSUE TITLE
Color page: lead animated gif not working

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#263]
this gif should be animating through logos

![4A40BE26-3930-45AE-8091-DFEDAB3A7CAE](https://user-images.githubusercontent.com/32881239/64064963-e4496a80-cbd5-11e9-94df-ff0814bbb0fd.jpeg)

**Comment by alisonjoseph** [comment]
Animated images aren't displaying on mobile. (Compare this page on desktop vs. mobile)

**Comment by emyarod** [comment]
looks like the carousel is completely collapsed on mobile
