### ISSUE TITLE
[Color] Language website Color page images update

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/design-language-website#272]
Final V2 color palette sketchfile: https://ibm.box.com/s/1n2c9h1ap7z05t6d2d84wkglhnfrz9bx

- [ ] Update [Language website color page ](https://www.ibm.com/design/language/elements/color) with new images using new colors. 
- [ ] Update Hover color documentation

**Comment by jnm2377** [comment]
Related: https://github.com/carbon-design-system/design-language-website/issues/326
@sadekbazaraa, do any images need to be updated to or can we close this issue?

**Comment by sadekbazaraa** [comment]
@jnm2377 if these main palette images are not linked to the color package and receiving updates automatically then we should at least update these 2 images as I've heard tales of folks taking screen shots and eye dropping from here. 

![Screen Shot 2019-10-28 at 4 01 32 PM](https://user-images.githubusercontent.com/33162280/67713540-5e129000-f99c-11e9-8434-925b43c05b20.png)

**Comment by jnm2377** [comment]
Those main images are linked to the color package. 👍

**Comment by laurenmrice** [comment]
![Screen Shot 2019-10-29 at 11 59 17 AM](https://user-images.githubusercontent.com/43969356/67790315-8e613980-fa43-11e9-802d-b34cb8e60d76.png)
 The specification images are the ones that need to be updated with the right colors. Right now they still reflect the old palette
