### ISSUE TITLE
Link to design kit broken 

### ISSUE THREAD

**Issue by alpha80147** [carbon-design-system/design-language-website#279]
## Detailed description

> Describe in detail the issue you're having.
Accessing https://www.ibm.com/design/language/ the design kit explore and create leads to a 404 page. https://www.carbondesignsystem.com/getting-started/designers#get-the-kit

> What did you expect to happen? What happened instead? What would you like to see changed?
Get me to a page to download the kit. 

> What browser are you working in?
Android Chrome

## Steps to reproduce the issue

1. Step one: Access https://www.ibm.com/design/language/ 
2. Step two: scroll down to Design kit Explore and Create
3. Step three: Click
4. etc. Enjoy the 404 page sighting 

## Additional information

- Screenshots or code
- Notes

**Comment by alisonjoseph** [comment]
Looks like this has been fixed. please re-open if I'm missing something
