### ISSUE TITLE
Pictograms library display

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/design-language-website#281]
Display pictograms similarly to icon library:

https://www.ibm.com/design/language/elements/icon-library

Blocked: @carbon/pictograms, @carbon/pictograms-react library has yet to be published.

**Comment by mjabbink** [comment]
@vpicone not sure I understand the block here.

**Comment by mjabbink** [comment]
@sadek Can you post a visual where the Pictogram Library should be in the current left nav.

**Comment by vpicone** [comment]
@mjabbink it just means we're waiting for something upstream, in this case we were waiting for the pictograms library to be released and the component to be approved.

**Comment by mjabbink** [comment]
but it’s up in Carbon site? I think it’s ready to go cotton eye joe with exception of some Pictogram issues that need fixing.

**Comment by mjabbink** [comment]
this is a high priority item to get up in IDL

**Comment by mjabbink** [comment]
Looks like this is ready to go up.
