### ISSUE TITLE
Website feedback - Hyperlinks at bottom of page are muddled

### ISSUE THREAD

**Issue by Clockray** [carbon-design-system/design-language-website#289]
## Summary
Hyperlinks at bottom of pages within the "https://www.ibm.com/design/language/elements/" pages are inconsistent.

## Relevant information
On the page "https://www.ibm.com/design/language/elements/app-icons/design/" the link at the bottom right of the page going to Next labelled "App: Icons Design" redirects to the same page. I suspect it should be labelled "App: Icon Usage" and redirect to "https://www.ibm.com/design/language/elements/app-icons/usage".
Throughout the pages with the design/language/elements the set of hyperlinks is slightly muddled. Some links go to the current page and the previous links jump whole sections. These links are in the "NextPrevious-module--wrapper" division on the page. 
I'd recommend someone go through each of the pages and make the hyperlinks consistent.

**Comment by alisonjoseph** [comment]
Duplicate https://github.com/carbon-design-system/design-language-website/issues/254
