### ISSUE TITLE
Next Buttons on some pages don't go the next page

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/design-language-website#293]
## Detailed description

In pages like App Icons and Pictograms, (it looks like pages with a second navigation of Design, Usage, and Contribute/Production) do not have buttons at the bottom of the page that advance to the next page but keeps them on the page a user is already one. 

Happening in both Chrome and Firefox.

## Additional information
A user is on the design sub-navigation but the button on the bottom right links back to the design page and not the next page.

![Screen Shot 2019-10-01 at 8 51 54 AM](https://user-images.githubusercontent.com/20582179/65968829-63c29780-e429-11e9-97d8-58252c527191.png)

The user is on the usage page but the button on the bottom right corner links them back to usage and not the next page.

![Screen Shot 2019-10-01 at 8 52 06 AM](https://user-images.githubusercontent.com/20582179/65968894-8359c000-e429-11e9-8d67-d08b8a834f7e.png)

**Comment by kingtraceyj** [comment]
i just saw that issue #254 covers this issue

**Comment by alisonjoseph** [comment]
duplicate
