### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#310]
- Remove facebook link from footer - doesn't exsit
- Typeface link on https://www.ibm.com/design/language/elements/type-specs-ui/#typeface is broken
- Remove links to 2x grid ui on 2x grid page(https://www.ibm.com/design/language/elements/2x-grid ) that don't exist anymore, link to Carbon(https://www.carbondesignsystem.com/guidelines/2x-grid/basics) instead 

### source issue / list of all links

https://github.ibm.com/duo/website/issues/1620#issuecomment-15170582
https://ibm.ent.box.com/s/ptz8cfrosk0qs8jcjznlnotxud6bsrfm

**Comment by alisonjoseph** [comment]
@greeshmareddyg

**Comment by creckling** [comment]
The link to the icons is broken too. on this tile:
![image](https://user-images.githubusercontent.com/50208035/66860406-2565c600-ef5b-11e9-899b-260c6921a846.png)
