### ISSUE TITLE
icon + pictogram library: Ai icon on resource card for "not found" message is showing up huge

### ISSUE THREAD

**Issue by conradennis** [carbon-design-system/design-language-website#311]
on IDL icon and pictogram library pages when the "not found" message shows up, the Ai icon on the resource card is gigantic:

<img width="808" alt="Screen Shot 2019-10-10 at 5 09 08 PM" src="https://user-images.githubusercontent.com/16782944/66606989-40ae8b00-eb81-11e9-9e77-eb92145d091a.png">

on Carbon site the resource card looks fine:
 
<img width="789" alt="Screen Shot 2019-10-10 at 5 09 14 PM" src="https://user-images.githubusercontent.com/16782944/66606945-25438000-eb81-11e9-9616-1dc20c48b359.png">

**Comment by vpicone** [comment]
@conradennis is this still an issue for you? Unable to replicate.

**Comment by conradennis** [comment]
@vpicone not an issue on Firefox. Still an issue on Chrome.

**Comment by alisonjoseph** [comment]
confirmed this has been fixed in Chrome
