### ISSUE TITLE
Add Arabic to the Language Support list

### ISSUE THREAD

**Issue by sethjohnsonIBM** [carbon-design-system/design-language-website#327]
## Relevant information

https://www.ibm.com/design/language/elements/typeface/ 
<img width="503" alt="Screen Shot 2019-10-23 at 12 37 22 PM" src="https://user-images.githubusercontent.com/32574988/67419296-1651ca00-f592-11e9-8445-19b7a82c5cb6.png">

**Comment by mjabbink** [comment]
@sethjohnsonIBM good catch!

**Comment by mjabbink** [comment]
@jnm2377 Is this issue resolved?

**Comment by mjabbink** [comment]
@alisonjoseph
