### ISSUE TITLE
Philosophy page Video is to tight with subsequent aside/text content

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/design-language-website#340]
<img width="1000" alt="Screen Shot 2019-11-05 at 11 33 36 PM" src="https://user-images.githubusercontent.com/4078018/68271229-839b3b80-0025-11ea-8fe9-744e7d27efb6.png">

**Comment by mjabbink** [comment]
part of spacing issues. Need to get these resolved because lingering too long.

**Comment by alisonjoseph** [comment]
fixed
