### ISSUE TITLE
Remove down state on cards

### ISSUE THREAD

**Issue by rcwakelin** [carbon-design-system/design-language-website#345]
## Detailed description

> Describe in detail the issue you're having. - See above

> What did you expect to happen? What happened instead? What would you like to see changed? - There should not be an outline with the card in the down state

> What browser are you working in? Fire Fox

## Steps to reproduce the issue

1. Step one - go to https://www.ibm.com/design/language/elements/typeface
2. Step two - click on a card
![Screen Shot 2019-11-18 at 4 57 08 PM](https://user-images.githubusercontent.com/53092894/69097429-87b35a00-0a24-11ea-9ef8-1689b3ee7ee9.png)

## Additional information

- Screenshots or code
- Notes

**Comment by alisonjoseph** [comment]
That's the focus state and needed for accessibility.

**Comment by rcwakelin** [comment]
@alisonjoseph Lets discuss the color and then apply it consistently across the sites. Its not consistent

**Comment by rcwakelin** [comment]
@alisonjoseph I cannot recreate were I found the inconsistencies. Agreed lets close.

**Comment by rcwakelin** [comment]
@alisonjoseph Strike my previous strike! Sadek and I just sat down to review the issue and  found this to be a safari issue. Re-wrote headline and story with a better description of what is happening.
