### ISSUE TITLE
[Pictogram library]: Broken Pictogram

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#347]
@conradennis Not sure if there was ever an issue for this. Feel free to close if so.
In Watson Catergory
https://www.ibm.com/design/language/elements/pictogram-library/

<img width="338" alt="Screen Shot 2019-11-19 at 2 28 08 PM" src="https://user-images.githubusercontent.com/32881239/69184288-349bde80-0ada-11ea-8d89-8f9ff6383e58.png">

**Comment by alisonjoseph** [comment]
This will need to get fixed upstream in pictogram library.
