### ISSUE TITLE
[Icon library]: Icon hierarchy & filtering

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#348]
Flatten hierarchy by removing buckets like Actions and Enterprise. https://www.ibm.com/design/language/elements/icon-library

So same model and Pictograms. https://www.ibm.com/design/language/elements/pictogram-library

@jeanservaas Do you agree. This added layer seems fussy to me and overly organized.

**Comment by mjabbink** [comment]
Let’s tackle this in Q1.

**Comment by vpicone** [comment]
@jeanservaas @mjabbink Is this still something we want to do?

**Comment by mjabbink** [comment]
yes

**Comment by vpicone** [comment]
Per slack thread, closing this for now. 

Points from slack convo:
- finding an icon in the website and being able to find it under the same dropdowns in Sketch is a nice feature of the status quo
- could flatten in either direction
- Something else to consider is how you’d sort them: if you just lumped them into large categories (say Actions), people would expect them to be sorted alphabetically. That means that all the subcategories would be shuffled in the larger category.

**Comment by vpicone** [comment]
Repoing to flatten it out
