### ISSUE TITLE
Image spacing is off on 2x grid page

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#349]
The spacing updates on the theme broke image spacing on this page 
https://www.ibm.com/design/language/elements/2x-grid/

Images should have equal spacing around them (2rem I believe)

<img width="1116" alt="Screen Shot 2019-11-20 at 9 08 38 AM" src="https://user-images.githubusercontent.com/2753488/69250520-6b730280-0b75-11ea-99e1-625fee6b348f.png">

This might be a theme issue, should I move it to that repo @vpicone

**Comment by jnm2377** [comment]
I have a PR open for this already: https://github.com/carbon-design-system/design-language-website/pull/350

It's actually not a theme issue, it's just that all of the images were in one row so it was like 8 million columns long.
