### ISSUE TITLE
Incorrect links in "No results found" Pictogram Library Page

### ISSUE THREAD

**Issue by rcwakelin** [carbon-design-system/design-language-website#352]
## Detailed description

> Describe in detail the issue you're having.

![Screen Shot 2019-11-20 at 4 36 45 PM](https://user-images.githubusercontent.com/53092894/69280323-21f5d800-0bb4-11ea-886a-67801f89ad10.png)

> What did you expect to happen? What happened instead? What would you like to see changed?
It should say and link to Pictogram version of the links

> What browser are you working in? Firefox and Chrome

## Steps to reproduce the issue

1. Step one - go to https://www.ibm.com/design/language/elements/pictogram-library
2. Step two - enter in a value that will not produce a pictogram
3. Step three - look at copy and the cards
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by mjabbink** [comment]
The cards above in the image are incorrect. The cards should NOT download icon grid or submit icon.

The resource cards should be as follows:

- [ ] Pictogram master
<img width="464" alt="Screen Shot 2019-11-26 at 6 40 07 PM" src="https://user-images.githubusercontent.com/32881239/69681491-4520fb80-107c-11ea-8760-d24621ab3384.png">

- [ ] Contribute pictogram: Resource card should lead to pictogram repo for someone to contribute or request a pictogram. 

- [ ] Currently all contribute links on Pictogram pages and including above "No results page" lead to the correct place. Should be the new pictogram repo. @ctennis Conrad Ennis to provide links





https://www.ibm.com/design/language/elements/pictograms/contribute/

**Comment by conradennis** [comment]
@mjabbink posting the links below. The pictogram repo is currently private so I'll also provide a link to the carbon repo as a placeholder just in case.

Pictogram master: https://github.com/carbon-design-system/carbon/blob/master/packages/pictograms/master/pictogram-master.ai

Contribute pictogram: https://github.ibm.com/brand/pictograms/issues/new

Contribute pictogram placeholder linking to Carbon Repo: https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+enhancement+%F0%9F%92%A1&template=feature-request-or-enhancement.md&title=

**Comment by mjabbink** [comment]
seems related to this issue
https://github.com/carbon-design-system/design-language-website/issues/311

**Comment by rcwakelin** [comment]
> Test comment for git hub
<sub>[View in Slack](https://bsxd.slack.com/archives/GM2KQDB5W/p1581521342000900)</sub>

**Comment by rcwakelin** [comment]
> Test comment for git hub
<sub>[View in Slack](https://bsxd.slack.com/archives/GM2KQDB5W/p1581521342000900)</sub>

**Comment by vpicone** [comment]
This is resolved
