### ISSUE TITLE
Update footer on Design Language Pages to match Brand Center

### ISSUE THREAD

**Issue by rcwakelin** [carbon-design-system/design-language-website#353]
11/25 updating story
Update footer on Design Language Pages to match Brand Center

-->

## Detailed description

> Describe in detail the issue you're having. - The footer on the DL pages needs to be updated

<img width="1121" alt="Screen Shot 2019-11-25 at 5 39 43 PM" src="https://user-images.githubusercontent.com/53092894/69584406-1d159780-0fab-11ea-8dd2-7cdd18381c0d.png">

Copy block 1 - Change to 
1A "Privacy" Open in new window https://www.ibm.com/privacy
1B "Terms of use" Open in new window https://www.ibm.com/legal
1C  "IBM.com" Open in new window https://www.ibm.com/
1D "Twitter" Open in new window 1D https://twitter.com/ibmdesign
1F "Instagram" Open in new window https://www.instagram.com/ibm/?hl=en

Copy block 2 - Change to 
Have questions? **Email** <mail to: branding@us.ibm.com> us or Slack
**#ibm-brand** <open in new window https://bsxd.slack.com/channels/ibm-design-language>(internal IBM users only)

Copy block 3 - Modify the date format
Last Updated 23 November 2019
Copyright ©2019 IBM

**Comment by alisonjoseph** [comment]
I think we need more details here...

What you seem to be asking for?
- remove copyright
- remove open issue link
- remove last updated date
- add link to brand? slack?

**Comment by rcwakelin** [comment]
Copy block 1 - Change to 
1A "Privacy" Open in new window https://www.ibm.com/privacy
1B "Terms of use" Open in new window https://www.ibm.com/legal
1C  "IBM.com" Open in new window https://www.ibm.com/
1D "Twitter" Open in new window https://twitter.com/IBM
1E "Facebook" Open in new window https://www.facebook.com/IBM/
1F "Instagram" Open in new window https://www.instagram.com/ibm/?hl=en

Copy block 2 - Change to 

Have questions? **Email** <mail to: branding@us.ibm.com> us or Slack
**#ibm-brand** <open in new window https://bsxd.slack.com/channels/ibm-design-language>(internal IBM users only)

Copy block 3 - Delete

![Screen Shot 2019-11-21 at 2 48 52 PM](https://user-images.githubusercontent.com/53092894/69371569-1961d800-0c6e-11ea-9df2-518e2d814162.png)

@alisonjoseph is this better?

**Comment by mjabbink** [comment]
@alisonjoseph we are not deleted date. The recommendation was to change the structure of the date to

expected:
Last update 23 November, 2019
Copyright © 2019 IBM 

current:
Last updated November 23rd, 2019
Copyright © 2019 IBM

**Comment by mjabbink** [comment]
@alisonjoseph 

There seems to be confusion regarding the social media links. I recommended only using twitter account for IDL, Event and Workplace. It does not look like there is an IBM Design Instagram account so in that case maybe we go to IBM master brand account for instagram.

- [ ]  The twitter link should go to IBM Design twitter feed. For the design sites

- [ ] No facebook

**Comment by rcwakelin** [comment]
Story updated. See top of page

**Comment by mjabbink** [comment]
The date part is Gatsby level change
