### ISSUE TITLE
Content changes to the Design Language site

### ISSUE THREAD

**Issue by rcwakelin** [carbon-design-system/design-language-website#354]
Content Changes to the Design Language Site

## Detailed description

> Describe in detail the issue you're having. - There are a variety of small changes that need to fixed across the Design Language web pages. Mostly they fall into 3 buckets. Broken Links, consistent application of when to open links in a new window and type changes. 

The needed changes can be found in https://ibm.invisionapp.com/d/main#/console/15353197/319292677/preview

**Comment by rcwakelin** [comment]
@alisonjoseph Based our our meeting I have made to issues. Let me know if this works. Thanks. -R

**Comment by mjabbink** [comment]
@alisonjoseph 
From this link down you’ll see the priority list for pages to add and the reshuffle of left navigation.
https://github.ibm.com/brand/design-language/issues/13#issuecomment-15796070
