### ISSUE TITLE
Left nav update and new pages

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#358]
@alisonjoseph
IDL top priorities

reference from IDL repo
https://github.ibm.com/brand/design-language/issues/13#issuecomment-15796070

Some of the items below have a few last minute dependencies but I wanted to capture it here.

To Do list:

**Ready:**
- [x]  Philosophy – move tabbed pages and create two pages children pages under "Philosophy" dropdown, change POV to Overview to be consistent with other pages

- [x]  Typography – nest Typeface, Type basics, Type specs UI under "Typography" dropdown

- [x]  IBM Logos – kill tabs and create two pages under dropdown
reference: https://github.ibm.com/brand/design-language/issues/77

- [x]  Iconography – nest UI Icons, App Icons, Pictograms under "Iconography" dropdown, add Library pages as tabs on UI Icons and Pictograms pages (Library | Design | Usage | Contribute)

- [x]  Photography – move tabbed pages and create two children pages under Photography 
reference: https://github.ibm.com/brand/design-language/issues/79

- [x]  Motion UI – add "UI" to page title to be more accurate, this page will become more general once we develop general motion principles and we can link to Carbon for detailed UI guidance

**Dependencies:**
- [ ]  Add Layout page (already developed and on staging. Pete to make last edit)

- [ ]  Add Resources page (Greeshma, Josefina)
reference: https://github.ibm.com/brand/design-language/issues/29

- [ ]  Add Updates section (Greeshma. Already developed and on staging but needs a few tweeks from Greeshma)
reference: https://github.ibm.com/brand/design-language/issues/26

- [ ] Add Help section. Already developed and on staging. Needs final edits from Greeshma.
reference: https://github.ibm.com/brand/design-language/issues/25

**Comment by mjabbink** [comment]
In addition to the spacing issues these set up pages and left nav reshuffle were the priorities

**Comment by mjabbink** [comment]
![f580be3e-6aca-4194-aa91-cabec6188e8d](https://user-images.githubusercontent.com/32881239/69762814-5aa82b00-1139-11ea-9ac4-113a966198e3.jpeg)

**Comment by alisonjoseph** [comment]
done!
