### ISSUE TITLE
Line length guideline update

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/design-language-website#365]
## Detailed description

On the `Type basics` page under the `Line lengths within containers` heading, the illustration shows extra padding, but it is much wider than our latest agreement between the Digital team and IDL team, which was around `90–95%`. My suggestion is to update the illustration to 
show the latest range of `90-95%`, as shown in magenta in the image below:

![Screen Shot 2019-12-03 at 1 20 18 PM](https://user-images.githubusercontent.com/30183447/70077894-b3f7da80-15cf-11ea-9d1f-fe34b2fc413e.png)

## Steps to reproduce the issue

1. visit this page: `https://www.ibm.com/design/language/elements/type-basics#line-lengths-within-containers`
2. See the illustration that shows recommended right padding.

**Comment by wonilsuhibm** [comment]
I also suggest that the `75%` in the copy in the illustration removed, it can cause confusion. :)

**Comment by mjabbink** [comment]
Good find @wonilsuhibm. We need to fix this in IDL site

**Comment by mjabbink** [comment]
We probably need some more detail on this. 95% might work well in a small card container and in a larger container definitely 90%

**Comment by mjabbink** [comment]
@sadekbazaraa This 95% does not seem to be enough. We should check with dotcom team to see what this is looking like in their components.

**Comment by sadekbazaraa** [comment]
@mjabbink I was just noticing this throughout Gatsby sites. Still seems like copy is going full width in most places. We've tackled this many times so I'm not sure why it continues to come up. It would be nice to understand the definitive rule so we can update the guidance to be accurate.

**Comment by mjabbink** [comment]
@sadekbazaraa can you share some of those screen grabs and we can discuss with Vince, Jeannie and Shix.

**Comment by sadekbazaraa** [comment]
Sure thing @mjabbink here are a handful of examples where body copy is going "full bleed".

![Screen Shot 2021-07-20 at 4 22 29 PM](https://user-images.githubusercontent.com/33162280/126390477-3d8e3934-bd57-40ad-b3c1-47958b2d93d1.png)

![Screen Shot 2021-07-20 at 4 21 36 PM](https://user-images.githubusercontent.com/33162280/126390501-f39fbacd-65c9-4608-832a-26574fbd4040.png)

![Screen Shot 2021-07-20 at 4 21 11 PM](https://user-images.githubusercontent.com/33162280/126390528-0b4498ad-2720-4e69-8636-9136bf50976c.png)

![Screen Shot 2021-07-20 at 4 18 51 PM](https://user-images.githubusercontent.com/33162280/126390551-5d024521-b8c7-4097-8a73-b081114e4aa6.png)

**Comment by mjabbink** [comment]
Thanks @sadekbazaraa. It’s especially broken with a list as it seems to push beyond the grid in that case.

@vpicone We need to address this since it’s not like a 3-year long issue that has not really ever been resolved. Over the years we’ve had at least 2–3 issues regarding this. I reckon we need to make another with very clear guidance and get this prioritized this time.

**Comment by mjabbink** [comment]
@alisonjoseph Not sure what keeps happening on this issue but it keeps coming back. Over the last few years, I feel like we have made 3–4 exact issues and it gets fixed but then it goes south again.

**Comment by vpicone** [comment]
@mjabbink totally. I'm happy to implement a fix, we just need a design spec.

**Comment by mjabbink** [comment]
Related to https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1156

**Comment by mjabbink** [comment]
I think the relative spec is also here carbon-design-system/gatsby-theme-carbon#1156

**Comment by alisonjoseph** [comment]
@vpicone 

Should be 8 col - 32px based on the spec in the link above. 
![image](https://user-images.githubusercontent.com/2753488/135637801-3f312dd3-fd66-468c-b554-e93878f2e566.png)

**Comment by alisonjoseph** [comment]
Should we move this issue to the theme repo @vpicone ?

**Comment by vpicone** [comment]
@alisonjoseph @mjabbink I'm a bit confused here. Is this in regards to all body copy on the page? The initial issue seemed to pertain just to cards.

**Comment by alisonjoseph** [comment]
I was just looking at this issue, I believe this is asking to update the guidance image? (we just merged in a fix for the actual line length bug in the theme with lists/headings).

Is there an updated image for us to drop into the website? @wonilsuhibm

**Comment by alisonjoseph** [comment]
@mjabbink I believe the body copy was fixed over here https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1156 in this PR https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1172

Going to close this issue, please re-open or create a new issue/PR with updated guidance images if needed.
