### ISSUE TITLE
Typeface color (valid-invalid) defines differ to the carbonsystem site

### ISSUE THREAD

**Issue by FlorianSchmittDE** [carbon-design-system/design-language-website#368]
IBM Design language website proposes valid & invalid typeface color examples.
Those differ to the typeface color section on the carbon design system
website.

https://www.ibm.com/design/language/elements/type-specs-ui#type-color
vs
https://www.carbondesignsystem.com/guidelines/typography/overview#type-color

**Comment by mjabbink** [comment]
I also believe the code snippet is supposed to be a DO (green) not a Do not (Red)

**Comment by vpicone** [comment]
@FlorianSchmittDE can you elaborate on the difference here? Is it that the `Normal` example is meant to have a 'correct' check mark?

**Comment by FlorianSchmittDE** [comment]
Sure. You can notice the difference in the attached screenshots.

![Bildschirmfoto 2019-12-17 um 08 20 22](https://user-images.githubusercontent.com/58469565/70973582-34c1d680-20a6-11ea-85b1-38bc91c749c1.png)

![Bildschirmfoto 2019-12-17 um 08 20 33](https://user-images.githubusercontent.com/58469565/70973593-39868a80-20a6-11ea-82ce-d842b4ce9223.png)

**Comment by FlorianSchmittDE** [comment]
The type specs in IBM's design language differ to the Carbon Typography section in those points:
• Neutral color for text
• Code snippet

**Comment by alisonjoseph** [comment]
Issue moved to [carbon-design-system/carbon-website #720](https://github.com/carbon-design-system/carbon-website/issues/720) via [**ZenHub**](https://www.zenhub.com/)
