### ISSUE TITLE
Replace image on IDL webpage—logo 

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/design-language-website#371]
Replace image on IDL page: https://www.ibm.com/design/language/elements/ibm-logos/8-bar/

The current image has a light grey background that was changed to a darker grey for better contrast.

Current situation: 
<img width="1239" alt="current" src="https://user-images.githubusercontent.com/51086727/70537776-af9c6600-1b69-11ea-93de-921a0616fc0a.png">

New image to use: 

![IBM logo grey 20](https://user-images.githubusercontent.com/51086727/70537853-ce9af800-1b69-11ea-9c55-438cf3226b59.png)

@jnm2377 please tell me if you need more info.

**Comment by mjabbink** [comment]
It’s in “clear space” section
