### ISSUE TITLE
Pictogram page updates

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#382]
- [ ] Replace single straight quote with apostrophes

- [ ] Replace “hyphens” with “en dash”

- [ ] Replace “en dashes” with “hyphens”

https://github.ibm.com/brand/design-language/issues/69

**Comment by mjabbink** [comment]
@conradennis can assist if any questions

**Comment by mjabbink** [comment]
This has to get addressed very soon please.

**Comment by vpicone** [comment]
closed by #405
