### ISSUE TITLE
Update several spacing and image issues: Pictogram , UI icon, App icons pages

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#390]
- [ ]  Spacing issues in various places in Pictogram Design page (mostly in mobile). Captions are too close to the image under it versus being 16px under the top image it belongs to.

current Pictogram page (https://www.ibm.com/design/language/iconography/pictograms/design#style)
<img width="497" alt="Screen Shot 2019-12-15 at 2 01 29 AM" src="https://user-images.githubusercontent.com/32881239/70859914-2cb83a00-1ee0-11ea-854c-dba73beed824.png">

———

<img width="494" alt="Screen Shot 2019-12-15 at 2 01 38 AM" src="https://user-images.githubusercontent.com/32881239/70859917-36da3880-1ee0-11ea-9e52-a946ec71be8a.png">

current UI icons page (https://www.ibm.com/design/language/iconography/ui-icons/design#style)

<img width="491" alt="Screen Shot 2019-12-15 at 2 03 14 AM" src="https://user-images.githubusercontent.com/32881239/70859949-be27ac00-1ee0-11ea-83fe-2abb7b4d33d2.png">

- [x]  Some images not showing up in UI icons (https://www.ibm.com/design/language/iconography/ui-icons/design#strokes)

<img width="902" alt="Screen Shot 2019-12-15 at 2 03 50 AM" src="https://user-images.githubusercontent.com/32881239/70859941-989aa280-1ee0-11ea-937a-fbd22992558f.png">

**Comment by mjabbink** [comment]
- [ ] Some images not full width in UI icons page "Design" tab
https://www.ibm.com/design/language/iconography/ui-icons/design#keyshapes

<img width="494" alt="Screen Shot 2019-12-15 at 2 03 04 AM" src="https://user-images.githubusercontent.com/32881239/70859969-11016380-1ee1-11ea-9826-489c3d963251.png">

**Comment by mjabbink** [comment]
- [ ]  update pictogram images (Conrad Ennis to supply). The below current examples should not have fills.

<img width="420" alt="Screen Shot 2019-12-15 at 2 02 10 AM" src="https://user-images.githubusercontent.com/32881239/70859991-5de53a00-1ee1-11ea-9fe6-a131ed86bb59.png">

—————

<img width="452" alt="Screen Shot 2019-12-15 at 2 02 06 AM" src="https://user-images.githubusercontent.com/32881239/70859992-650c4800-1ee1-11ea-9259-3901f13110d6.png">

**Comment by mjabbink** [comment]
@alisonjoseph and @jnm2377 Some caption spacing issues slipped through the cracks in mobile as well as some of the images widths.

Also Conrad owes you some new images.

**Comment by mjabbink** [comment]
- [ ]  App icons page caption spacing issues

https://www.ibm.com/design/language/iconography/app-icons/design#overview

https://www.ibm.com/design/language/iconography/app-icons/design#style

https://www.ibm.com/design/language/iconography/app-icons/design#elements

<img width="493" alt="Screen Shot 2019-12-15 at 10 13 43 AM" src="https://user-images.githubusercontent.com/32881239/70865550-84789480-1f24-11ea-9267-2eb239e9ad81.png">

<img width="487" alt="Screen Shot 2019-12-15 at 10 13 53 AM" src="https://user-images.githubusercontent.com/32881239/70865553-87738500-1f24-11ea-9728-d2ccae23e4e7.png">

<img width="489" alt="Screen Shot 2019-12-15 at 10 13 59 AM" src="https://user-images.githubusercontent.com/32881239/70865557-8c383900-1f24-11ea-92f7-a5348b552a36.png">

**Comment by mjabbink** [comment]
- [ ]  Space needs to be between this set of images in mobile. They are currently touching.

https://www.ibm.com/design/language/iconography/app-icons/design#ibm-plex-icons


<img width="494" alt="Screen Shot 2019-12-15 at 10 21 13 AM" src="https://user-images.githubusercontent.com/32881239/70865564-a6721700-1f24-11ea-9487-040fcf99284b.png">

**Comment by mjabbink** [comment]
@peter-garvin see above app icons issues in mobile

**Comment by mjabbink** [comment]
- [ ]  2xGrid page also has the same caption problems down the page in mobile

<img width="493" alt="Screen Shot 2019-12-16 at 8 59 02 AM" src="https://user-images.githubusercontent.com/32881239/70917157-6ffad180-1fe2-11ea-9b23-799fd406dc17.png">

**Comment by conradennis** [comment]
@alisonjoseph @jnm2377 I went through the pictograms `design` page and found a handful of images on mobile that need to be replaced. Here are the updated images: https://ibm.box.com/s/diznkx0gxcmjklfj1gtw57f4inqizg0m

**Comment by mjabbink** [comment]
Let’s get these issues done early in the new year please.

**Comment by mjabbink** [comment]
https://www.ibm.com/design/language/iconography/pictograms/design/#resources

<img width="878" alt="Screen Shot 2020-01-02 at 10 04 29 PM" src="https://user-images.githubusercontent.com/32881239/71706655-e56ced00-2dab-11ea-90d4-68b290f825e9.png">

**Comment by mjabbink** [comment]
the first issue in this thread is a biggie to resolve asap please. In mobile it is a problem as the caption is connected to the wrong image. This happens in a bad way on the icons and logos pages for example.

**Comment by mjabbink** [comment]
more images with fills.

<img width="195" alt="Screen Shot 2020-01-09 at 7 46 59 AM" src="https://user-images.githubusercontent.com/32881239/72073016-b3302380-32b4-11ea-99ab-9dbdac83fe12.png">


<img width="214" alt="Screen Shot 2020-01-09 at 7 46 55 AM" src="https://user-images.githubusercontent.com/32881239/72073017-b3302380-32b4-11ea-957e-a190677cefe7.png">

**Comment by mjabbink** [comment]
<img width="472" alt="Screen Shot 2020-01-09 at 7 46 17 AM" src="https://user-images.githubusercontent.com/32881239/72073033-bb885e80-32b4-11ea-9658-f50f94498fc6.png">

**Comment by jnm2377** [comment]
> the first issue in this thread is a biggie to resolve asap please. In mobile it is a problem as the caption is connected to the wrong image. This happens in a bad way on the icons and logos pages for example.

@mjabbink regarding the caption spacing issues, these are actually an issue with the `Column` component, and it affects all things using `Column` not just captions. Vince and I just talked about this and he will be opening an PR to add mobile styles for `Column`, which should address all issues with mobile column spacing,  this includes images touching and captions touching, etc.

> https://www.ibm.com/design/language/iconography/pictograms/design/#resources

@mjabbink Not sure why it's not working for you, but I'm seeing the image.
<img width="724" alt="Screen Shot 2020-01-14 at 12 07 26 PM" src="https://user-images.githubusercontent.com/32556167/72369789-73a77400-36c6-11ea-9aa1-897da24bdd4b.png">

**Comment by jnm2377** [comment]
> * [ ]  Some images not full width in UI icons page "Design" tab
>   https://www.ibm.com/design/language/iconography/ui-icons/design#keyshapes
> 
> <img alt="Screen Shot 2019-12-15 at 2 03 04 AM" width="494" src="https://user-images.githubusercontent.com/32881239/70859969-11016380-1ee1-11ea-9826-489c3d963251.png">

@mjabbink can we get these files in the correct size? None of the svg's have any additional styling, that's just the size the svg is, which doesn't match the size of the other svg's.

**Comment by vpicone** [comment]
@jnm2377 it looks like those two svgs share a row for some reason which is causing them to retract in mobile.

Adding `width: 100%` allows them to scale to their full width. Since they're svg's they can scale without needing a higher resolution asset.

**Comment by conradennis** [comment]
@jnm2377 @vpicone I've been making composite images for mobile when there are two images side by side in desktop. linking to the files below:

saved the first one at 2x size svg: https://ibm.box.com/s/scblpxifhuntisnpzx984o3mw7nefvtl

<img width="624" alt="Screen Shot 2020-01-14 at 3 50 16 PM" src="https://user-images.githubusercontent.com/16782944/72381572-99904100-36e5-11ea-8806-6314e18ffdcd.png">

composite SVG of the second set: https://ibm.box.com/s/6uc6gwnh8x4p6tw1bz3jof7eathy4lut

<img width="313" alt="Screen Shot 2020-01-14 at 3 50 22 PM" src="https://user-images.githubusercontent.com/16782944/72381583-9e54f500-36e5-11ea-8382-73ff15f3399e.png">

**Comment by mjabbink** [comment]
I’m assuming once the space added to h4 header is fixed it will resolve the same issues in the Gatsby demo site? It too has a ton of those situations

**Comment by mjabbink** [comment]
@jnm2377 @alisonjoseph @vpicone This same update should be applied to Carbon site. It is littered with the same issues.
