### ISSUE TITLE
Layout page: Overview: In mobile headers needs space under them

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#391]
@peter-garvin In the headers in “Point-of-view“ need space under them to separate from the text.
https://www.ibm.com/design/language/layout/overview

<img width="482" alt="Screen Shot 2019-12-16 at 9 08 18 AM" src="https://user-images.githubusercontent.com/32881239/70917961-e3e9a980-1fe3-11ea-813e-cfde83c13da1.png">

<img width="490" alt="Screen Shot 2019-12-16 at 9 08 12 AM" src="https://user-images.githubusercontent.com/32881239/70917970-e8ae5d80-1fe3-11ea-89cb-27a12920ac72.png">

**Comment by jnm2377** [comment]
closing as duplicate for #625

**Comment by jnm2377** [comment]
Jk. Thought this was in the gatsby repo. Re-opening just to track that it's fixed with a future GTC update.
