### ISSUE TITLE
Icons and Pictograms update

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#401]
I believe there has been an issue to update UI icons for quite some time. Can you check with @laurenmrice and @conradennis on this to make sure we get this covered in the next sprint. There are over 100 new UI icons.

I believe pictograms as well. @conradennis can confirm and provide details.

**Comment by conradennis** [comment]
@mjabbink the most recent batch of uI icons was merged into the repo a couple weeks ago. PR issue: https://github.com/carbon-design-system/carbon/pull/4789

**Comment by laurenmrice** [comment]
correct^ they need to be updated in the libraries still from the plugin, which should be covered in the next sprint.

**Comment by conradennis** [comment]
oh wait I'm seeing them in the Carbon library

**Comment by mjabbink** [comment]
Ok great. Maybe I was thinking Pictograms?

**Comment by laurenmrice** [comment]
i am referring to the icon libraries and idl libraries in Sketch aren't up to date with the newest additions.

**Comment by mjabbink** [comment]
@alisonjoseph and @mattrosno Can we get this accomplished. Before this issue another was created for weeks prior. Lauren has the details but it needs to be tacked in the next week or two tops.

**Comment by vpicone** [comment]
@mjabbink the website is using the latest icons/pictograms. Are there some icons that aren't on the website?

If we're talking about the sketch plugin the issue for that is over on the monorepo: https://github.com/carbon-design-system/carbon/issues/4130

**Comment by mjabbink** [comment]
Sketch plug-in for Pictograms. Sorry, I was not clear on this issue. Best to touch base with @laurenmrice

**Comment by jnm2377** [comment]
Closing this issue then since it's referring to the sketch plugin, and there's already an issue for it in the monorepo. see https://github.com/carbon-design-system/design-language-website/issues/401#issuecomment-572329241
