### ISSUE TITLE
Logo page: Missing/broken image

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#404]
https://www.ibm.com/design/language/ibm-logos/8-bar#alignments

The “logo alignments” image is missing

<img width="1193" alt="Screen Shot 2020-01-06 at 9 17 30 PM" src="https://user-images.githubusercontent.com/32881239/71865960-3b060a00-30ca-11ea-8ee1-84d5c8b7ccfe.png">

**Comment by jnm2377** [comment]
what designer has the svg for this? Looks like the file itself is missing. @mjabbink

**Comment by sadekbazaraa** [comment]
@jnm2377 here is the missing .svg 

[logo_alignments.svg.zip](https://github.com/carbon-design-system/design-language-website/files/4060561/logo_alignments.svg.zip)
