### ISSUE TITLE
Spacing after headings to tight (mobile)

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#418]
Mobile

Space after H3 is too tight. Needs 24px I think @jeanservaas @Peter-Garvin

current examples:
<img width="490" alt="Screen Shot 2019-12-16 at 9 08 12 AM" src="https://user-images.githubusercontent.com/32881239/71699418-f9512880-2d84-11ea-8391-88cd6587d660.png">
https://www.ibm.com/design/language/layout/overview#essential

———

<img width="479" alt="Screen Shot 2020-01-02 at 5 24 52 PM" src="https://user-images.githubusercontent.com/32881239/71699431-08d07180-2d85-11ea-80fa-7309b6564b6f.png">

https://www.ibm.com/design/language/philosophy/principles#uniquely-unified

**Comment by vpicone** [comment]
- Migrate `h4`s to use new `Title` component from theme 
- fix the h3s in columns that wrap
