### ISSUE TITLE
[IDL]: Update links and make images clickable

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#457]
- [ ]  the `here` link in copy should go to

https://www.ibm.com/design/language/iconography/pictograms/design

<img width="786" alt="ecf68b28-aca4-472c-8ebe-f51c1bd3909e" src="https://user-images.githubusercontent.com/32881239/75809817-f8ba1b80-5d4e-11ea-8512-55ae90957be5.png">

**Comment by mjabbink** [comment]
...enhancement to our `UI Icon` and `Pictogram` libraries by... should link to:
icons: https://www.ibm.com/design/language/iconography/ui-icons/library
pictograms: https://www.ibm.com/design/language/iconography/pictograms/library

<img width="894" alt="Screen Shot 2020-03-03 at 1 02 43 PM" src="https://user-images.githubusercontent.com/32881239/75810128-9877a980-5d4f-11ea-8e06-a74ec92bb34a.png">

**Comment by mjabbink** [comment]
![IDL Updates What's new](https://user-images.githubusercontent.com/32881239/75815527-2dcb6b80-5d59-11ea-813a-6e62c585dbb0.png)

**Comment by mjabbink** [comment]
@vpicone
@sadek mentioned updating links himself in markdown but the clickable image should probably be a gatsby theme issue.

**Comment by vpicone** [comment]
@mjabbink Images as links are possible today without needing anything extra from the theme.

We just don't do that on any other pages or sites so discoverability of that behavior would probably be pretty low. Can definitely give it a shot here if you want though.

**Comment by sadekbazaraa** [comment]
@vpicone I just created a PR in an attempt to get to a staging link to see if the changes I made work. I tried to upload two images to the src/pages/images directory but didn't have access.

The PR is here:
https://github.com/carbon-design-system/design-language-website/pull/458

I probably broke 10 rules and protocols along the way but hopefully it's pretty close.

FYI @mjabbink

**Comment by sadekbazaraa** [comment]
These were the two images:

![IBM_stationery](https://user-images.githubusercontent.com/33162280/75823900-8e19d780-5d70-11ea-8034-e2361063593e.png)

![IBM_data_vis](https://user-images.githubusercontent.com/33162280/75823901-8eb26e00-5d70-11ea-8bfa-b9cfe851c7f8.png)

**Comment by vpicone** [comment]
@mjabbink @sadekbazaraa pushed some fixes to your PR, super impressed you figured out how to fit the images and links together. I was about to have to look it up haha.

One question: The new stationary system lives under brand which requires an IBM login. I don't think it's a big deal, just want to remind you it'll prompt folks to log in if they're not IBMers.

**Comment by mjabbink** [comment]
@vpicone That is a good point we overlooked. I think maybe adding some text in parenthesis after the link (and maybe also included in the link). Might at least help those who will face the login.
