### ISSUE TITLE
Typo with "ecreativity"

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/design-language-website#477]
https://www.ibm.com/design/language/philosophy/principles

> IBM Design principles are carefully considered, uniquely unified, `ecreativity` our brand demands and our clients deserve.

I don't know what `ecreativity` means / is that a word? The commit: https://github.com/carbon-design-system/design-language-website/commit/f8dafd3e49d3c0311b1b0760116f86ff2bdfe71d.

**Comment by alisonjoseph** [comment]
@greeshmareddyg looks like you made this edit, are you able to go back and double check what the text should be here?
