### ISSUE TITLE
[IDL]: Help : Support page needs added space between numbers and letters in order list

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#484]
https://www.ibm.com/design/language/help/support#questions

![Screen Shot 2020-03-26 at 3.44.49 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/f7aa527c-d564-4d5d-bb13-ada033bfc6ee)

**Comment by vpicone** [comment]
@mjabbink to help isolate this, could you verify if the list style is broken in the theme as well? https://gatsby-theme-carbon.now.sh/components/markdown#lists

**Comment by mjabbink** [comment]
It’s the same in GT. Maybe we keep this as is. This way is space efficient but not necessarily good for a user. The breaks would be nice but let’s leave as is.
