### ISSUE TITLE
[IDL and Carbon] Pictograms and Icons contribute pages link to the wrong repos

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#485]
this page:
https://www.ibm.com/design/language/iconography/pictograms/contribute/#contribution-process

and link should go here:
https://github.ibm.com/brand/pictograms/issues

@conradennis 
The copy in this contribution section should get updated. Did you work with Lori on this?

**Comment by conradennis** [comment]
issue addressing this with copy/link updates from Lori: 
https://github.ibm.com/brand/bxd/issues/81

**Comment by mjabbink** [comment]
see copy/links updates from Lori: 
https://github.ibm.com/brand/bxd/issues/80

**Comment by mjabbink** [comment]
@conradennis can you confirm this issue is capturing the ones from IDL board.

**Comment by conradennis** [comment]
update to links used on Carbon/IDL contribution pages:

**PICTOGRAMS**

issues: https://github.ibm.com/brand/Pictograms/issues/new/choose

single pictogram issue: https://github.ibm.com/brand/Pictograms/issues/new?assignees=&labels=&template=single-pictogram-for-approval.md&title=%5Bpicto%5D

batch pictogram issue: https://github.ibm.com/brand/Pictograms/issues/new?assignees=&labels=&template=batch-pictogram-approval-request.md&title=%5Bpicto-batch%5D

**UI ICONS**

issues: https://github.ibm.com/brand/ui-icons/issues/new/choose

single icon: https://github.ibm.com/brand/ui-icons/issues/new?assignees=&labels=&template=single-ui-icon-approval.md&title=%5Bui-icon%5D

batch icon: https://github.ibm.com/brand/ui-icons/issues/new?assignees=&labels=&template=batch-ui-icon-approval-request.md&title=%5Bui-icon-batch%5D

**Comment by conradennis** [comment]
also see: https://github.ibm.com/brand/bxd/issues/77

**Comment by LMapes** [comment]
@mjabbink this also should reference  https://github.ibm.com/brand/bxd/issues/81. Because both the UI Icons and Pictograms contribute processes on Carbon pages should mirror the changes we made in IDL Pictograms and UI Icons Contribute pages.

**Comment by vpicone** [comment]
@mjabbink @conradennis the link that you sent is to internal Github so only IBM employees with Github enterprise logins would be able to open issues. is that the entent?

**Comment by mjabbink** [comment]
@vpicone yes, for now only people with IBMid’s

The urgent part of this issue is this first so at least the link is correct for now.
https://github.com/carbon-design-system/design-language-website/issues/485#issue-588770504

**Comment by mjabbink** [comment]
@andreancardona @conradennis It’s very urgent to at least correct the link right now. It’s aiming people to wrong repo

**Comment by andreancardona** [comment]
@mjabbink This has been updated in this PR here: https://github.com/carbon-design-system/design-language-website/pull/556

**Comment by mjabbink** [comment]
@vpicone I think or hope this will be solved when we move things to public. Let me know if that will not solve this.
