### ISSUE TITLE
Yikes! [IDL] Typeface page: IBM Plex Arabic is not showing and defaulting to system Arabic

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#488]
https://www.ibm.com/design/language/typography/typeface/#non-latin-scripts

![Screen Shot 2020-03-27 at 3.24.39 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/5c6fc3c6-14be-45c2-b066-562087b110a0)

**Comment by mjabbink** [comment]
This is still an issue.

**Comment by vpicone** [comment]
@mjabbink hmm checking it out
