### ISSUE TITLE
[IDL] Type specs UI: add periods in Do not cards

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/design-language-website#491]
url: https://www.ibm.com/design/language/typography/type-specs-ui/

two do not cards need a period at the end of the sentence as per Lori QA:

<img width="400" alt="do dont" src="https://user-images.githubusercontent.com/51086727/78123642-27dbaf80-7417-11ea-814b-fb89f0e71aef.png">

To do:
Add images with periods at the end of sentences for both cards

Exported images are here: fixed card images are here: https://ibm.box.com/s/jub63lxoladxobva85apa5vcsz2bo9tr

**Comment by mjabbink** [comment]
@DianaStanciulescu Is this something you can tackle in markdown? These are the kind of jobs I’m hoping design team can tackle and edits to copy should be Lori and Peggy.

**Comment by DianaStanciulescu** [comment]
yes, actually I can and will.  I made the issue before I was confident about this. it's an svg that's why I will do it and not lori /peggy.

**Comment by DianaStanciulescu** [comment]
made a PR: https://github.com/carbon-design-system/design-language-website/pull/510

**Comment by DianaStanciulescu** [comment]
done, it is live
