### ISSUE TITLE
[IDL] Home page - photos fix 

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/design-language-website#497]
url: https://www.ibm.com/design/language/

On the IDL Home page there are a few photos that have some problems:
- the carbon component image needs to have the components smaller in the field
- the desktop photography image with the divers on the beach is wrong, it needs a different crop
- the mobile photography images, wind turbines and divers, have weird crops, I created square crops for mobile, IF the component becomes a square image with card underneath (like the watson XG site) right now it behaves differently, not sure if it's correct

all images mentioned are here:  https://ibm.box.com/s/76653v0l3sxb73rqzgpnr377v7kzfx56

**Comment by vpicone** [comment]
looking into this

**Comment by mjabbink** [comment]
@vpicone moved this to Brand Prioritized
