### ISSUE TITLE
[IDL] Create data viz pages

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#498]
Top priority for IDL

see issue in IDL private repo
https://github.ibm.com/brand/design-language/issues/87

Just a reminder that this is my top most priority for IDL @vpicone. This is one of those issues that has been not moving nearly fast enough and long overdue to be live on IDL

**Comment by vpicone** [comment]
@mjabbink @greeshmareddyg has an open PR for this here: https://github.com/carbon-design-system/design-language-website/pull/471

When I asked on 3/27 Greeshma said there were still content changes to be made.

**Comment by mjabbink** [comment]
@greeshmareddyg and @vpicone I’m unaware of any content updates needed. @vpicone Can you continue with other development work on this issue?

**Comment by vpicone** [comment]
@mjabbink @greeshmareddyg has an open PR for this work here: https://github.com/carbon-design-system/design-language-website/pull/471

Deploy preview: https://deploy-preview-471--design-language-website.netlify.com/

She said in slack she would finish the PR now that we're no longer doing the modal/overlay. To start from scratch now would be a big waste of time/effort. 

I'm unclear as to what she needs to do to finish, she still has it marked as "Work in Progress"

**Comment by mjabbink** [comment]
@vpicone —This is almost done but Dana needed to update a few images which I think she did and we are looking into adjusting an animation.

Last major item was to make add the button with outgoing icon on the hovers . This is exactly the Pictogram library pattern It will let people know they are leaving IDL site at least until the overlay pattern can get resolved.

**Comment by vpicone** [comment]
It’ll need to be after Dana’s gets merged so we’re not stepping on each other’s toes editing the same stuff.

**Comment by mjabbink** [comment]
I think this is ready for you to add the launch out icon/hover like in Pictogram library

**Comment by vpicone** [comment]
@mjabbink those pages still aren't live yet are they? Still need to merge greeshma's PR

**Comment by mjabbink** [comment]
They are not live

**Comment by mjabbink** [comment]
@sstrubberg @vpicone Some of these pages can get updated with the new mini resource card component.

**Comment by mjabbink** [comment]
These pages are live. Closing this issue unless I’m missing something.
