### ISSUE TITLE
[IDL] Iconography > App icons > Gallery

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/design-language-website#512]
Create a new Gallery tab in the App icons page:

![App icon library](https://user-images.githubusercontent.com/51086727/78987717-7421a080-7b37-11ea-9ea6-c8294268d9b5.png)

from Peter Garvin:
master here: https://github.ibm.com/brand/App-icons/raw/master/App_Icon_Master.ai
all icons SVG and uploaded to the repo here:
https://github.ibm.com/brand/App-icons/tree/master/svg

sketch file here: https://ibm.box.com/s/yoni7ot52baszyczgouoe7sp5s86xrtu

**Comment by vpicone** [comment]
MVP for this would be replicating the pictogram and icon library functionality. However, these aren't distributed by Carbon so don't have the associated metadata which would need to be provided (linking the icons to their group/category)

If we add the dark mode it would need to be for all the pages (icon, pictogram, and app icons), not just one. @laurenmrice were you able to find anything related to dark mode/themes in the original spec for the pictogram/icon library work?

**Comment by DianaStanciulescu** [comment]
@vpicone I need your help or somebody's from your team to code this. I left a bunch of notes on the side of the mockup, and other than that just wanted to make sure this is clear? please tell us what you need from us. thanks!

**Comment by DianaStanciulescu** [comment]
@mjabbink @peter-garvin tagging you so you are aware of the conversation. thanks!

**Comment by vpicone** [comment]
@DianaStanciulescu we have a lot of brand projects going on right now. Need @mjabbink to prioritize this work. This isn't an easy project at all.

**Comment by DianaStanciulescu** [comment]
@vpicone , Peter already did the naming/exporting of svgs, we can categorize them , but the code needs to order icons by file name, and then we need to fill in in some document what friendly name to display for each, and add in all the tags/aliases. We can do that with your guidance.

Prioritization is not up to me, of course, I know you are super busy, and the project is indeed not that simple. Thanks!

**Comment by vpicone** [comment]
@DianaStanciulescu yeah getting the data together is the easy part. Even offering guidance requires a lot of research/time. 

Are they ordered by icon name or by group? @conradennis might be able to help you with getting the metadata together. Should be the same as icons/pictograms.

**Comment by DianaStanciulescu** [comment]
@vpicone we were thinking they are grouped in 3 separate categories  (stroke icons, fill, and ibm plex), and then ordered by file name, and that we will name them with any group denominator in front to keep groups together (for example, there are 3 icons named A, G, and  X, and to keep them together we will name them Maximo-A, Maximo-G, Maximo-X)

**Comment by vpicone** [comment]
#That could work, I’d use an underscore so if the company name has two words you can use a hyphen there.

**Comment by mjabbink** [comment]
@DianaStanciulescu We need to lighten Vince}s load for a few weeks. Too many think going that we need Vince to take care of. This can back burner or you can go for it in markdown. If too complicated for you no problem we’ll pick it up in a few weeks on the dev side when we can.

**Comment by DianaStanciulescu** [comment]
Hi! I think coding this is a bit too difficult for me, but until Vince & team have time to take this on, I can coordinate with Pete to see what preparation work we need to do. Thanks!

**Comment by mjabbink** [comment]
@DianaStanciulescu What else can you do in the meantime on this?

**Comment by DianaStanciulescu** [comment]
@mjabbink I am preparing the yml files with the metadata. I talked to pete, conrad, josh black. it's WIP

**Comment by DianaStanciulescu** [comment]
hi @mjabbink , @vpicone , we put together the drafts for the yml files : https://ibm.box.com/s/wxn4zx99wn4yx8q0iyrcxslgcg0v0u3c

all icons SVG and uploaded to the repo here:
https://github.ibm.com/brand/App-icons/tree/master/svg

sketch file here: https://ibm.box.com/s/yoni7ot52baszyczgouoe7sp5s86xrtu

this should be ok to go to dev when there is an opening. 

thanks!

**Comment by mjabbink** [comment]
Thanks @DianaStanciulescu. One small detail in the Sketch file is the tabs are not the correct height.

**Comment by DianaStanciulescu** [comment]
@mjabbink  right! cleaned-up file: https://ibm.box.com/s/4ul152s12lm8g6fkdj2bgvseelo21s0c

**Comment by mjabbink** [comment]
@peter-garvin Does @DianaStanciulescu have your latest app icon master? Who will be making the individual assets for the library?

**Comment by peter-garvin** [comment]
Ive made the assets already, but havent gotten in the most recent handful. Before we publish, let me review the files - there are some added, and some of the unassigned ones that have been assigned. Current assets are here: https://github.ibm.com/brand/App-icons/tree/master/svg

**Comment by mjabbink** [comment]
@peter-garvin I fee like there are 4–5 more since you last posted above.

**Comment by peter-garvin** [comment]
yes theres maybe 20–30 more that I'll need to package up. they just keep coming

**Comment by mjabbink** [comment]
@vpicone @sstrubberg. Please make this a priority for the next sprint.

**Comment by peter-garvin** [comment]
@Lori-Mapes @DianaStanciulescu @pbenson
I've uploaded a new batch of icons that need metadata as well. Here is a spreadsheet of new icons and icons that have been assigned and renamed. Anything that doesnt have an entry in the Old Name field is a net new icon

[New app icons.xlsx](https://github.com/carbon-design-system/design-language-website/files/5064194/New.app.icons.xlsx)

**Comment by peter-garvin** [comment]
theyre labelled light theme but the same info applies to the dark theme version as well

@mjabbink that was 55 new icons!

**Comment by LMapes** [comment]
@peter-garvin I see these.

**Comment by pbenson322** [comment]
@peter-garvin @LMapes  I see them, too.

**Comment by LMapes** [comment]
@DianaStanciulescu is it possible to get another Word file so we can add the metadata?

**Comment by DianaStanciulescu** [comment]
hi @LMapes ! these were the latest word files that you and peggy worked on, the light version and the identical dark one : https://ibm.box.com/s/wxn4zx99wn4yx8q0iyrcxslgcg0v0u3c

**Comment by LMapes** [comment]
@peter-garvin @DianaStanciulescu @pbenson322 has the files now to make edits.

**Comment by vpicone** [comment]
@DianaStanciulescu @peter-garvin looks like the metadata hasn't been updated for a bit do we have an up to date version and location for the final app icon files?

**Comment by peter-garvin** [comment]
@vpicone 

1. yes the latest files are there
2. yes
3. not always identical, i'll leave out some words like 'for' or 'and', maybe abbreviations for products that use abbreviation themselves. Is there anything currently that is non-latin? I know some have a ~ in order to put unassigned icons at the bottom of the list alphabetically. Open to suggestions
4. @DianaStanciulescu may know more about this, 5 and 6, I havent touched the metadata

@vpicone @conradennis What is the best way to continue to add icons to this? I'm not sure how its done for UI icons but I'd like to get a process nailed down that is easy to update

**Comment by vpicone** [comment]
@peter-garvin this is the one that stood out as non-latin: `app-icon-light-新视界.svg`. 

In regards to the tilde, `_` is a more standard prefix for distinguishing internal/unused files. However, using it would, would move them to the _top_ of the list when sorted (not sure if that's an issue?). I have an idea though: what if _instead_, we named them then used an `unused: true` piece of metadata to track that? Then we could distinguish/filter `unused` icons on the website and avoid folks fat-fingering the file name when the icon changes to being used.

It'd be best if the file names were exactly the `name`, otherwise we'll need a _separate_ metadata property with the exact file name (so we can loop over the metadata and pull in the corresponding files). I think it's easier to just keep them the same.

Would you be okay with a PR to remove `app-icon-light` and `app-icon-dark` from the name/filename? That way we just have to change the directory we're pulling the image from. If the filename is the same between light and dark, then we only need one metadata file. This will reduce human errors caused from trying to keep the `light` and `dark` yaml's in sync.

**Comment by peter-garvin** [comment]
ahhh ok i forgot about that one, I can change that. I agree with your suggestions

**Comment by DianaStanciulescu** [comment]
@vpicone we did fill in the aliases as they were searchable keywords, since this is my understanding of how they are used? I though the name "alias" was set in stone and part of the yml file structure.  Anyway - the aliases are indeed there to help searches, they are not alternate names for the app icons.

I added the stroke/fill/... etc as aliases also for search reasons, and also to help us sort through the files easier.  if they need another category we can change the structure of the file but need your guidance to do so.

As for the category names, I followed the structure of the IDL app icons guidance. I think it's ok to keep it like this for now; it also does not bother me to read "fill app icons", it's useless but "fill" alone feels less expressive and weird. Also since there was a decision to name the text ones "IBM Plex app icons" we should keep the name the same.

<img width="482" alt="Screenshot 2020-08-24 at 13 21 30" src="https://user-images.githubusercontent.com/51086727/91034033-00c38b80-e60d-11ea-80c3-daa9246f68c8.png">

FYI @LMapes

**Comment by LMapes** [comment]
@DianaStanciulescu Here is the metadata file you seek. https://ibm.box.com/s/k3gd5gpdxyrpepnfuoycvkom7m0qb105

**Comment by vpicone** [comment]
@DianaStanciulescu any updates on the metadata just yet?

**Comment by DianaStanciulescu** [comment]
@vpicone I just started working on it, and realized that the new icons are missing aliases & category, so I am now going through all of them adding this and making the changes we discussed. 

I am working in here: https://github.com/carbon-design-system/design-language-website/pull/719

I hope to have it done by the end of the day today or tomorrow

**Comment by DianaStanciulescu** [comment]
@vpicone done! there should be another round of cleanup but I think this version can work as a v1. I still need to figure out where to place the dark/light switcher for the entire page, I will work on that next.

**Comment by vpicone** [comment]
@DianaStanciulescu great thanks!

**Comment by DianaStanciulescu** [comment]
@peter-garvin @sadekbazaraa, we discussed with Vince the placement of the dark/light tabs on the page, and it would be simpler for a user to have a single set of tabs for the entire page; this way, searching or going for one category to the next will not affect the displayed bg color. This is a solution I was thinking of, do you think the search bar remains too small? Should we remove the dropdown and leave the search + tabs only (since there are only 3 categories)?

![App icons library v4](https://user-images.githubusercontent.com/51086727/92462708-7b76d400-f1d3-11ea-8b67-fc7f1137c132.png)

**Comment by sadekbazaraa** [comment]
@DianaStanciulescu I think this solution could work as well. I wonder if it breaks the patterns that we're using anywhere else for similar functionality? I think some of these considerations came up for the new data vis color section on the Carbon site which I don't think is live just yet.

**Comment by DianaStanciulescu** [comment]
@sadekbazaraa this is the reason I initially removed the tabs from the top bar; however, the experience would be worse, and the page has extra functionality vs the UI icon and pictos page, so I am thinking it is ok to break that pattern.

**Comment by mjabbink** [comment]
@DianaStanciulescu I think the tabs/dropdown can align on the app icon grid. Worth a try but maybe the containers will be too small?

**Comment by mjabbink** [comment]
an I do think it’s worth effecting the whole page between dark/light icons

**Comment by DianaStanciulescu** [comment]
Yes, the dropdown&tabs can and should align to the grid. This is the updated mockup, the sketch file is here: https://ibm.box.com/s/yoni7ot52baszyczgouoe7sp5s86xrtu


![App icons library v5](https://user-images.githubusercontent.com/51086727/92596268-3ecbdb00-f2ae-11ea-8beb-6af416ab1518.png)

**Comment by peter-garvin** [comment]
could also look at dropdown like carbon demos

<img width="1013" alt="Screen Shot 2020-09-09 at 11 23 40 AM" src="https://user-images.githubusercontent.com/47458576/92625991-f5b85e80-f28e-11ea-8c87-c6847f58d884.png">

**Comment by DianaStanciulescu** [comment]
might be a good idea, especially if we want to add monochrome at some point in the future or other variant

**Comment by mjabbink** [comment]
Agree

**Comment by mjabbink** [comment]
:lightningbolt:

**Comment by mjabbink** [comment]
Looking forward to seeing this page on the glass.

**Comment by peter-garvin** [comment]
i might recommend trying gray 20 for vertical dividers between dropdowns, and I dont know that you need the labels above here

**Comment by DianaStanciulescu** [comment]
@peter-garvin agreed; @vpicone sketch file is [here:](https://ibm.box.com/s/6s8ruvg6ej4n7opf8qfq593bcj5o4g2z) , this should be ready to go. please tell me if you need any changes to metadata or design.

<img width="675" alt="Screenshot 2020-09-11 at 14 26 06" src="https://user-images.githubusercontent.com/51086727/92920494-073e6980-f43b-11ea-886e-85ddef6b9fbf.png">
