### ISSUE TITLE
[IDL] Color page needs proper apostrophes in Don’ts

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#515]
@sadekbazaraa not sure if you can make these edits quickly.

https://www.ibm.com/design/language/color

All the Do not captions need curly apostrophes (’)

![Screen Shot 2020-04-15 at 12.26.41 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/898e4eaf-dfdf-4d77-8d3c-d80e9a9b4dc3)

![Screen Shot 2020-04-15 at 12.26.51 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/3207ad81-5f3f-4451-a153-cfdea1a3fa80)

![Screen Shot 2020-04-15 at 12.26.57 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/a8bd54ac-b81f-4608-8737-cf9a2ff0946a)

**Comment by sadekbazaraa** [comment]
@mjabbink I created an issue last week to add the 'Edit this page on Github' link back to the pages. If that was at the bottom of the page it'd be super quick.

@vpicone is this simple enough to put back in? https://github.com/carbon-design-system/design-language-website/issues/505

**Comment by mjabbink** [comment]
Let’s add it back in.
