### ISSUE TITLE
Add better UX around linking out to Carbon charts

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/design-language-website#518]
Instead of the whole card being a button, the charts should have an action button (like the Icon/Pictogram cards) with an "outgoing link" icon and tooltip text that indicates "Carbon implementation"

<img width="223" alt="Screen Shot 2020-04-17 at 11 17 48 AM" src="https://user-images.githubusercontent.com/4078018/79590725-18a66400-809d-11ea-8c0b-7980de91e887.png">

**Comment by vpicone** [comment]
@andreancardona this one won't be ready until the data vis pages are merged

@mjabbink do you know when that might be?

**Comment by mjabbink** [comment]
Waiting for designer to return from vacay. I think sometime mid week we can release
