### ISSUE TITLE
[2x Grid] Missing poster image

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#530]
Missing poster image for divisions of two. Not sure whats happening here, markdown looks correct.
Should be this image: https://github.com/carbon-design-system/design-language-website/blob/master/src/pages/images/divisions-of-two.jpg

<img width="1680" alt="Screen Shot 2020-04-28 at 10 03 29 AM" src="https://user-images.githubusercontent.com/47458576/80503471-86714c00-8937-11ea-8afb-c73b3e3e9966.png">
<img width="1158" alt="Screen Shot 2020-04-28 at 10 04 34 AM" src="https://user-images.githubusercontent.com/47458576/80503593-b3256380-8937-11ea-82fd-76c3be22d5c8.png">

**Comment by andreancardona** [comment]
# Testing Instructions: 

- [ ] Navigate to deploy preview: https://deploy-preview-538--design-language-website.netlify.app/design/language/2x-grid

- [ ] 2x grid should now have the image as seen below:
![Screen Shot 2020-05-04 at 2 21 04 PM](https://user-images.githubusercontent.com/32720851/81004833-9d6ddd80-8e12-11ea-93a8-73655a9c4f07.png)

**Comment by peter-garvin** [comment]
Looks good to me! Thanks Andrea

**Comment by mjabbink** [comment]
Release

**Comment by mjabbink** [comment]
:+1: @andreancardona

**Comment by mjabbink** [comment]
@andreancardona let’s get this released please
