### ISSUE TITLE
[IDL] Typeface page the type tester should default to larger size in desktop and mobile

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#536]
Thew default size has reverted to something very small. 

In desktop it was like 50% through the slider as the default and in  mobile it was like 25%

**Comment by andreancardona** [comment]
# Testing Instructions: 

- [ ] Navigate locally to: https://www.ibm.com/design/language/typography/typeface/ 

- [ ] The default slider size should now be `50%` in desktop as seen below
<img width="962" alt="Screen Shot 2020-05-01 at 1 46 52 PM" src="https://user-images.githubusercontent.com/32720851/80832570-85981e80-8bb2-11ea-803d-82c1870949a6.png">


- [ ] The default slider size should now be `25%` in desktop as seen below
<img width="377" alt="Screen Shot 2020-05-01 at 1 46 39 PM" src="https://user-images.githubusercontent.com/32720851/80832588-8b8dff80-8bb2-11ea-8fa7-15c56d0af050.png">

**Comment by mjabbink** [comment]
Looks good!

**Comment by mjabbink** [comment]
Can we release?

**Comment by mjabbink** [comment]
:+1: looks good @andreancardona

**Comment by mjabbink** [comment]
@andreancardona the dropdowns are defaulting in a open state now

<img width="1026" alt="Screen Shot 2020-05-07 at 1 32 42 PM" src="https://user-images.githubusercontent.com/32881239/81331709-9be92300-9067-11ea-9fbf-7d84000ddb8e.png">
