### ISSUE TITLE
[Illustration - Isometric] broken margin between images on mobile

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#539]
On mobile breakpoint, these two items run into each other. Markdown looks correct to me, i'm not sure what causes this. 

![IMG_5908](https://user-images.githubusercontent.com/47458576/81189976-dcb83d80-8f7c-11ea-9652-4fc96abd5dab.PNG)

**Comment by jnm2377** [comment]
The markdown is actually not correct for this. Whoever added this example used the old do-dont example, which has incorrect spacing. It should be using the new `DoDontRow` and `DoDont` component, which have the correct spacing. https://gatsby-theme-carbon.now.sh/components/DoDontRow

**Comment by mjabbink** [comment]
same as #520

**Comment by mjabbink** [comment]
@jnm2377 Your magic can fix or @peter-garvin if you’re confident in markdown to update?
