### ISSUE TITLE
[IDL] Typeface page > Slider is broken

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#544]
Slider component no worky

https://www.ibm.com/design/language/typography/typeface#type-tester

**Comment by mjabbink** [comment]
Definitely broken and not functional as a slider.

**Comment by mjabbink** [comment]
@vpicone TJ recommends to address with your solution you posted in Systems repo.

**Comment by vpicone** [comment]
@mjabbink I did, that solution didn’t work in production that’s why I deleted it from the original issue.

**Comment by mjabbink** [comment]
Ok, not sure what is the next step but it needs to be addressed because we can’t have a broken component on the site

**Comment by vpicone** [comment]
@mjabbink I don’t like having broken things on the website either. It’s a severity 1 bug over in Carbon: https://github.com/carbon-design-system/carbon/issues/6039
