### ISSUE TITLE
[Data Vis] Missing chart anatomy video on Design/Basics

### ISSUE THREAD

**Issue by sadekbazaraa** [carbon-design-system/design-language-website#557]
https://www.ibm.com/design/language/data-visualization/design/basics/#chart-anatomy

![Screen Shot 2020-05-28 at 12 57 33 PM](https://user-images.githubusercontent.com/33162280/83170779-0f200b00-a0e3-11ea-8314-06198d6c2bdb.png)

@vpicone @sstrubberg @mjabbink

**Comment by mjabbink** [comment]
Can we get this fixed today? I’ve been stopped twice in referencing/sharing/presenting this page because of the missing video.

**Comment by andreancardona** [comment]
@mjabbink It is being reviewed - just have to wait on approvals
