### ISSUE TITLE
[IDL Animation] Gif/video player functionality

### ISSUE THREAD

**Issue by sadekbazaraa** [carbon-design-system/design-language-website#559]
PR: https://github.com/carbon-design-system/design-language-website/pull/548

@vpicone @sstrubberg I'm using a combination of animated Gifs and Mp4s within the Do/don't component where animated examples are needed. The intended behavior is for these examples to autoplay. It's necessary that the videos play and loop side by side in order for them to be effective.
https://design-language-website-git-add-animation-v3.carbon-design-system.now.sh/animation/classic-principles/

**Autoplay**
For whatever reason the videos do not autoplay. Is there a property that can be included to invoke the autoplay feature? Incidentally, the pause/play icons are inverted.

**Lottie**
For many of the videos, we've been able to get lottie files. How do we implement lottie files?

The examples portion of this page is working as intended where the smaller and shorter files are automatically looping and the longer form videos have the blue play button. https://design-language-website-git-add-animation-v3.carbon-design-system.now.sh/animation/tips-and-techniques/#examples

Similar to the Classic Principles page, the do/don't examples should autoplay here as well.

**Lazy load**
Does it make sense to load this content as you scroll similar to https://www.ibm.com/design/

These issues are fairly high priority to resolve so we can get these pages live sooner than later.

FYI @mjabbink

**Comment by mjabbink** [comment]
Issue moved to [carbon-design-system/gatsby-theme-carbon #872](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/872) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jnm2377** [comment]
@sadekbazaraa what does your code for the GifPlayer look like?

**Comment by jnm2377** [comment]
Are you passing in the images like this?
```mdx
<GifPlayer>
![IBM Cloud Pictograms](/images/IBM_Cloud_Pictograms.gif) // must be gif
![IBM Cloud Pictograms](/images/IBM_Cloud_Pictograms.png) // must be static image
</GifPlayer>
```

Note: the static img has to be the second child.

**Comment by sadekbazaraa** [comment]
@jnm2377 my code currently looks like this

![Screen Shot 2020-06-04 at 2 46 00 PM](https://user-images.githubusercontent.com/33162280/83798413-3d1cc680-a672-11ea-99b6-c9b9a0fd1d3d.png)

**Comment by jnm2377** [comment]
@sadekbazaraa a few things:

- `DoDontExample` is deprecated. It has incorrect spacing. We introduced [`DoDontRow` and `DoDont`](https://gatsby-theme-carbon.now.sh/components/DoDontRow) a while back to replace it. 
- The gif player isn't starting automatically bc you have the png as the first child. The first child needs to be the animated image or video. Then the png after it.
    - I tested it in my dev env on the gatsby theme and it should work fine with a video, but one thing to note, is that the GifPlayer doesn't add aspect ratio to the images or video. So you'll notice that the video doesn't encompass the whole DoDont like the image does bc they're different ratios. I would recommend turning the animation into a gif instead of a video for this reason, but either way a video should work. I didn't however test it with an `.mp4` file. I used our `Video` component.

     ![gifplayer](https://user-images.githubusercontent.com/32556167/83800617-50796300-a66d-11ea-9f70-550b8cde5029.gif)

 - As far as autoplaying the video, that's not something the GifPlayer does. The GifPlayer just handles toggling the images. Autoplaying the video would need to be done in the video itself or the `Video` component.
- This is the code I used for the example
```mdx
<DoDontRow>

  <DoDont type="dont" aspectRatio="1:1">

<GifPlayer>

<Video title="Carbon homepage video" vimeoId="322021187" />

![IBM Cloud Pictograms](/images/IBM_Cloud_Pictograms.png)

</GifPlayer>

  </DoDont>
  
</DoDontRow>
```

**Comment by jnm2377** [comment]
Hope that helps! Feel free to ping me if you need more clarification.

**Comment by sadekbazaraa** [comment]
Thanks @jnm2377! Simply switching the order of static and video assets gave the intended behavior but everything is using DoDontRow which seems to be working fine.

**Comment by sadekbazaraa** [comment]
@jnm2377 now to make it more complex... how would we include a Lottie file in the same scenario? For example, I have lottie files for everything on the Classic Principles page.

**Comment by sadekbazaraa** [comment]
@jnm2377 I was able to get everything working in Safari as intended but apparently the Gifplayer doesn't handle .mp4s in Chrome. 

You can compare this page between the two browsers to see.
https://design-language-website-git-add-animation-v3.carbon-design-system.now.sh/animation/tips-and-techniques/

Here is the code for the top row of images under Examples.

![Screen Shot 2020-06-08 at 10 26 54 AM](https://user-images.githubusercontent.com/33162280/84042417-08ab5200-a973-11ea-8652-5269fdfc8f2e.png)

**Comment by jnm2377** [comment]
@sadekbazaraa yeah, I used the `Video` component in my example. Is there a reason you're not using the Video component? https://gatsby-theme-carbon.now.sh/components/Video

**Comment by vpicone** [comment]
@sadekbazaraa yeah GifPlayer, as the name would suggest is for gifs! Try using the video player.

**Comment by sadekbazaraa** [comment]
@vpicone @jnm2377 I'm going to try the video player again to see if that works as intended.

Still need some info on lazy loading and how to integrate lottie files.

**Comment by vpicone** [comment]
@sadekbazaraa going to close this one since the video+lottie situation is resolved.

re: lazy loading We'd might want to implement that fade up effect across the board rather than just a single page/component type? The fact that we use video, images, and lottie makes it a bit trickier, but we could do it on here to test.

We'd need a spec for which components and which content would have this effect. If you want to open a seperate issue with that info we can give it a go.
