### ISSUE TITLE
[IDL]: Philosophy > Principles Spacing above bullet list is too big

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#577]
https://www.ibm.com/design/language/philosophy/principles#carefully-considered

——————
<img width="1095" alt="Screen Shot 2020-06-17 at 5 49 31 PM" src="https://user-images.githubusercontent.com/32881239/84959370-ce555980-b0c4-11ea-9ddf-d35124dd42e1.png">

@sadekbazaraa or @peter-garvin can one of you masters provide spacing spec here. Seems like just full return within the text field or use 24-32px?

**Comment by sadekbazaraa** [comment]
@mjabbink I'll have a look and see what I can determine. In general, I've been using 24px below the rule and 48px above the next rule for this pattern in my sketch files. I'll check some of the implementation in other places and see what's happening in the code.

**Comment by sadekbazaraa** [comment]
@mjabbink I figured it out. If this is good to go, I'll ask the AUX squad to merge.
https://design-language-website-git-sadekbazaraa-patch-4.carbon-design-system.vercel.app/philosophy/principles

**Comment by mjabbink** [comment]
thanks @sadekbazaraa that is good to go and much better. This change will also effect other sites like BC, Watson, Cloud XGs

**Comment by mjabbink** [comment]
@sadekbazaraa @vpicone Closing this since it looks merged already?

**Comment by sadekbazaraa** [comment]
@mjabbink yup, it's already live
