### ISSUE TITLE
[Plex site]: Plexness > fix typo in caption. 1960 should be 1961.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#584]
https://www.ibm.com/plex/plexness/

The year should be 1961

![Screen Shot 2020-06-23 at 3.10.58 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/b080b2b0-090c-4006-b0b2-7dcfec733a73)

**Comment by vpicone** [comment]
Closed by https://github.ibm.com/brand/plex/pull/66
