### ISSUE TITLE
[Animation] Image and video spacing errors — mobile only

### ISSUE THREAD

**Issue by sadekbazaraa** [carbon-design-system/design-language-website#597]
There are a number of spacing errors appearing on mobile vs. desktop. In mobile, some of the videos and captions are losing the spacing. The spacing appears fine in my local build but once it hits staging, the errors appear.

https://design-language-website-git-add-animation-v3.carbon-design-system.vercel.app/animation/classic-principles/

Any thoughts @jnm2377 ?
FYI @mjabbink 

Local build on left, staging link on right in the screenshots below (Safari).

**Classic principles**

![Screen Shot 2020-07-06 at 12 13 30 PM](https://user-images.githubusercontent.com/33162280/86615736-dea17b80-bf82-11ea-990a-e166667b972e.png)

**Tips and techniques**

![Screen Shot 2020-07-06 at 12 11 16 PM](https://user-images.githubusercontent.com/33162280/86615778-eeb95b00-bf82-11ea-8d0b-269a565bd492.png)

![Screen Shot 2020-07-06 at 12 12 04 PM](https://user-images.githubusercontent.com/33162280/86615832-01339480-bf83-11ea-94a4-740c6bb4bd10.png)

**Comment by vpicone** [comment]
This will be fixed by https://github.com/carbon-design-system/gatsby-theme-carbon/issues/898
