### ISSUE TITLE
[IDL] : New animation/illustrations spacing issues

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#600]
- [ ]  Some images in mobile need space between them. They are currently touching when stacked. 

- [ ] Some captions need spacing adjustments

here: 
https://www.ibm.com/design/language/animation/classic-principles/
https://www.ibm.com/design/language/animation/tips-and-techniques/

![Screen Shot 2020-07-07 at 3.24.51 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/4fc622bb-48cc-4aee-95ae-fe9c0344c466)

![Screen Shot 2020-07-07 at 3.25.25 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/8b3d2bdb-17a5-4687-b063-1d4ad2ed80c4)

![Screen Shot 2020-07-07 at 3.25.06 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/1f026913-2b59-4440-9c7c-f04a77d15007)

![Screen Shot 2020-07-07 at 3.23.48 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/d2616bbc-cfb5-49d9-a2c8-99343bcd6174)

**Comment by vpicone** [comment]
This will be fixed here: https://github.com/carbon-design-system/gatsby-theme-carbon/pull/899

**Comment by mjabbink** [comment]
In mobile /chrome movies are broken

![410F1657-E8AD-4AF7-96E1-7E1CF6A359C2](https://user-images.githubusercontent.com/32881239/86871601-3255b700-c0a0-11ea-9fdc-beaacc9d7a22.png)

**Comment by vpicone** [comment]
@mjabbink negative, that's different. Mobile browsers are very cautious about auto-playing video to preserve battery.

**Comment by mjabbink** [comment]
Not sure what you’re saying? It’s not working when it should. Is it a browser setting thing?

**Comment by mjabbink** [comment]
Works great here https://www.ibm.com/design/language/animation/classic-principles/

But not here https://www.ibm.com/design/language/illustration/line-style/usage

**Comment by mjabbink** [comment]
This may be low in terms of effecting usability but it’s not an acceptable state of design. This makes it a high priority because we cannot have these issues for long.

**Comment by mjabbink** [comment]
@vpicone This is the highest of all priorities for IDL/brand issues for this coming week. I realize mobile is not a huge user base but nonetheless these issues cannot go on too long. It was marked low but it’s the opposite.

**Comment by vpicone** [comment]
@mjabbink the impact tags are just used to mark the number of users impacted by the issue

High Impact = every user is impacted (site down), 
Medium Impact = many users (Icon library broken on all devices),
Low Impact = a few users (_some_ components _some_ pages wrap weird on _mobile_)

Like I mentioned a few days ago and in our brand prio meeting: we're working on solving it the right way, shipping a quick hack or anything less than design excellence isn't an option.

**Comment by mjabbink** [comment]
Was not sure if the focus was clear and it’s not clear if low impact determines priorities so just clarifying. Design excellence and no hacks goes without saying.

**Comment by mjabbink** [comment]
Do nots have double spacing now and in illustration (usage tabs) the animations do not auto play and in chrome getting broken video icon

**Comment by mjabbink** [comment]
![3B35FA5A-BAEE-454D-B1EA-16A996BB8D5C](https://user-images.githubusercontent.com/32881239/87258200-68f84c80-c467-11ea-9e0c-f7b8d7041a55.jpeg)

**Comment by vpicone** [comment]
@mjabbink trying to suss our what’s a new issue and what’s not. The auto play chrome stuff has been broken for some time (we still don’t have an issue for this I think) the double space thing is new and unique to IDL?

**Comment by mjabbink** [comment]
The issue is in this issue. You want me to make a separate issue?

**Comment by vpicone** [comment]
@mjabbink this issue is for the spacing thing right? Their unrelated so a separate issue would be ideal.

**Comment by mjabbink** [comment]
Made a separate issue was  meant to capture “multiple issues”

**Comment by vpicone** [comment]
Spacing issues have been resolved w/ latest theme release

**Comment by mjabbink** [comment]
Spacing is now inconsistent across many pages. Looks like we not to go over every page again to correct. @vpicone @sadekbazaraa @peter-garvin

**Comment by mjabbink** [comment]
i.e. the spacing between the black images in mobile: https://www.ibm.com/design/language/typography/typeface

**Comment by mjabbink** [comment]
@sadekbazaraa ill make a separate issue but the 32px now causes the space between stacked images with captions to be too large: https://www.ibm.com/design/language/animation/tips-and-techniques/#camera

Versus with 24px it looked like this:
https://www.ibm.com/brand/architecture/#outside-in

I’ll make a new issue to explore all of this again with a page by page audit.

**Comment by mjabbink** [comment]
@sadekbazaraa ill make a separate issue but the 32px now causes the space between stacked images with captions to be too large: https://www.ibm.com/design/language/animation/tips-and-techniques/#camera

Versus with 24px it looked like this: https://www.ibm.com/brand/architecture#outside-in

**Comment by mjabbink** [comment]
@vpicone still related to this issue. These are Using different spacing than Do Nots. https://www.ibm.com/design/language/animation/tips-and-techniques/#complexity

These should be the same spacing treatment

**Comment by mjabbink** [comment]
@vpicone this section also has both 23px and 32px. Also this same issue. 
https://www.ibm.com/design/language/animation/tips-and-techniques/#examples

**Comment by vpicone** [comment]
@mjabbink those are design language issues, I have open PRs for them. Do you have any spacing issues that are present in the theme right now at gatsby-theme-carbon.now.sh?

**Comment by vpicone** [comment]
@mjabbink you already opened #613 for those issues, no need to re-open this one. I have a PR to address #613 here https://github.com/carbon-design-system/design-language-website/pull/623
