### ISSUE TITLE
Correct Apostrophe fixes

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#601]
They can be found in the sections below. https://www.ibm.com/design/language/illustration/line-style/usage#design-first-performance

https://www.ibm.com/design/language/illustration/line-style/design#rounded-corners-and-nesting

https://www.ibm.com/design/language/illustration/line-style/design#circular-curves

https://www.ibm.com/design/language/illustration/line-style/usage#gradients

**Comment by mjabbink** [comment]
![IMG_6228](https://user-images.githubusercontent.com/32881239/86840265-2817c680-c068-11ea-8ef0-aaf823841ff0.png)

**Comment by mjabbink** [comment]
![IMG_6227.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/ac34e798-d1e3-4831-bf9d-903094ff6511)

**Comment by sadekbazaraa** [comment]
@mjabbink Fixed these with this PR.
https://github.com/carbon-design-system/design-language-website/pull/602
