### ISSUE TITLE
Remove space between color groups

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#608]
https://www.ibm.com/design/language/color#specifications. Color should be butting up together in this particular case.

![Screen Shot 2020-07-09 at 6.18.11 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/df68a7e9-fcc6-4395-9ea7-31b972a546fd)

@sadekbazaraa

**Comment by sadekbazaraa** [comment]
@mjabbink would you want to at least keep 1px in between the groups vertically to match the horizontally adjacent groups? And would you still keep the gray family together on its own row or would you run it all together as one continuum? There's something nice and digestible to me about the strips in that regard, but I fully see how it could all run together as well and appear more like one large image by removing the vertical spacing.

**Comment by mjabbink** [comment]
@sadekbazaraa is that what it used to be? What that was worked. I cannot remember what we did there.

**Comment by sadekbazaraa** [comment]
@mjabbink you're screen shot above is the way it's always been. 16 px between the rows on desktop which turns into 16px between each group on mobile. Here's a screenshot from the original sketch file.

![Screen Shot 2020-07-14 at 10 47 28 AM](https://user-images.githubusercontent.com/33162280/87440130-9bb55880-c5bf-11ea-9154-418047fa2868.png)

**Comment by mjabbink** [comment]
@sadekbazaraa really? I always thought the 1px line since those are not groups but rather it’s all one continuous palette. I feel like the space is not needed. What do you think?

**Comment by sadekbazaraa** [comment]
@mjabbink yeah, it's always been there to help with legibility by giving some separation so it doesn't feel like one giant scrolling image. I agree that it's not necessary in this case but I think I prefer the breathing room, especially in mobile. And of course they aren't meant to denote families, but I do kind of like that you end up with the warm family, the cool family, the gray family and then there's green which is stuck on it's own with the layout, so it sort of works out in a meaningful way. Totally your call though if you think we should change it : )

**Comment by mjabbink** [comment]
But on the top of color page images touch both in desktop and mobile.

These not have 32 spacing in mobile and should touch in mobile too.

<img width="371" alt="Screen Shot 2020-07-16 at 8 20 03 PM" src="https://user-images.githubusercontent.com/32881239/87738214-7af92880-c7a2-11ea-8664-4e0339f9c261.png">

**Comment by mjabbink** [comment]
<img width="1529" alt="Screen Shot 2020-07-16 at 8 19 49 PM" src="https://user-images.githubusercontent.com/32881239/87738236-82b8cd00-c7a2-11ea-9d9e-0c824bf9bb6f.png">

**Comment by vpicone** [comment]
@mjabbink the spacing in the swatch palletes is unrelated to any of the spacing changes recently. It's always been hard coded 32px of space below each pallete.
