### ISSUE TITLE
Spacing issues

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#613]
Horizontal spacing between image galleries should be 32px. 

Illustration:
https://www.ibm.com/design/language/illustration/line-style/design/#examples

https://www.ibm.com/design/language/illustration/flat-style/usage

https://www.ibm.com/design/language/illustration/flat-style/usage#examples-in-use

Animation:
https://www.ibm.com/design/language/animation/tips-and-techniques/#examples

![Screen Shot 2020-07-13 at 12.51.35 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/3010c508-1a7b-4eaa-bcbc-20fdd0e5b112)

![Screen Shot 2020-07-13 at 12.51.41 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/cca05f50-15db-4246-879d-83f5428ccfa0)

...
It’s correct here:
https://www.ibm.com/design/language/2x-grid

**Comment by mjabbink** [comment]
@sadekbazaraa

**Comment by mjabbink** [comment]
happening in Brand Center as well. The horizontal space should be 32 or 64px
https://www.ibm.com/brand/systems/#additional-systems

<img width="1102" alt="Screen Shot 2020-07-13 at 5 16 54 PM" src="https://user-images.githubusercontent.com/32881239/87365129-0ec8bb80-c53b-11ea-848e-8164cb447feb.png">

**Comment by sadekbazaraa** [comment]
@mjabbink we need some dev support, I see all these places that aren't quite 32px, looks like 24px in a lot of places. No idea what's causing that fluctuation across the various pages. 🤷🏻‍♂️

**Comment by vpicone** [comment]
Article cards stacked up

**Comment by vpicone** [comment]
for reference: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/911

**Comment by mjabbink** [comment]
here”s another area where it’s defaulting to 24px when it should be 32px
https://ibmbrandpublisher-stage.mybluemix.net/brand/templates/presentations

**Comment by vpicone** [comment]
@mjabbink I opened a PR updating the default theme spacing from 24px to 32px if you want to see what its like: https://github.com/carbon-design-system/gatsby-theme-carbon/pull/914

**Comment by mjabbink** [comment]
The spacing is not always 32px in certain places. Here for example all these images butt up against each other in desktop and should in mobile. Now they have 32px in mobile.

desktop is correct and touching each other:
<img width="1529" alt="Screen Shot 2020-07-16 at 8 19 49 PM" src="https://user-images.githubusercontent.com/32881239/87737919-d1b23280-c7a1-11ea-846a-17b41dfc255d.png">
.
.
.
Mobile now has 32px spacing but should touch:

<img width="371" alt="Screen Shot 2020-07-16 at 8 20 03 PM" src="https://user-images.githubusercontent.com/32881239/87737949-e5f62f80-c7a1-11ea-9a80-8d75cc1a1d44.png">

**Comment by mjabbink** [comment]
@sadekbazaraa
