### ISSUE TITLE
[IDL] Animation > Tips and techniques: Animations missing

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#635]
Now not working in Desktop and new issues as this all worked a few days ago.

Missing animations:

https://www.ibm.com/design/language/animation/tips-and-techniques/#examples

https://www.ibm.com/design/language/animation/tips-and-techniques/#rhythm

https://www.ibm.com/design/language/animation/tips-and-techniques/#volume

https://www.ibm.com/design/language/animation/tips-and-techniques/#sequential

https://www.ibm.com/design/language/animation/tips-and-techniques/#simple-loops

**Comment by mjabbink** [comment]
This the absolute priority again.

**Comment by mjabbink** [comment]
Seems resolved now but maybe the new small gif player can be used to replace the large blue player button on the large animation

**Comment by vpicone** [comment]
Merged a fix for #652, closing this one as well

**Comment by mjabbink** [comment]
Image still missing or large gap. https://www.ibm.com/design/language/animation/tips-and-techniques/#examples

![602265D5-835B-4643-A1E1-3A39592168F9](https://user-images.githubusercontent.com/32881239/88359043-d98c4c80-cd36-11ea-90b3-3c1e261db9a2.png)
