### ISSUE TITLE
[IDL]: Illustration > all tabbed “Usage” pages are missing images

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#637]
Every Usage page for the three styles has missing and non playing images

https://www.ibm.com/design/language/illustration/line-style/usage

https://www.ibm.com/design/language/illustration/flat-style/usage

https://www.ibm.com/design/language/illustration/isometric-style/usage

**Comment by mjabbink** [comment]
@vpicone 
Only one missing now is the main video with blue play button.
https://www.ibm.com/design/language/illustration/line-style/usage/#animation

**Comment by mjabbink** [comment]
https://www.ibm.com/design/language/illustration/flat-style/usage#animation

and

https://www.ibm.com/design/language/illustration/isometric-style/usage#animation

**Comment by vpicone** [comment]
@mjabbink our publish script got stuck, should be good to go now.

**Comment by vpicone** [comment]
Investigating the three main videos on mobile.
