### ISSUE TITLE
[IDL]: Spacing should be 32px between images

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#638]
spacing not 32px in between certain rows.

https://www.ibm.com/design/language/illustration/isometric-style/design/#examples

https://www.ibm.com/design/language/illustration/isometric-style/design/#circular-curves

https://www.ibm.com/design/language/illustration/isometric-style/design/#organic-curves

https://www.ibm.com/design/language/illustration/isometric-style/design/#rounded-corners-and-nesting

https://www.ibm.com/design/language/illustration/isometric-style/design/#light-source

https://www.ibm.com/design/language/illustration/isometric-style/design/#shadow-types

————

https://www.ibm.com/design/language/illustration/flat-style/design#examples

https://www.ibm.com/design/language/illustration/flat-style/design#rounded-corners-and-nesting

————

https://www.ibm.com/design/language/illustration/isometric-style/design#examples

https://www.ibm.com/design/language/illustration/isometric-style/design#circular-curves

https://www.ibm.com/design/language/illustration/isometric-style/design#organic-curves

https://www.ibm.com/design/language/illustration/isometric-style/design#rounded-corners-and-nesting

https://www.ibm.com/design/language/illustration/isometric-style/design#light-source

https://www.ibm.com/design/language/illustration/isometric-style/design#shadow-types

@peter-garvin

**Comment by mjabbink** [comment]
@vpicone connected to the other spacing issues regarding the 32px between cards and images

**Comment by mjabbink** [comment]
and maybe this is resolved already but not merged?

**Comment by vpicone** [comment]
@mjabbink The spacing stuff has been merged, so these would need to be overriden. The recent 32px movement has created a ton of edge cases since our default on these components has been 24px for 8 months.

**Comment by mjabbink** [comment]
Need to discuss with @jeanservaas and @sadekbazaraa

**Comment by vpicone** [comment]
This looks to be resolved, 32px horizontal and vertical gutters for these images on desktop and mobile.
