### ISSUE TITLE
[IDL]: Remove broken Mini-cards and replace with links in body copy paragraph

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#651]
@dana-paslaru Remove Mini-cards and explore two design options for this page: https://www.ibm.com/design/language/data-visualization/design/basics

1. Just use the side caption text link with launch out icon with maybe rule above text. Something like here: https://www.ibm.com/design/language/philosophy/pov

2. Place the “Learn more on Carbon > ” as a text link in the paragraph of text.

3. Maybe try new mini card spec under text — above the Do Not cards OR maybe it’s. better under the Do Nots cards? I don’t think this will work well but worth a try to know the results.

New MiniCard
https://gatsby-theme-carbon.now.sh/components/MiniCard

**Comment by DanaPaslaru** [comment]
@mjabbink Hi, I've done a first round of explorations for these, please let me know what you think about it. Thanks!

1. with side caption + launch out icon:

<img width="650" alt="with side caption" src="https://user-images.githubusercontent.com/64195956/88660858-30e83f00-d0e0-11ea-9994-1d0d833d2d5c.png">



2. with "Learn more on Carbon" as text link:

a. in the paragraph:

<img width="686" alt="with text link after paragraph" src="https://user-images.githubusercontent.com/64195956/88661028-802e6f80-d0e0-11ea-80a2-6888a8b090c4.png">


and 
b. after Do's and Don'ts cards:

<img width="650" alt="with text link" src="https://user-images.githubusercontent.com/64195956/88661107-a6eca600-d0e0-11ea-80f8-095e30d92656.png">



3. with new mini card:

a. on 4 columns, under the Do Nots cards:

<img width="719" alt="with mini card on 4 columns" src="https://user-images.githubusercontent.com/64195956/88661362-0f3b8780-d0e1-11ea-8648-f4a50c2a1114.png">

and 
b. on 5 columns, under the Do Nots cards:

<img width="694" alt="with mini card on 5 columns" src="https://user-images.githubusercontent.com/64195956/88661416-25494800-d0e1-11ea-977a-ceeec4dd01de.png">

**Comment by mjabbink** [comment]
I think inline links can be text color which will help.

**Comment by DanaPaslaru** [comment]
> I think inline links can be text color which will help.

Hi, then something like this?

<img width="926" alt="image" src="https://user-images.githubusercontent.com/64195956/88682482-62223880-d0fb-11ea-9d7f-f508fb2598b8.png">

Thanks!

**Comment by DanaPaslaru** [comment]
> I think inline links can be text color which will help.

@mjabbink Hi, I did a little research and it seems that markdown doesn't support color, but I'll try to add a class to this inline element, so we can define a color for it. Thanks!

**Comment by mjabbink** [comment]
let’s go for version “a”

**Comment by DanaPaslaru** [comment]
@mjabbink Hi, here are the two preview urls for this issue, for Data Vis Overview page and Data Vis Design Basics page:

https://design-language-website-git-fork-danapaslaru-patch-3.carbon-design-system.vercel.app/data-visualization/design/basics/

https://design-language-website-git-fork-danapaslaru-patch-2.carbon-design-system.vercel.app/data-visualization/overview

Please let me know if all is ok with you, so we can move forward with it. Thanks!

**Comment by vpicone** [comment]
@mjabbink what am I lookin at here?

**Comment by mjabbink** [comment]
The removal of the broken (old) mini cards.

**Comment by mjabbink** [comment]
The preview links look correct so seems good to go.

**Comment by vpicone** [comment]
When @DanaPaslaru changes her PR from draft to ready for review, we'll be pinged automatically to look at it.

**Comment by mjabbink** [comment]
Looks done
