### ISSUE TITLE
[IDL]: Animation > Lead animation poster image needs to be higher resolution 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#656]
https://www.ibm.com/design/language/animation/overview

If comparing the poster image on the Animation Overview lead animation it is considerably lower quality than the other poster images here:
https://www.ibm.com/design/language/2x-grid
https://www.ibm.com/design/language/typography/typeface
https://www.ibm.com/design/language/iconography/ui-icons/design
https://www.ibm.com/design/language/motion-ui/basics

@sadekbazaraa

**Comment by sadekbazaraa** [comment]
@mjabbink I uploaded a new high res poster image and it's a bit crisper now. Vimeo applies a touch of compression automatically.

**Comment by mjabbink** [comment]
great. The images look way better so this one must have got twice the compression or something. Not sure. Thanks @sadekbazaraa

**Comment by mjabbink** [comment]
Can I close this issue>

**Comment by sadekbazaraa** [comment]
Yep, all good to close @mjabbink
