### ISSUE TITLE
[mobile]: Animations to not auto play and/or are missing again

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#670]
Same exact issue from last week is back again.

—Chrome mobile shows missing video icon or no image at all.

here:
https://www.ibm.com/design/language/illustration/line-style/usage

https://www.ibm.com/design/language/illustration/flat-style/usage

https://www.ibm.com/design/language/illustration/isometric-style/usage

https://www.ibm.com/design/language/animation/tips-and-techniques/

**Comment by mjabbink** [comment]
Showing these new illustration and animation pages to Phil on Wednesday. He always checks mobile.

**Comment by vpicone** [comment]
@mjabbink try refreshing, all four pages are working on chrome/safari/firefox mobile browsers for me.

![animation](https://user-images.githubusercontent.com/4078018/88663901-e516a500-d0a1-11ea-9c4d-9d7fdefa434a.gif)

**Comment by mjabbink** [comment]
I did reboot chrome several times and did not work. It works now thought even without rebooting. Not sure what was going on last night. All good.
