### ISSUE TITLE
[IDL] Update left nav

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#679]
Update the order of left navigation and insert rules to create distinct clustering. @sadekbazaraa I think we do not need to have that extra space to separate the Sketch kits since we now have the rules in between clusters. Those are just another cluster.

![Screen Shot 2020-07-30 at 11.42.52 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/df007a7e-6c77-4405-8ea3-7abbd5c00c90)

**Comment by vpicone** [comment]
@mjabbink is there no help dropdown anymore?

**Comment by sadekbazaraa** [comment]
@vpicone Mike is out this week. I believe the missing Help menu is totally an oversight. The idea is to move What's New to the top of the group.

It should be:
– What's new
– Resources
– Help

That's a good point about the Resource links. Let's just leave those as they are now to be consistent across all the sites. We can revisit them as a whole to see if we want to make a change across the board.

**Comment by vpicone** [comment]
@sadekbazaraa @aagonzales made a similar issue in the Carbon website, should we look at removing it in the theme?

https://github.com/carbon-design-system/carbon-website/issues/1348

**Comment by mjabbink** [comment]
Good catch. It was 100% oversight and what @sadekbazaraa noted above is correct. 
It should be:
– What's new
– Resources
– Help

**Comment by mjabbink** [comment]
@vpicone This was prioritized but when moved it lost that. I had placed it at the top of the list along with App icons library issue.

**Comment by mjabbink** [comment]
<img width="798" alt="Screen Shot 2020-08-04 at 6 27 30 PM" src="https://user-images.githubusercontent.com/32881239/89358319-416c5c80-d680-11ea-9d51-b1b8c5bd2ccf.png">

**Comment by mjabbink** [comment]
@vpicone This issue is a priority for the next sprint.

**Comment by mjabbink** [comment]
@sstrubberg I forgot to spec the spacing after an opened nav. Should be 24px

**Comment by mjabbink** [comment]
@sadekbazaraa Should,we be adding 24px after the last item in open left nav sections?

i.e.

<img width="705" alt="Screen Shot 2020-08-11 at 11 38 41 AM" src="https://user-images.githubusercontent.com/32881239/89930090-6c4a3980-dbc7-11ea-8e5d-9635f84d53ed.png">

**Comment by mjabbink** [comment]
and also here:


<img width="552" alt="Screen Shot 2020-08-11 at 11 45 45 AM" src="https://user-images.githubusercontent.com/32881239/89930610-41141a00-dbc8-11ea-9bba-91d27b9a1b80.png">

**Comment by mjabbink** [comment]
@sadekbazaraa @vpicone @sstrubberg Sorry gents, I overlooked spec‘ing this situation out. Currently it looks like we do not add any additional space after the last item in an opened state. I can go either way here. One is space efficient and the added space might help a user navigate the content clearly.

**Comment by jeanservaas** [comment]
didn't @aagonzales  also look at this in 
https://github.com/carbon-design-system/carbon-website/issues/1348

I think I might keep the spacing the same regardless

**Comment by mjabbink** [comment]
ok, let’s leave the spacing as is and see what it all looks like once it’s on the glass. We can always create an issue to add that space later.

**Comment by mjabbink** [comment]
so we will carry on with this spacing for now.

![Uploading Screen Shot 2020-08-11 at 1.58.44 PM.png…]()
