### ISSUE TITLE
[IDL pictograms] Usage tab Clearance section showing both desktop and mobile versions of artwork simultaneously

### ISSUE THREAD

**Issue by conradennis** [carbon-design-system/design-language-website#681]
@vpicone @mjabbink On Firefox and Chrome, Usage tab Clearance section is showing both the 16:9 desktop version and 1:1 mobile version of artwork simultaneously. On mobile images are sized incorrectly, possibly due to this issue. Similar issue is happening on Carbon: https://github.com/carbon-design-system/carbon-website/issues/1512

Desktop:
![screencapture-ibm-design-language-iconography-pictograms-usage-2020-08-04-14_00_36](https://user-images.githubusercontent.com/16782944/89328324-3ce17d00-d65b-11ea-855d-371726a4940a.png)

Mobile:

<img width="498" alt="Screen Shot 2020-08-04 at 2 01 45 PM" src="https://user-images.githubusercontent.com/16782944/89328297-2f2bf780-d65b-11ea-8d36-cbececc97d3b.png">
<img width="497" alt="Screen Shot 2020-08-04 at 2 01 50 PM" src="https://user-images.githubusercontent.com/16782944/89328298-2fc48e00-d65b-11ea-87f4-b622f70a8c9d.png">
<img width="500" alt="Screen Shot 2020-08-04 at 2 01 56 PM" src="https://user-images.githubusercontent.com/16782944/89328299-2fc48e00-d65b-11ea-9258-4ec2ca6231bf.png">

**Comment by mjabbink** [comment]
@conradennis Can you tackle this in markdown or do we need Aux squad?

**Comment by vpicone** [comment]
@mjabbink already tackled this
