### ISSUE TITLE
[IDL]: Create color palette image for mobile and update

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#687]
https://www.ibm.com/design/language/ibm-logos/8-bar/#color

In mobile the color palette image should be like below (6 swatches across):

<img width="363" alt="Screen Shot 2020-08-11 at 1 54 00 PM" src="https://user-images.githubusercontent.com/32881239/89942632-25b20a80-dbda-11ea-820f-11dd40ede99c.png">

**Comment by mjabbink** [comment]
@DianaStanciulescu Can you update to include a mobile image. If you can tackle in markdown please proceed.

**Comment by DianaStanciulescu** [comment]
I started a PR but I keep getting weird behaviours. I would like to get it to work myself, so I hope this can wait a week. 

The link is here if not: https://github.com/carbon-design-system/design-language-website/pull/688

**Comment by mjabbink** [comment]
the preview link not letting me get to the logo page.

**Comment by DianaStanciulescu** [comment]
@mjabbink preview link ready to be reviewed for both 8-bar and rebus: https://design-language-website-git-dianastanciulescu-patch-2.carbon-design-system.vercel.app/
