### ISSUE TITLE
Add link to isometric starter kit

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/design-language-website#703]
When it's ready, we need to be sure the link gets added and the coming soon note removed here: https://www.ibm.com/design/language/illustration/isometric-style/production#automated-object-transformations

**Comment by vpicone** [comment]
@sadekbazaraa I feel like this has been a few days away for a month now. Should we just remove the tutorial based around this kit?

**Comment by sadekbazaraa** [comment]
@vpicone @DianaStanciulescu has created a new issue for this. We are working on the finishing touches to the kit and have added some copy and updated the Resource cards a bit. I think we can likely close this issue now that there is a new and more complete one.
