### ISSUE TITLE
Color: Add spacing between images and play/pause button causing image to disappear

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#710]
https://www.ibm.com/design/language/color/#gradients

@sadekbazaraa

**Comment by sadekbazaraa** [comment]
@mjabbink Whoa, weird. I see two of the same images, one static, one with the play/pause button. The image should span 12 columns, not 8. 

![Screen Shot 2020-08-27 at 7 25 23 PM](https://user-images.githubusercontent.com/33162280/91504507-590fbd00-e89b-11ea-9f0c-598503baf7a2.png)

**Comment by mjabbink** [comment]
Also looks like the images is repeating?
