### ISSUE TITLE
Make link with Carbon more apparent. 

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/design-language-website#714]
The intrinsic link between IDL and Carbon should be apparent and obvious to users of either site. We want to make sure the relationship is clear.

**Comment by jnm2377** [comment]
@vpicone what do you mean exactly? Like the actual link in the Switcher between those two? Or just the visual feel of it should make it apparent that the sites are related... bc I thought that was obvious...

**Comment by vpicone** [comment]
@jnm2377 more just a general content thing. This was brought up in one of our team meetings but got set aside. I think I'll close it for now.
