### ISSUE TITLE
IDL Homepage cards should NOT link to new tab.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#726]
Not sure how or when this happened but the cards on the homepage are now linking out to new tab. Only the Carbon one used to  do that now they all seem to link out to a new tab. We need to undo this ASAP.

@KSandeep5 

FYI @sadekbazaraa @kennethhartmann

**Comment by mjabbink** [comment]
This was in the op slot and somehow got moved way down the brand column. This should get addressed as a priority.

**Comment by sadekbazaraa** [comment]
Noted @mjabbink not sure who moved it but I see it's back up top now.

Also, I've confirmed with the dotcom team that the general best practice they use is that pages within the same site open in the same tab and external pages open in a new tab. I think this is the practice we should be using across the board including all of our Gatsby sites.
