### ISSUE TITLE
Outdated link to Visual Design page

### ISSUE THREAD

**Issue by LMapes** [carbon-design-system/design-language-website#734]
## Detailed description

> I believe and Ken Hartmann confirmed that the 'Visual' entry found in the second column of this SERP result should be removed. 

> This was discoved in a search for IBM Design Language in Firefox.

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes
<img width="1440" alt="Screen Shot 2020-09-22 at 2 32 07 PM" src="https://user-images.githubusercontent.com/56092796/93930275-b94f1e80-fce2-11ea-8802-0211c9e123e3.png">

**Comment by vpicone** [comment]
Unfortunately, this is controlled by Google, there's no way for us to customize it. We would need to shut down the old v1 site.
