### ISSUE TITLE
Scrolling Iconography > UI icons and > Pictograms goes to black

### ISSUE THREAD

**Issue by LMapes** [carbon-design-system/design-language-website#746]
## Detailed description

> Open IDL, navigate to Iconography > UI icons. Library appears. Screen goes to black when I scroll down. Pictograms goes straight to black. No issue with App icons.

> Not site wide. Only these two iconography pages. Also, cannot navigate using back button on browser window from the black screens. Behavior the same in private window.

> Firefox 81.0
![Screen Shot 2020-09-24 at 3 44 32 PM](https://user-images.githubusercontent.com/56092796/94199281-2f3bbd00-fe7e-11ea-87e3-a07e18cf2ffa.png)
![Screen Shot 2020-09-24 at 3 36 14 PM](https://user-images.githubusercontent.com/56092796/94199284-31058080-fe7e-11ea-8a10-c9cbbed8dc5f.png)

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by mjabbink** [comment]
@LMapes Not able to duplicate. Can you conform this is still happening for you? May have been while site was updating?

**Comment by LMapes** [comment]
@mjabbink appears to be resolved. Not sure of the cause, but all set now.
