### ISSUE TITLE
404 on App icons > Contribute page

### ISSUE THREAD

**Issue by LMapes** [carbon-design-system/design-language-website#749]
## Detailed description

> App icons page shows fourth tab titled 'Contribute':
https://www.ibm.com/design/language/iconography/app-icons/library

Produces a 404 when clicked.

Clicking onto App icons > Design tab, I can see that the fourth tab there is named 'Production' 

This may be the problem. Inconsistent tab names.

> What did you expect to happen? What happened instead? What would you like to see changed?

> FF 81.0
<img width="1250" alt="Screen Shot 2020-09-25 at 1 15 06 PM" src="https://user-images.githubusercontent.com/56092796/94302051-37a10000-ff31-11ea-93a8-b2f7293fb727.png">
<img width="1216" alt="Screen Shot 2020-09-25 at 1 15 17 PM" src="https://user-images.githubusercontent.com/56092796/94302057-396ac380-ff31-11ea-83ea-7291be9d3f2d.png">

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- FYI @kennethhartmann

**Comment by mjabbink** [comment]
I get that message as well but only on occasion. I sometime get the page to load but I have icons missing

<img width="350" alt="Screen Shot 2020-09-26 at 1 53 41 PM" src="https://user-images.githubusercontent.com/32881239/94348270-5b7f4700-0000-11eb-860c-8cff1092ed51.png">
<img width="330" alt="Screen Shot 2020-09-26 at 1 53 54 PM" src="https://user-images.githubusercontent.com/32881239/94348272-5b7f4700-0000-11eb-8be5-acb2081664d8.png">
<img width="338" alt="Screen Shot 2020-09-26 at 1 54 00 PM" src="https://user-images.githubusercontent.com/32881239/94348273-5c17dd80-0000-11eb-850e-cb26f1ade3a6.png">
<img width="1093" alt="Screen Shot 2020-09-26 at 1 55 01 PM" src="https://user-images.githubusercontent.com/32881239/94348274-5c17dd80-0000-11eb-8bcc-52009bd42b01.png">
<img width="1067" alt="Screen Shot 2020-09-26 at 1 55 17 PM" src="https://user-images.githubusercontent.com/32881239/94348275-5c17dd80-0000-11eb-95ee-bbf022e3c3a7.png">

**Comment by mjabbink** [comment]
@LMapes Seems to be resolved. Can you confirm.

**Comment by mjabbink** [comment]
This was probably happening during an update.

**Comment by LMapes** [comment]
@mjabbink all set now.
