### ISSUE TITLE
[app icons library] pixelated icons in some browsers

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#753]
@vpicone I'm seeing a weird problem with SVGs that im not sure what to make of, wondering if you or someone on the team has any ideas. Looking at app icons library on mobile, all the stroke ones are pixelated (just the color mask, not the white bits). I'm noticing this happens on both safari and chrome in mobile, as well as safari desktop. But they look fine in desktop chrome and firefox. havent tested in other browsers 

Even more weird is that ive tested these SVG codes in different browsers and on mobile and they're all sharp: https://codepen.io/petergarvin/pen/dyojpbB

Chrome mobile:
![IMG_7124](https://user-images.githubusercontent.com/47458576/94348970-2e359780-0006-11eb-9952-5f58fd9cac8f.PNG)

Safari mobile:
![IMG_7125](https://user-images.githubusercontent.com/47458576/94348976-3c83b380-0006-11eb-8e70-86d3a3c623d4.PNG)

Safari desktop:
<img width="1436" alt="Screen Shot 2020-09-26 at 2 31 47 PM" src="https://user-images.githubusercontent.com/47458576/94348982-4a393900-0006-11eb-9433-824e28b14737.png">

**Comment by peter-garvin** [comment]
When I save the SVG images, the files appear fine. I downloaded this one and dropped it in codepen and it works across all browsers ive tried
<img width="1166" alt="Screen Shot 2020-09-26 at 2 44 47 PM" src="https://user-images.githubusercontent.com/47458576/94349089-ec592100-0006-11eb-8d70-d614827331f1.png">
https://codepen.io/petergarvin/pen/xxVByPJ

**Comment by mjabbink** [comment]
Not able to duplicate in Chrome or Safari. May have been while site was updating?

**Comment by peter-garvin** [comment]
@mjabbink im still seeing it on safari, and on mobile browsers

**Comment by peter-garvin** [comment]
you may have to zoom or look closely to notice

**Comment by mjabbink** [comment]
You’re right I see it too.

**Comment by mjabbink** [comment]
FYI @vpicone

**Comment by vpicone** [comment]
Just a point of order: on iOS every browser uses the safari rendering engine under the hood.

Not sure what’s causing this, exporting them as 2x pngs would solve it but I’ll try and look at other options.

**Comment by peter-garvin** [comment]
I wonder why the SVG code would work in safari but not once on the library page

**Comment by vpicone** [comment]
@peter-garvin it has something to do with constraining the size of it. Were they exported through illustrator to be responsive?

**Comment by peter-garvin** [comment]
yes they are responsive. im noticing safari also bitmap renders the mask SVG code if zoomed waaay in. This wouldnt be an issue to me since it is rendering at the right resolution. but it seems to be worse with it in the img tag:
[icontest.html.zip](https://github.com/carbon-design-system/design-language-website/files/5300497/icontest.html.zip)


<img width="490" alt="Screen Shot 2020-09-29 at 11 27 28 AM" src="https://user-images.githubusercontent.com/47458576/94586389-c621c400-0246-11eb-9d25-9e0e534aa9c8.png">

**Comment by vpicone** [comment]
@peter-garvin yeah, it works fine if you just throw the svg code into the page, but it's hard to go from raw svg files to that. They aren't exported particularly well suited for that either with things like style tags.

**Comment by peter-garvin** [comment]
the style tags is just me hacking it together for a test, I dont believe illustrator exports with style tags

**Comment by vpicone** [comment]
@peter-garvin it can (and should) be set to export in that way. But here's the bee for example: https://github.com/carbon-design-system/design-language-website/blob/master/static/app-icons/dark-theme/Bee.svg

**Comment by peter-garvin** [comment]
ah I thought you were talking about the html test. Theyre all exported with illustrator with these settings. But that shouldnt be the cause of the pixelation right? it seems to me the img tag is making things weird. is there anything you suggest?
<img width="768" alt="Screen Shot 2020-09-30 at 9 31 50 AM" src="https://user-images.githubusercontent.com/47458576/94699314-cd58d880-02ff-11eb-9af9-eb2f06667972.png">

**Comment by mjabbink** [comment]
Seems to be resolved? Looking good to me now.

**Comment by peter-garvin** [comment]
I'm still seeing it pixelated, dont believe anything has changed

cant for the life of me figure out why the SVG looks good in safari until you put it within an img tag

**Comment by vpicone** [comment]
@peter-garvin its some arcane safari bug, I’m stuck as well. My plan is to see if Big Sur fixes it and if not, figure out a rendering strategy that doesn’t rely on img element s
