### ISSUE TITLE
Color: Specifications: Tabs height should be taller

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#756]
https://www.ibm.com/design/language/color#specifications
.
.
.
Current:
![Screen Shot 2020-09-28 at 10.57.37 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/85cd3055-2d41-4186-a60d-63adfccd52ec)

Expected:
![Screen Shot 2020-09-28 at 11.01.06 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/82b21150-1939-4ef8-9546-86efc5bb0b60)

https://www.ibm.com/design/language/typography/typeface#subfamilies

Overlap comparison:
![Screen Shot 2020-09-28 at 11.02.00 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/bab4f142-f075-4ee8-9f42-cc89e8f46266)

**Comment by mjabbink** [comment]
FYI: @sadekbazaraa

**Comment by sadekbazaraa** [comment]
Good 'ol eagle eye @mjabbink! You still got it.
