### ISSUE TITLE
[App icons library] Friendly name updates

### ISSUE THREAD

**Issue by LMapes** [carbon-design-system/design-language-website#758]
## Detailed description

> Update friendly names on IDL > Iconography > App icons > Library page. 
- copy edit/review of app names for legal trademarks
https://ibm.invisionapp.com/d/main#/console/15367904/319719114/comments

- Screenshots or code
- Notes

**Comment by LMapes** [comment]
@DianaStanciulescu all comments in Invision marked with thumbs up are good to go. Still a few outstanding items that might be resolved by your next day online.

**Comment by pbenson322** [comment]
@DianaStanciulescu @LMapes Edits completed on 09.28.20 with the exception of IoT Asset and IoT Business Analytics. Awaiting confirmation on correct naming.

**Comment by LMapes** [comment]
Edited .yml file and created PR here. https://github.com/carbon-design-system/design-language-website/pull/763

**Comment by vpicone** [comment]
@
