### ISSUE TITLE
DL - 404 from DL to Carbon design site - Link 'Carbon libraries'

### ISSUE THREAD

**Issue by rmathur16** [carbon-design-system/design-language-website#762]
**URL:**
All DL pages  - Left nav - Link '[Carbon libraries](https://www.carbondesignsystem.com/resources/#theme-libraries)' goes to 404 page.

**Describe the bug**
All DL pages  - Left nav - Link '[Carbon libraries](https://www.carbondesignsystem.com/resources/#theme-libraries)' goes to 404 page.

At present 'Carbon libraries' link on left nav goes to 
https://www.carbondesignsystem.com/resources/#theme-libraries
which is a 404 page

**To Reproduce**
1. Go to 'https://www.ibm.com/design/language/'
2. Click on 'Carbon libraries' link 
3. See 404 error page

**Expected behavior**
'Carbon libraries' link should point to https://www.carbondesignsystem.com/

**Screenshots**
![Screenshot_2020-09-30 https www carbondesignsystem com](https://user-images.githubusercontent.com/38890232/94707040-f766c680-0310-11eb-85e5-d84e5111f00b.png)

**Comment by rmathur16** [comment]
Hi @kenhartmann just noticed that in All DL pages, on left nav - Link 'Carbon libraries' goes to 404 page.
At present 'Carbon libraries' links to https://www.carbondesignsystem.com/resources/#theme-libraries which is a 404 page

I don’t see any theme libraries page in Carbon unless I’m missing something here.
According to me link’ Carbon libraries’ should just point to https://www.carbondesignsystem.com/

Please confirm. Thank you.
fyi: @sadek @mjabbink @ksandeep

**Comment by mjabbink** [comment]
The Carbon site rework left nav. Kits are now in Designing https://www.carbondesignsystem.com/designing/kits/sketch

**Comment by mjabbink** [comment]
@rmathur16 @sadekbazaraa If this is something one of our designers can take of we should do so. Maybe Diana or Pete can handle correcting the URLs and creating the PR.

**Comment by rmathur16** [comment]
@DianaStanciulescu can you please take look at this one. Thanks.

**Comment by DianaStanciulescu** [comment]
PR: https://github.com/carbon-design-system/design-language-website/pull/774

**Comment by DianaStanciulescu** [comment]
fixed & live, closing issue.
