### ISSUE TITLE
[app icons library] copy change

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#764]
in app icons library, IBM Plex section should be "IBM Plex®" including registered trademark symbol. Not sure how to update it myself since it seems its not in markdown

**Comment by LMapes** [comment]
@peter-garvin The registered trademark IBM Plex® must be followed by a noun. Suggest 'IBM Plex® app icons'

**Comment by vpicone** [comment]
@LMapes then would all of the other sections would need that noun too? Seems like people would see it as a mistake to declare one section app icons and not the others.

**Comment by vpicone** [comment]
This gets back at my issue with the section in the first place the other two categories are art styles, the Plex one should just be “typographic” or something.

**Comment by LMapes** [comment]
I would like to put Stroke style icons, Fill style icons, IBM Plex® style icons

**Comment by LMapes** [comment]
I would like to put Stroke app icons, Fill app icons, and IBM Plex® app icons

Final answer!

**Comment by mjabbink** [comment]
@LMapes @vpicone Personally I think it’s fine as is. In this case adding the literal names seems unnecessary when it says “All app icons” as the default choice. Using Stroke, Fill, IBM Plex seems pretty clear.

As is:

All app icons
Stroke
Fill
IBM Plex


Suggested:

All app icons
Stroke app icons
Fill app icons
IBM Plex app icons


I prefer the as is.

**Comment by LMapes** [comment]
@mjabbink The IBM Plex® typeface takes the registered trademark and must be followed by a noun in order to protect the trademark. It's not a matter of preference. One other alternative is shown below.

All app icons
Stroke style 
Fill style 
IBM Plex® style

**Comment by mjabbink** [comment]
@LMapes There does not need to be a noun after the name IBM Plex with or without the registration mark.

That said I don’t mind the “style” added

**Comment by mjabbink** [comment]
I’ve added an issue to add ® mark in the header for IBM Plex® 
https://github.com/carbon-design-system/design-language-website/issues/809

**Comment by pbenson322** [comment]
@mjabbink Hi Mike. Thought I'd chime in here about adding a noun after IBM Plex® and why Lori is requesting one be added. The IBM legal department not only requires that we follow IBM Plex with a register mark on the first mention in text or in the headline if that's the only mention, but requires us to follow any IBM trademarked product name with a descriptive noun in EVERY MENTION to further protect the brand. This requirement is mentioned on the "Copyright and trademark information" page under "General rules for proper reference to IBM product names" item "3", which reads: "A product name should be used as an adjective qualifying a noun that is a generic description of the product or service." Here's the link to that page: https://www.ibm.com/legal/copytrade Let me know if you have any questions. Thanks. cc: @LMapes

**Comment by mjabbink** [comment]
I’ll repeat you do not need that noun after the name. That description does not apply to this situation.

**Comment by mjabbink** [comment]
And as I said I like the “style” coming after but it has nothing to do with the reasons you state. Based on that description all logotypes and names would have a noun after it which is absolutely not the case. It’s not needed!

**Comment by mjabbink** [comment]
You are reading that recommendation and wanting to apply it where it does not need to be applied. It would be totally fine as IBM Plex®

**Comment by LMapes** [comment]
So, to fix the headlines on this app icons library page, can we agree to go with:

Stroke style
Fill style
IBM Plex® style

**Comment by mjabbink** [comment]
yes.

**Comment by LMapes** [comment]
@vpicone Thank you for your patience. Please make each of the headings on this page:
Stroke style
Fill style
IBM Plex® style
