### ISSUE TITLE
Add more spacing between header and image

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#765]
The header “Illustration” needs more space underneath.

https://www.ibm.com/design/language/animation/overview/

![Screen Shot 2020-09-30 at 3.04.54 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/25001e5f-3f23-40c1-bea0-e4eb3c136143)

**Comment by mjabbink** [comment]
FYI @sadekbazaraa @peter-garvin Maybe Pete you can resolve in markdown?

**Comment by peter-garvin** [comment]
I think this will do it, but lets double check once staging is up

https://github.com/carbon-design-system/design-language-website/pull/766

**Comment by sadekbazaraa** [comment]
Thanks @peter-garvin, looks good on staging. I asked Vince to merge.
