### ISSUE TITLE
Remove sound icon from browser address field [Safari] — there is no sound on the page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#767]
https://www.ibm.com/design/language/animation/tips-and-techniques/

![Screen Shot 2020-09-30 at 7.38.53 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/fdebcfd0-f4e4-4bd5-9462-d582d9c16e14)

**Comment by vpicone** [comment]
@mjabbink Is this still happening? I'm not able to replicate it.

**Comment by vpicone** [comment]
Gonna close this for now since I think it was resolved when we added auto play/mute to the page.

**Comment by mjabbink** [comment]
This still exists.

**Comment by mjabbink** [comment]
see Safari desktop @vpicone

**Comment by sadekbazaraa** [comment]
@mjabbink @vpicone I wonder if this is a Safari browser bug that has been fixed by any chance? My Safari seems to be working as intended. When a video with audio is playing, the icon is there, as soon as I pause the video, the icon goes away. Are you still seeing it

**Comment by sadekbazaraa** [comment]
@mjabbink did you have any luck after updating Safari?

**Comment by mjabbink** [comment]
Sorry, still need to do it.

**Comment by alisonjoseph** [comment]
I'm also unable to replicate. Going to close for now.
