### ISSUE TITLE
[app icon library] Remove unapproved icons

### ISSUE THREAD

**Issue by LMapes** [carbon-design-system/design-language-website#777]
## Detailed description

Remove these unapproved icons from App icons library page. This is a legal issue. 

- Community health coach 
- Community health member
- Project: Speak Play Win
- Doc Buddy
- IBM TouchToken
- IBM Ecosystem Italia
- IBM Maintall
- IBM Study Connect
- IBM Verify Credentials
- IBM Maximo Assist
- IBM Blockchain Trusted Identity
- IBM OpenLabs
- IBM Download Director
- IBM Maas360® admin
- IBM Site Access
- IBM AgroPad
- IBM Call Home Connect Mobile

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by LMapes** [comment]
In addition to removing the app icons named above, please change the IBM Plex header to read:
IBM Plex® app icons

**Comment by LMapes** [comment]
@mjabbink Hi Mike, these app icons are not legally approved for public use and need to be removed from the library. The approvals might be held up by NDAs, or test runs, or other internal reasons. This list has been vetted by Lizet and these should be removed as soon as possible. Can you help expedite? I don't know the rules of working with the AUX squad. Thanks!

**Comment by vpicone** [comment]
@LMapes 
I can't find IBM Study Connect, did you mean IBM Study Advance?

Same with Maximo Assist, did you mean Maximo Voice Assistant?

**Comment by LMapes** [comment]
If you don't find the exact name on the live page, ignore the entry on my list. Thanks Vince!

**Comment by LMapes** [comment]
@vpicone What is on the page as IBM Maximo Augumented Collaboration needs to be removed. It was known as Maximo Assist when it began life. It is not approved for use.

**Comment by vpicone** [comment]
@LMapes What about Study Connect?
