### ISSUE TITLE
[IDL] illustration pages - add kits

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/design-language-website#782]
Add back in the resource cards with direct downloads links to the illustration design kits.

Sketch file: https://ibm.box.com/s/sywkremt3h2qcf342e73fb4og79myk4n
Invision: https://ibm.invisionapp.com/share/VNO0K3MF7RZ

BSXD board corresponding issue: https://github.ibm.com/brand/design-language/issues/190

Starter kits AI files: WIP

**Comment by DianaStanciulescu** [comment]
@LMapes please take a second look at the copy before this can go to dev. thanks!

@sadekbazaraa  FYI

**Comment by LMapes** [comment]
@DianaStanciulescu These look good to me!

**Comment by mjabbink** [comment]
exciting!
