### ISSUE TITLE
[IDL] 2x Grid: Illustrator file under resource card for "2x Grid for video" not downloading

### ISSUE THREAD

**Issue by sadekbazaraa** [carbon-design-system/design-language-website#786]
Download link doesn't seem to work in Safari:
https://www.ibm.com/design/language/2x-grid#2x-grid-for-video

**Comment by sadekbazaraa** [comment]
@vpicone just so I understand more specifically. I made this issue in the carbon/idl repo.. when you say you'll transfer over to IDL, what do you mean? I thought I made in IDL from the onset.

**Comment by vpicone** [comment]
@sadekbazaraa it was originally in the gatsby theme:
<img width="734" alt="Screen Shot 2020-10-12 at 12 14 40 PM" src="https://user-images.githubusercontent.com/4078018/95773665-8adeb680-0c84-11eb-963c-ee6adf001aed.png">

It's no problem really, just wanted to make sure we weren't going down the "just throw everything in the Gatsby theme repo" route (it seems that wasn't the intent).

**Comment by sadekbazaraa** [comment]
@vpicone ah, got it! That was my bad then. It makes sense to be in IDL for sure.
