### ISSUE TITLE
Philosophy > Point of view: Add more space under “Philosophy” video

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#790]
The typography (including caption/aside) are too close to the feature video. @sadekbazaraa can provide the spacing spec for this situation.

https://www.ibm.com/design/language/philosophy/pov

![Screen Shot 2020-10-09 at 10.20.49 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/82b0018b-aa01-4cde-8a1a-3ff8dbef67ed)

**Comment by vpicone** [comment]
Blocked waiting for spec from @sadekbazaraa

**Comment by sadekbazaraa** [comment]
@vpicone it should be a healthier space, more like any of the pages where we have a hero video at the top, 80px above and 80px below. For example, https://www.ibm.com/design/language/2x-grid

![Screen Shot 2020-10-12 at 3 38 18 PM](https://user-images.githubusercontent.com/33162280/95784077-25e58980-0ca1-11eb-8949-c2b9065b2761.png)

**Comment by mjabbink** [comment]
So Sadek are we set at 80px recommendation?

**Comment by sadekbazaraa** [comment]
Yessir @mjabbink 80px it is.
