### ISSUE TITLE
Sass files using rem(*px) where it isn't imported

### ISSUE THREAD

**Issue by raven-wills** [carbon-design-system/design-language-website#795]
![Screen Shot 2020-10-12 at 10 33 39 PM](https://user-images.githubusercontent.com/35464374/95812443-08cdac80-0cdb-11eb-96b1-baff9f39fecb.png)

I think this is happening for all the stylesheets in `src/styles/` as discovered from issue: https://github.com/carbon-design-system/design-language-website/pull/794

**Comment by sjarva** [comment]
I could start working on this! ⌨️ 👩‍💻

**Comment by sjarva** [comment]
Started doing more research on this issue, as the description is not very clear.

I found out that this is not affecting only the components in `src/styles` but also in `src/components` (or at least HomepageVideo component's styles are also affected):

<img width="1104" alt="HomepageVideo component styles affect by ren(px) bug" src="https://user-images.githubusercontent.com/1133238/95891226-776b4280-0d8d-11eb-86bf-d4da9ef45150.png">

Tested with Chrome (83.0.4103.116) and Safari (Version 14.0).

**Comment by sjarva** [comment]
Okay, did more digging 😄 

There isn't a local Sass mixin that is called `rem()` in this project.

The syntax `rem(<pixel value>)` seems to be a feature of (at least) the [`sass-rem` package](https://www.npmjs.com/package/sass-rem), but this package hasn't been included in this project dependencies ever (and therefore hasn't been accidentally removed at some point). The first person to use the `rem()` notation in any `.scss` files has been @alisonjoseph (on May 9th 2019, in a4f0aa7ce1b1294c15817ddc005e76e2cdd9b63d). They've probably used sass-rem in another project and used it here too, and then other people have used the same notation 🤷 

Team/maintainers, how would you like this issue to be fixed?

I see two options here:

1. Find and replace all `rem()` references with an actual `rem` value OR
2. Add the `sass-rem` package as a dependency the this project. The package has zero dependencies (nice), but it would add 8.76 kB in size.
