### ISSUE TITLE
[app icons] App icon incorrectly marked as "unassigned"

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/design-language-website#796]
https://www.ibm.com/design/language/iconography/app-icons/library/

This icon (see the image below - I believe it is named **091** in the library file) is marked as _unassigned_ but it belongs to one of our apps and it should be named:
**IBM Enterprise Video Streaming**

<img width="324" alt="image" src="https://user-images.githubusercontent.com/12408951/95876070-f99a3d80-0d72-11eb-8960-ec15a7f374a9.png">

The icon on the left is our another video app and the icon on the right was just another version of the icon I mentioned above. Could you remove the right one from the list of the available app icons to claim as it would be confusing to end users. 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/12408951/95876285-2ea69000-0d73-11eb-873d-bb1c6be53b7a.png">

**Comment by vpicone** [comment]
@peter-garvin @DianaStanciulescu who's in the go-to for tracking and updating which icons are in use?

**Comment by peter-garvin** [comment]
That'd be me, I can take it out of the master. I thought there was one video streaming app and the other ideas for it were ok to use

@mariuszmickiewicz so we have IBM enterprise video streaming and IBM video streaming?

**Comment by mariuszmickiewicz** [comment]
@peter-garvin 
Yes, there are 
* **[IBM Video Streaming](https://github.ibm.com/brand/App-icons/issues/76)** (circular "record" icon - for broadcasting) app and 
* **IBM Enterprise Video Streaming** (triangle, blue - for watching videos). It used to be [IBM Cloud Video for Enterprise](https://github.ibm.com/brand/App-icons/issues/19) (or Video Portal). 
The latter one needs a name to be assigned to it here in the library.

Regarding the circular/blue icon with play shape inside of it — this was the first concept for the Enterprise Video Streaming (hence very similar pattern to the one with a circle inside), but in the end I decided to go with the big play icon. 

I guess there is not that many video apps at IBM and the circular play icon won't be taken, but it would be a bit undesired result if it did.

Thanks

**Comment by vpicone** [comment]
@mariusmickiewicz So what do we need to do here?

**Comment by mariuszmickiewicz** [comment]
@vpicone 
Please change the name of this icon from **Unassigned** to **IBM Enterprise Video Streaming**

<img width="585" alt="image" src="https://user-images.githubusercontent.com/12408951/102237525-0f53ec80-3ef5-11eb-9607-0906e64503cc.png">

**Comment by mjabbink** [comment]
This needs to be addressed asap. This issue has been open for over 6 months and it’s a name change.

**Comment by mjabbink** [comment]
FYI @alisonjoseph

**Comment by peter-garvin** [comment]
@mjabbink This is already fixed in my PR

**Comment by mjabbink** [comment]
ok thanks @peter-garvin

**Comment by alisonjoseph** [comment]
Is this resolved @peter-garvin

**Comment by peter-garvin** [comment]
Yep!
