### ISSUE TITLE
[app icons] several broken icons

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#799]
@vpicone  looks like some icons got messed up with the conversion
<img width="296" alt="Screen Shot 2020-10-13 at 3 34 29 PM" src="https://user-images.githubusercontent.com/47458576/95917590-1c772280-0d70-11eb-8381-e48f182bdc22.png">
<img width="299" alt="Screen Shot 2020-10-13 at 3 35 21 PM" src="https://user-images.githubusercontent.com/47458576/95917597-1da84f80-0d70-11eb-9fbb-a7f682a9b777.png">
<img width="338" alt="Screen Shot 2020-10-13 at 4 21 24 PM" src="https://user-images.githubusercontent.com/47458576/95917620-29941180-0d70-11eb-9809-cdffa1360ae5.png">

Here is a package of icons exported using the new spec. This also includes icon 132 which was previously PNG and not included, but ive solved the SVG issue that prevented us from using it
[icon fixes.zip](https://github.com/carbon-design-system/design-language-website/files/5374228/icon.fixes.zip)

**Comment by peter-garvin** [comment]
@vpicone moving forward, how can I update icons to the page myself?

**Comment by vpicone** [comment]
Sweet, I'll swap those icons out and try to add some docs on for adding/removing/deprecating going forward. 

Do you have a chunk of metadata for the new icon?

**Comment by vince** [comment]
Gotta block you all. I've mentioned it multiple times but you keep mentioning the wrong Vince. Have a nice day.

**Comment by peter-garvin** [comment]
132 was in the metadata originally but was removed because it was PNG. Do you have that metadata doc? if not I can track it down

**Comment by vpicone** [comment]
@peter-garvin ah that’s right, no I can find it thanks!

**Comment by mjabbink** [comment]
@vpicone Also high priority. This was created Oct 13.

**Comment by vpicone** [comment]
@mjabbink can you clarify what's broken here?

**Comment by peter-garvin** [comment]
Some icons aren't displaying properly. The zip above has re-exported icons to replace

**Comment by mjabbink** [comment]
@vpicone for example the above “IBM Mobile Capture” is missing a line.
