### ISSUE TITLE
Check analytics tags within IDL pages - Big drop in no. of visits

### ISSUE THREAD

**Issue by rmathur16** [carbon-design-system/design-language-website#813]
## Detailed description

> Describe in detail the issue you're having.
There is a big drop in number of visits on IDL pages when compared from last month. 

> What did you expect to happen? What happened instead? What would you like to see changed?
Please check if analytics tags within IDL pages are not accidentally removed. Thanks.

## Additional information

- Attached is the screenshot of 96% drop in Sep when compared to month of Aug.
![IDL-monthly-analytics-report.png](https://images.zenhubusercontent.com/5ae8a3724b5806bc2bd159f8/99b00fb2-91b7-4344-a416-04b7d3aed35f)

@sstrubberg @vpicone 

fyi: @kennethhartmann

**Comment by vpicone** [comment]
@rmathur16 we removed the analytics script so that we could stop remove that awful cookie notification.

We switched to a service that respects users privacy and doesn't require cookie popups. You can view the report here: https://app.usefathom.com/share/hlfjurxw/design-language

**Comment by kennethhartmann** [comment]
Hi @vpicone, 

We may want to move off of our current Analytics plan across all of our sites.
Is Fathom an IBM approved tool?
Also, if IBM approved, who is the account owner paying for costs?

**Comment by vpicone** [comment]
@kennethhartmann I’m not sure about either of those; maybe @mattrosno would know? I know we’re on the hosted plan a d We’re delighted with it. It is open-source, so you could also run it on your own in the IBM cloud.

**Comment by kennethhartmann** [comment]
> @rmathur16 we removed the analytics script so that we could stop remove that awful cookie notification.
> 
> We switched to a service that respects users privacy and doesn't require cookie popups. You can view the report here: https://app.usefathom.com/share/hlfjurxw/design-language

Hi @vpicone 

Is there any code on IBM Design Language that sets cookies on any page? Regardless, we are on ibm.com domain and IBM uses cookies throughout its site so we can’t tell users “hey you have to go to some other page if you change your mind about us using cookies for your visit."

Please revert back to the cookie notification and/or follow the IBM.com footer cookie preferences–thank you! I think the design and digital team have been working on a redesign for several months now so, we should be close to a new design.

We pay for analytics reports so, if changing analytics strategies, we need to align before making a decision. As far as I can see, Fathom is not an IBM approved supplier. If there are any, please remove Fathom scripts from the IBM Design Language site–thank you! 

If we want to use Fathom, I suggest we add it to the Design Toolbox repo and someone take the lead and begin the approval process.

Thank you @vpicone. 

FYI @alisonjoseph @sadekbazaraa @KSandeep5 @rmathur16

**Comment by sadekbazaraa** [comment]
Here's an example of Fathom in use
https://app.usefathom.com/share/hlfjurxw/design-language

@rmathur16 can you please set up a 30 minute meeting with you @kennethhartmann @mjabbink @vpicone and myself to discuss the most suitable analytics approach for our design ecosystem sites.

**Comment by kennethhartmann** [comment]
> > @rmathur16 we removed the analytics script so that we could stop remove that awful cookie notification.
> > We switched to a service that respects users privacy and doesn't require cookie popups. You can view the report here: https://app.usefathom.com/share/hlfjurxw/design-language
> 
> Hi @vpicone
> 
> Is there any code on IBM Design Language that sets cookies on any page? Regardless, we are on ibm.com domain and IBM uses cookies throughout its site so we can’t tell users “hey you have to go to some other page if you change your mind about us using cookies for your visit."
> 
> Please revert back to the cookie notification and/or follow the IBM.com footer cookie preferences–thank you! I think the design and digital team have been working on a redesign for several months now so, we should be close to a new design.
> 
> We pay for analytics reports so, if changing analytics strategies, we need to align before making a decision. As far as I can see, Fathom is not an IBM approved supplier. If there are any, please remove Fathom scripts from the IBM Design Language site–thank you!
> 
> If we want to use Fathom, I suggest we add it to the Design Toolbox repo and someone take the lead and begin the approval process.
> 
> Thank you @vpicone.
> 
> FYI @alisonjoseph @sadekbazaraa @KSandeep5 @rmathur16

**Comment by kennethhartmann** [comment]
> > > @rmathur16 we removed the analytics script so that we could stop remove that awful cookie notification.
> > > We switched to a service that respects users privacy and doesn't require cookie popups. You can view the report here: https://app.usefathom.com/share/hlfjurxw/design-language
> > 
> > 
> > Hi @vpicone
> > Is there any code on IBM Design Language that sets cookies on any page? Regardless, we are on ibm.com domain and IBM uses cookies throughout its site so we can’t tell users “hey you have to go to some other page if you change your mind about us using cookies for your visit."
> > Please revert back to the cookie notification and/or follow the IBM.com footer cookie preferences–thank you! I think the design and digital team have been working on a redesign for several months now so, we should be close to a new design.
> > We pay for analytics reports so, if changing analytics strategies, we need to align before making a decision. As far as I can see, Fathom is not an IBM approved supplier. If there are any, please remove Fathom scripts from the IBM Design Language site–thank you!
> > If we want to use Fathom, I suggest we add it to the Design Toolbox repo and someone take the lead and begin the approval process.
> > Thank you @vpicone.
> > FYI @alisonjoseph @sadekbazaraa @KSandeep5 @rmathur16

Hi @alisonjoseph 

Would you please share a status update on this issue i.e. in which sprint it will be addressed–thank you!

**Comment by rmathur16** [comment]
@vpicone @kennethhartmann @sadekbazaraa @mjabbink @alisonjoseph 
Based on our meeting (12/4) here's the call summary and next steps:
1. Add IBM cookie requirements back to IDL on 12/4 / Vince
2. Investigate IBM.com cookie requirements / Vince & Rohit
3. Continue to work with Andreea and team to design and deploy new Cookie modal / Sadek
4. Remove Fathom from any IBM Brand websites and start IBM Application approval process for Fathom / Vince

Thank you.

**Comment by vpicone** [comment]
@rmathur16 @kennethhartmann steps one and four have been resolved, please open separate issues for #2 and #3 if necessary. I'm not clear on what my "investigation" action items are for step 2.
