### ISSUE TITLE
Update pictogram library

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#818]
The Carbon site has released the latest pictograms and their new percentage adjustment and the same needs happen for IDL pictogram library page.

**Comment by mjabbink** [comment]
@vpicone We basically want the new one to appear to be the same scale they currently are.

**Comment by mjabbink** [comment]
and of course this applies to Carbon site as well.

**Comment by mjabbink** [comment]
@alisonjoseph Once the new pictograms package is ready for the library we need to get Aux to adjust this percentage to keep them roughly the same size as they are now. Not sure when that day will ever come but I’ve prepared this issue for that celebratory day!

**Comment by mjabbink** [comment]
@alisonjoseph Assuming if the Carbon site is updated IDL will be as well?

**Comment by mjabbink** [comment]
the scaling has been figured out by System team for carbon site library and preview here :https://carbondesignsystem-git-release-v10250-rc1.carbon-design-system.vercel.app/guidelines/pictograms/library

**Comment by mjabbink** [comment]
just needs to go live now and also updates applied to IDL site

**Comment by vpicone** [comment]
Resolved
