### ISSUE TITLE
Update Gallery page background color

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#83]
The background for the Gallery page should be gray 100, and nav should be using the dark theme

**Comment by emyarod** [comment]
does this requires a change to the theme or can it exist in this repo only? it seems that the `homepage` prop sets the dark theme on the index only and no other pages right?

**Comment by alisonjoseph** [comment]
@vpicone thoughts on this? Should we update the theme to somehow set a "dark" mode for a page? Would we want to set this on the front matter of any page, or would we rather just hard code this for the design language website for now.
