### ISSUE TITLE
[pictograms/usage] page fixes

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#830]
@conradennis 

Noticed some things on the pictograms page as I was working on app icons guidance

(pictograms page on left, proposed app icon guidance on right) Here I think the order would make more sense to show the icons without containers first, and I noticed the clearance on some images is half gray 10, but one has all blue clearance
<img width="1178" alt="Screen Shot 2020-12-03 at 12 50 34 PM" src="https://user-images.githubusercontent.com/47458576/101074236-2514f980-3566-11eb-9a69-68ad61020692.png">

Looks like the captions for these two images are swapped
<img width="921" alt="Screen Shot 2020-12-02 at 10 15 06 AM" src="https://user-images.githubusercontent.com/47458576/101074553-8046ec00-3566-11eb-853a-1c36b8c7613c.png">
<img width="915" alt="Screen Shot 2020-12-01 at 11 07 22 AM" src="https://user-images.githubusercontent.com/47458576/101074563-83da7300-3566-11eb-97b1-7c967110fc50.png">

**Comment by conradennis** [comment]
@peter-garvin good catch, thanks for the heads up. I'll make these changes and link the PR here when i'm done.

**Comment by conradennis** [comment]
PR is here: https://github.com/carbon-design-system/design-language-website/pull/831

**Comment by vpicone** [comment]
closed via https://github.com/carbon-design-system/design-language-website/pull/831
