### ISSUE TITLE
Typeface page style fixes

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#84]
- [x] Replace lead video with new one from Buck
- [x] Sub-families section type should be bigger. Also the two columns of type should sit on page column grid.
**expected**
![image](https://user-images.githubusercontent.com/2753488/60925496-851c4900-a269-11e9-9e97-16bcd24408e9.png)

- [x] Type-tester sample text should be bigger and “Light”
- [x] Use default Carbon styles for slider
**expected**
![image](https://user-images.githubusercontent.com/2753488/60925535-982f1900-a269-11e9-848c-3144e34cb6c5.png)
![image](https://user-images.githubusercontent.com/2753488/60925565-abda7f80-a269-11e9-8a21-cdee705a39ec.png)

**Comment by emyarod** [comment]
>  Sub-families section type should be bigger. Also the two columns of type should sit on page column grid.

> Use default Carbon styles for slider

are these point still valid? they appear to be identical to the current IDL site

**Comment by alisonjoseph** [comment]
Font sizes are definitely different, check all breakpoints, but it looks like they might only be off at the larger/largest one. 
![Screen Shot 2019-07-18 at 9 36 41 AM](https://user-images.githubusercontent.com/2753488/61466484-99360980-a93f-11e9-9042-075b141ddbaf.png)

and Yes Mike requested default styles for the slider, so it will be different than the current live site.

**Comment by emyarod** [comment]
ok just to confirm, "sub-families section type" was not referring to the "Sub-families" heading or "With four subfamilies..." text and is referring to the text in the content switcher then?

[the default slider styles are identical to the current live site](https://the-carbon-components.netlify.com/?nav=slider), so I guess we want a custom slider right? do we have a spec for which color tokens to use?

**Comment by alisonjoseph** [comment]
> ok just to confirm, "sub-families section type" was not referring to the "Sub-families" heading or "With four subfamilies..." text and is referring to the text in the content switcher then?

Yup! Sorry for confusion

For the slider, it looks correct, but looks like it is just missing the active/focus state? I think its custom right now, but we should just be using what Carbon provides. 
http://react.carbondesignsystem.com/?path=/story/slider--default

It's the `InputRange` component, I'd see first if we can easily swap it out for the default slider from Carbon, if not then we just need to add the focus/active state to match what we have.

**Comment by emyarod** [comment]
alright I got the font size issue addressed now

andjust to confirm for the slider, we want to rip out `<InputRange>` for the Carbon `<Slider>`?

**Comment by alisonjoseph** [comment]
I think you'll want to import the `Slider` into the `InputRange` component since there is a wrapper element to it to give it the white background and correct width. OR you can just adjust the styles that are there to give it the correct active state.

**Comment by emyarod** [comment]
the wrapper is not contained in the `<InputRange>` component so it looks like we can just replace `<InputRange>` with `Slider` altogether in this scenario. we may be able to do the same in `<TypeSetStyle>` since that's the only other location `<InputRange>` is used

**Comment by alisonjoseph** [comment]
new vimeo ID for the top video is `337384869` @emyarod

**Comment by alisonjoseph** [comment]
and yea, we should go ahead and replace the other slider and just kill the `<InputRange>` component if possible 👍

**Comment by emyarod** [comment]
got it, will remove the other `<InputRange>` in a separate PR

**Comment by mjabbink** [comment]
In mobile  the "Sub-families"  list should be one column.

![File (49)](https://user-images.githubusercontent.com/32881239/62149660-3db63500-b2ca-11e9-85a1-b5caecf4c509.jpg)

**Comment by mjabbink** [comment]
looks like you may have already done the above.

**Comment by mjabbink** [comment]
the large typesetter size is nice in desktop but too large in mobile


current:

![File (50)](https://user-images.githubusercontent.com/32881239/62230142-2db45900-b38f-11e9-9fea-1b2540f4e3c9.jpg)


expected:

![File (51)](https://user-images.githubusercontent.com/32881239/62230190-491f6400-b38f-11e9-872f-efe9a636ed0e.jpg)

**Comment by jeanservaas** [comment]
qq I just reopened the issue, but the devs need more clarity.

Right now, when the slider is maxed out, we matched the current IDL behavior exactly

Here's a side by side of our build and current IDL with the slider maxed out:

![image](https://user-images.githubusercontent.com/43144260/62231706-335b7000-b38a-11e9-8671-b48b1126ed61.png)

<br>

In your image, the slider's only about a third / quarter of the way:

![image](https://user-images.githubusercontent.com/43144260/62231804-5dad2d80-b38a-11e9-95cd-270275f09772.png)



<br>

Question:

Do you want us to change the value of the max'd out slider? If so what should be the Min / Max values?

**Comment by mjabbink** [comment]
Not seeing this reflected in staging.

**Comment by mjabbink** [comment]
Hope this clears it up.

— Desktop is currently correct in staging which looks exactly centered in the slider (it matches current IDL as well)

— Mobile the slider it remains at center which is too big in mobile. IDL goes to 1/4 in mobile which yields the above image and I placed below again to be clear. 


<img width="391" alt="Screen Shot 2019-08-09 at 2 30 59 AM" src="https://user-images.githubusercontent.com/32881239/62737599-c0b75800-ba4d-11e9-9d42-ec3621800985.png">

**Comment by jeanservaas** [comment]
@alisonjoseph I'm hoping this can just be a quick fix.

Mike clarified that this is just about default slider positions... so when you show up to the page, on desktop the slider dot is set to halfway (50%) which is correct (this is correct now)

… but if you show up to the page in mobile or scale to mobile, he wants the slider default to be only 25% of the distance across. Does this make sense?

**Comment by mjabbink** [comment]
🙏
