### ISSUE TITLE
[app icons] change "IBM Cloud Project Coligo" To "IBM Cloud Code Engine"

### ISSUE THREAD

**Issue by eraymond25** [carbon-design-system/design-language-website#865]
## Detailed description

On the [app icons library page](https://www.ibm.com/design/language/iconography/app-icons/library/) "IBM Cloud Project Coligo" should be changed to "IBM Cloud Code Engine". Coligo was the codename for it, but now it's real name is Code Engine
cc @peter-garvin in case you want to update this in your box folders too

## Additional information

<img width="280" alt="Screen Shot 2021-01-27 at 10 21 54 AM" src="https://user-images.githubusercontent.com/12436158/106044470-64168580-60a5-11eb-8856-944ae604fb9d.png">

cc: @ortelt

**Comment by peter-garvin** [comment]
we're aware of this one, it will be resolved by https://github.com/carbon-design-system/design-language-website/pull/848 and https://github.ibm.com/brand/App-icons/issues/256

**Comment by alisonjoseph** [comment]
This is resolved
