### ISSUE TITLE
DL slow page load time on mobile and desktop - Optimize Images for Web and Performance

### ISSUE THREAD

**Issue by rmathur16** [carbon-design-system/design-language-website#870]
@kennethhartmann @sadekbazaraa @KSandeep5 @mjabbink @vpicone 
**Background DL site speed:** DL pages are experiencing slow page load time both in Mobile as well as on Desktop.

**Tested DL pages on:** https://developers.google.com/speed/pagespeed/insights/

**How to improve DL site speed?**

**Mindful of the file size of the source image and reduce the size of it.**
Per Vince and Alison - https://squoosh.app/ can resize one offs but Adobe bridge/ImageMagic can help for bulk image resizing. 

**Use of video formats for animated content**
Large GIFs should be converted into MP4 to save bandwidth and load the page faster.
For example: https://www.ibm.com/design/language/c7b2d70d2a51b90c318d9d68435b80ae/IBM_Services_Progress_Animation.gif
The size of original GIF is 1.7MB when converted to MP4 is 157KB.

**Optimize images for mobile tablet desktop - Need more discussion with Dev team on this:** 
How are we optimizing images on the page for mobile, tablet and desktop?
Whether we are generating multiple versions of each image.
One of the ways to go about this is to start with your design’s base width and the biggest image size that can be used, and then scale down from there for some common devices and breakpoints.
For example, most websites don’t go above the 1100 px mark for content block width, so you can assume that the max image that can be displayed in that case is 1100 px in width as well.
Then, you can create breakpoints for 800 px and 550 px (common values) to cover tablet and mobile scenarios. While this won’t give you 100% perfect results on all devices, you’re at least optimizing to a reasonable extent and keeping your images under control.

The main point is if we are serving one big image and scaling down this will waste a lot of bandwidth and make the site load really slowly on most devices specially when it comes to mobile therefore we should be looking into options such as generating multiple versions of source image for mobile and tablets.

**Optimize images**
Choose the right format and quality for every image on our pages.
JPG or PNG - Which one to use when.
Scan through all the pages.

**Remove any unused JavaScript - Need more discussion with Dev team on this:**
Check with Vince and Pavol
It can reduce bytes consumed by network activity.

The above points will be applicable to BC pages as well.

**Comment by rmathur16** [comment]
I'll reach out individually/slack channels to discuss this further. Thank you.

**Comment by vpicone** [comment]
@rmathur16 are there particular pages of concern? The majority of our users are desktop where the performance for the homepage is fine 
![image](https://user-images.githubusercontent.com/4078018/107816829-f0c67200-6d3a-11eb-80bf-a7c14b08f9b1.png)

**Comment by vpicone** [comment]
I added a GH action to compress the images on demand and on a schedule (every Sunday). I ran it once [here](https://github.com/carbon-design-system/design-language-website/pull/872) and it caught some easy compression.

**Comment by rmathur16** [comment]
@vpicone This is just one example and there are plenty of pages like these. And I do understand that our majority of users are on desktop but at the same time we should strive for improving our mobile performance as well. Thx.
Attached screenshot for - https://www.ibm.com/design/language/gallery

![Screenshot_2021-02-12 PageSpeed Insights](https://user-images.githubusercontent.com/38890232/107818271-5b7cab00-6d45-11eb-8654-64e81196a14e.png)
![Screenshot_2021-02-12 PageSpeed Insights(1)](https://user-images.githubusercontent.com/38890232/107818272-5b7cab00-6d45-11eb-9b9e-ffec0ddb59d5.png)

**Comment by vpicone** [comment]
@rmathur16 make sure your browser is in incognito mode when you run lighthouse, it can have a significant impact on the results:
![image](https://user-images.githubusercontent.com/4078018/107818719-a5619300-6d3d-11eb-8681-7cf18714d20a.png)

**Comment by rmathur16** [comment]
Yes @vpicone now checked in incognito mode...and this what I got for mobile and desktop.
![incog01](https://user-images.githubusercontent.com/38890232/107819704-941d8400-6d47-11eb-9a90-7ad404572a91.jpg)
![incog02](https://user-images.githubusercontent.com/38890232/107819706-941d8400-6d47-11eb-9466-b52e72b241b4.jpg)

**Comment by vpicone** [comment]
@rmathur16 the lab data from pagespeed insights is less reliable than running lighthouse in your browser dev tools: https://github.com/GoogleChrome/lighthouse/issues/6708

Try giving that a try. Are users complaining about the site being slow?

**Comment by rmathur16** [comment]
@vpicone so https://developers.google.com/speed/pagespeed/insights/ is less reliable than running lighthouse in your browser dev tools? what are the steps to run lighthouse in browser dev tool? Not sure where it's mentioned on the link you have provided (GoogleChrome/lighthouse#6708).

Being a user myself I see the site is pretty slow specially on mobile. And if we can work on optimizing the images the site can definitely speed up. Thanks.

**Comment by alisonjoseph** [comment]
Closing for now, will reopen if needed
