### ISSUE TITLE
Add missing chart images to Charts page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#900]
https://www.ibm.com/design/language/data-visualization/charts

Synchronize mini chart illustrations with Carbon site.

Carbon
![Screen Shot 2021-03-24 at 8.53.55 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/91710336-0f0a-473a-b1b6-6b144978e5ee)

———
IDL
![Screen Shot 2021-03-24 at 8.54.24 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/3c4e29cc-35d7-4781-a6c3-3594f1189714)

**Comment by mjabbink** [comment]
Carbon
<img width="1096" alt="Screen Shot 2021-03-24 at 8 55 16 PM" src="https://user-images.githubusercontent.com/32881239/112407083-7139a480-8ce3-11eb-8d5f-1b073bba874b.png">




————
IDL

<img width="1132" alt="Screen Shot 2021-03-24 at 8 54 40 PM" src="https://user-images.githubusercontent.com/32881239/112407161-9a5a3500-8ce3-11eb-9df7-c98dd53f4dd6.png">

**Comment by mjabbink** [comment]
FYI: @sadekbazaraa

**Comment by sadekbazaraa** [comment]
Thanks @mjabbink I was just discussing updates to this page with @DanaPaslaru last week. @KSandeep5 let's be sure to get these changes on the books. Dana, do you have some bandwidth to help out with this one?

**Comment by DanaPaslaru** [comment]
@sadekbazaraa @mjabbink Hi, yes, I'll look into it and make the sync. Thanks!

**Comment by mjabbink** [comment]
Keep in mind Bullet, Boxplot and Circle pack are coming down the pike and will slot into this as well.

**Comment by DanaPaslaru** [comment]
@sadekbazaraa @mjabbink Hi, I've made the adjustments on data vis charts page, here is the prview url: 
https://design-language-website-il53hjlzy-carbon-design-system.vercel.app/data-visualization/charts

Was wondering if we should wait for bullet, circle and boxplot to be added...or should we move forward with this pull request and make a new one after we have the other three ones from Jeannie? 

Thanks!

**Comment by mjabbink** [comment]
@DianaStanciulescu @DanaPaslaru We now have Bullet, Word Cloud, Boxplot, Lollipop, and floating bar available and updated on the Carbon site.

**Comment by DanaPaslaru** [comment]
@mjabbink @sadekbazaraa  Hi, I've updated the Chart page with the missing ones, you can preview them here: https://design-language-website-lrlrbr805-carbon-design-system.vercel.app/data-visualization/charts

One question: I saw that Bar chart (horizontal) and Grouped bar (horizontal) were removed from Comparisons on Carbon site; also, Stacked bar vertical was removed from part to whole section. Should I remove them from IDL also? Or should we keep them here? 

Thanks!

**Comment by sadekbazaraa** [comment]
> One question: I saw that Bar chart (horizontal) and Grouped bar (horizontal) were removed from Comparisons on Carbon site; also, Stacked bar vertical was removed from part to whole section. Should I remove them from IDL also? Or should we keep them here?

Thanks for getting these in @DanaPaslaru 
Seems like we should be consistent with what's available in Carbon.
Maybe check with @jeanservaas to see why the others were removed.

**Comment by mjabbink** [comment]
Not sure why those were removed? Can you ping Iliad and Jeannie. I want to make sure that is not a mistake. If intentional then make the same as Carbon but if those were removed accidentally we need to add them back!

**Comment by DanaPaslaru** [comment]
@mjabbink Hi, I've had a quick chat, with Eliad, they intentionally removed bar chart horizontal, grouped bar horizontal and stacked bar vertical; they've decided to make the demo pages smaller + more focused on the generality of the purpose of using a specific chart type. 
I've updated the IDL charts to match what's now on Carbon, preview url here:
https://design-language-website-d83ftxgd9-carbon-design-system.vercel.app/data-visualization/charts

Thanks!

@sadekbazaraa fyi

**Comment by mjabbink** [comment]
Yes, I designed the new page with edited demos. But that said we did not need to remove those necessarily. But I think it works and Storybook is the place for all the variants. No need for Carbon page to have all those.

So, only thing remaining and for Carbon team as well is adding Circle pack thumbnail to Chart types page. Carbon has a PR open to add Circle Pack to the “Complex charts” page.

**Comment by mjabbink** [comment]
nice work @DanaPaslaru

**Comment by DanaPaslaru** [comment]
@mjabbink Hi, so we'll wait a bit more, to have circle pack thumbnail, right? and then push this page to deployment. Thanks!

**Comment by mjabbink** [comment]
@DanaPaslaru Circle Pack is live. @jeanservaas is there a thumbnail you can pass to @DanaPaslaru? We also need to update the Carbon page thumbnails as well

**Comment by mjabbink** [comment]
@DianaStanciulescu @DanaPaslaru Is there design needed or can this move to dev? This issue is starting to linger

**Comment by DanaPaslaru** [comment]
@mjabbink HI, I just need to add the carbon page url for circle pack, then it should be good to go. For some strange reason, the circle pack is not visible at the moment in the main charts type carbon page. Thanks!

**Comment by mjabbink** [comment]
👍

**Comment by DanaPaslaru** [comment]
@mjabbink Hi, the new charts are all updated, preview url here: https://design-language-website-hq6s0bds3-carbon-design-system.vercel.app/data-visualization/charts

PR here: https://github.com/carbon-design-system/design-language-website/pull/918

Thanks!

**Comment by mjabbink** [comment]
Nice. Looks good.

**Comment by mjabbink** [comment]
@DanaPaslaru and @vpicone All the links from the cards are now broken and revealing 404 page
