### ISSUE TITLE
Typo: “Stacked headlines” section

### ISSUE THREAD

**Issue by jtweigle** [carbon-design-system/design-language-website#901]
> Headlines are preferred Stack headlines into two or even three lines versus keeping them in one long line. This helps create a compact reading unit for the headline, and can help control or avoid widows.

This is what I see, viewing the website in Firefox on Pop!_OS. Is this paragraph meant to start with “Stack headlines into …”?

**Comment by mjabbink** [comment]
PR: https://github.com/carbon-design-system/design-language-website/pull/981

**Comment by mjabbink** [comment]
Good catch @jtweigle
