### ISSUE TITLE
Incorrect illustrator icons on library pages

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/design-language-website#903]
Illustrator icons (and all resource icons) have been updated to be global coming from this directory:
https://github.com/carbon-design-system/design-language-website/blob/master/src/images/resource-cards/

Seems that the resource card on library pages when theres no results is still using the old icon, but I dont know how to change it. This is for both UI icons and pictograms

<img width="1678" alt="Screen Shot 2021-03-29 at 10 55 36 AM" src="https://user-images.githubusercontent.com/47458576/112864574-8add4200-907d-11eb-85d0-6b591eb72d5c.png">

**Comment by peter-garvin** [comment]
@vpicone Josh mentioned you might know about this

**Comment by alisonjoseph** [comment]
This will need to get updated on the Carbon website also.

**Comment by alisonjoseph** [comment]
@peter-garvin I found where this is coming from, do you have the correct icon in svg form?

**Comment by peter-garvin** [comment]
Not in SVG form, but the PNG can be found in src/images/resource-cards

if it needs to be SVG I'm sure we could find or make one
