### ISSUE TITLE
far right column tool tips in pictograms and icons need to be end tooltips — open towards left.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#905]
![Screen Shot 2020-11-23 at 8.35.00 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/ae5d928b-b6bf-4cd8-8ce1-98c4491223b5)

![Screen Shot 2020-11-23 at 8.34.15 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/7f3f8032-b70e-454d-ba7d-366190dcef38)

IDL
https://www.ibm.com/design/language/iconography/ui-icons/library
https://www.ibm.com/design/language/iconography/pictograms/library

Carbon
https://www.carbondesignsystem.com/guidelines/icons/library
https://www.carbondesignsystem.com/guidelines/pictograms/library

**Comment by alisonjoseph** [comment]
This will need to get updated on the Carbon website also.

**Comment by mjabbink** [comment]
In mobile the tooltip seems to get stuck on the home page. It won’t go away as you scroll up and down the page.

**Comment by mjabbink** [comment]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/32881239/114469497-e564bb00-9bb2-11eb-9ec4-4d7591815b30.gif)

**Comment by mjabbink** [comment]
Actually it also get’s stuck in desktop as well.

**Comment by mjabbink** [comment]
Should be Gatsby issue.

**Comment by mjabbink** [comment]
@vpicone @alisonjoseph the tooltip is still not going away in mobile. The same recording above shows the current situation although alignment is resolved the "stuck" tooltip part is not. Should this be a separate issue?
