### ISSUE TITLE
Sync vs. remove "UI" page content

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#94]
We're currently duplicating content on both IDL and Carbon, and pages are out of sync. A suggestion is to remove UI pages from IDL and link to Carbon, would be interested in what other people think?

**Remove**
- Type Specs UI
- Color UI
- 2x Grid UI

**Keep/sync**
- Icon Library

**Discuss**
- Motion

**Comment by jeanservaas** [comment]
I agree with this. I think for sure Type Specs UI / Color in UI / 2x grid UI should be removed from IDL.

The biggest question is the icon library and after talking with @chrisconnors-ibm and @aagonzales and earlier with Mike, seems like the icon library will be the only real 1:1 duplication.

**Comment by alisonjoseph** [comment]
I agree on the Icon library, its also not an issue to try and keep it in sync, since both sites will be pulling the data directly from the Icon package.

**Comment by mjabbink** [comment]
I agree for the most part. The only think I wonder is if DL has a simplified or high level overview and aim to Carbon or adjust the 2x Grid page to include some of the UI high level and aim to Carbon from there. The other thing to think about is the animation at the top of the page. My hunch is you all don’t like it but I think it’s valuable and many people do. Same for color in UI.

**Comment by emyarod** [comment]
has the discussion around this ticket been finalized?

**Comment by alisonjoseph** [comment]
> Mike Abbink [4:12 PM]
I think the grid UI can be removed but can we keep up Specs until we replace with a general type specs page. Other there are no type specs at all in IDL which seems odd. I’ve asked the team to design a new page in the next few weeks and then move into dev. We can then remove and replace

> Mike Abbink [8:51 PM]
Those animations for Color in UI and Grid UI need to have a place to live. Those are valuable reflect intent. So if we remove those pages from IDL (color/grid) then those animations need to be present in Carbon pages. Or we need to revisit how they can be incorporated in IDL.
for example the “Layout” page in Carb is the place for the Grid animation video.
and “Color” where the color UI video should live

> Mike Abbink [11:56 PM]
Maybe @cristiana.iliescu can own this with me. Would like Jan or Connor to help too if they can

**Comment by jeanservaas** [comment]
I'm good with bringing animations into Carbon, the only thing that's a little weird is that only some elements get specific animations around UI usage and the others don't. It would be nice if we had animations specific to product for all of our elements on Carbon ultimately. But that doesn't have to stop us from bringing in the two we have.

Is there dev work around that? Thought the video player was already built.

**Comment by alisonjoseph** [comment]
> Is there dev work around that? Thought the video player was already built.

nope, no dev specific work, its all content/IA decisions at this point.

**Comment by mjabbink** [comment]
Jeoff and/or Phil need to cough up bucks

**Comment by jeanservaas** [comment]
Cool, I say we move this effort forward and get the duplicate UI content that we talked about down from IDL. Especially since we want to start adding some product specific grid guidance into the layout section... don't want to have to worry about that content needing updates in two places.

And if we can fold those videos into Layout and Color sections on Carbon.

**Comment by mjabbink** [comment]
We need to update our Type Specs UI page first. We have this now in the design pipeline. Once we have a solid replacement and a design to move into dev we can take remove old one.

I think Color in UI and 2x Grid in UI can come down. As long as video go and mobile image treatments follow when relevant.
