### ISSUE TITLE
Revert back to “G100 background” under lead space. 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#949]
NOt sure how this became gray but should be G100.

<img width="1316" alt="Screen Shot 2021-05-07 at 10 39 28 AM" src="https://user-images.githubusercontent.com/32881239/117474730-d9091f00-af20-11eb-9507-03fb3f9c8e94.png">

**Comment by vpicone** [comment]
@mjabbink @sadekbazaraa do think black like Carbon? g100 is the background color
<img width="883" alt="Screen Shot 2021-05-17 at 3 29 18 PM" src="https://user-images.githubusercontent.com/4078018/118554504-222e4f80-b727-11eb-87f5-b0dd216198cb.png">

**Comment by vpicone** [comment]
Carbon for reference
<img width="684" alt="Screen Shot 2021-05-17 at 3 47 26 PM" src="https://user-images.githubusercontent.com/4078018/118554564-3b370080-b727-11eb-934d-3485a5e3609f.png">
