### ISSUE TITLE
Add Plex Sans JP to the Typeface page & remove resource card for Noto JP

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#965]
- [x]  Add Japanese to the type testers above Korean —https://www.ibm.com/design/language/typography/typeface/#non-latin-scripts

Use this test as a sample:  設計された

- [x] Remove resource card aiming to Noto Sans Japanese

![Screen Shot 2021-06-14 at 1.36.24 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/dc661019-f397-43e5-8aef-457592651938)

- [x] Update text in “Asian scripts” section

replacement copy:
The Chinese scripts are currently under development. Chinese is scheduled for release in 2022–2023 and will support both Traditional and Simplified Chinese. In the meantime, we have chosen an open source Chinese typefaces that can work well with the IBM Plex Family.

**Comment by mjabbink** [comment]
@sadekbazaraa @vpicone Would be nice to have this updated with the release of Plex JP

**Comment by mjabbink** [comment]
Waiting for some final files but @vpicone can chime in on timing.

**Comment by mjabbink** [comment]
<img width="1015" alt="Screen Shot 2021-06-16 at 2 21 42 PM" src="https://user-images.githubusercontent.com/32881239/122279962-4314cc80-ceae-11eb-8915-c8408338d76d.png">

**Comment by mjabbink** [comment]
Asian scripts

The Chinese scripts are currently under development. Chinese is scheduled for release in 2022–2023 and will support both Traditional and Simplified Chinese. In the meantime, we have chosen an open source Chinese typefaces that can work well with the IBM Plex Family.

**Comment by vpicone** [comment]
Yeah we don't have the final Japanese files yet, release will be a couple days after that. I'll make a note to update this card as part of the release.

**Comment by mjabbink** [comment]
@vpicone 2 of the three tasks are taken care of since I know how to achieve those. The last one is in your hand's brother.

**Comment by mjabbink** [comment]
@vpicone Can you provide me some timeframe for 1). The last item left in this issue and 2). The release of the Plex JP files in the repo.

There are communication plans in play that are dependant upon the release and addition to the Type page on the IDL site.

**Comment by mjabbink** [comment]
Final files for github were provided by Bold Monday several weeks ago.

**Comment by vpicone** [comment]
1. The last item left takes 30 seconds but is pointless until JP is released
2. My goal is to have a beta released by the end of next week

**Comment by Katie-A-IBM** [comment]
@mjabbink Please see above.

**Comment by mjabbink** [comment]
Perfect. Sounds good. Thanks for update because the timing was not clear to me.

**Comment by mjabbink** [comment]
@vpicone Once you have a beta release it’s fine to get the JP in the IDL typeface page typesetter (last item in the issue). The JP fonts themselves should not be beta so not sure what you mean by beta release.

**Comment by mjabbink** [comment]
@vpicone Hows this last typesetter item going? Plex JP launch?
