### ISSUE TITLE
Mobile: The dropdown should be white. Original issue 1109

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#978]
In the mobile, the tab becomes a dropdown and should be white. The original issue was closed but this looks like it was not resolved.
https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1109

![IMG_0546.jpg](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/98f8a53e-d11c-4434-95b0-2e0a14570915)

**Comment by mjabbink** [comment]
@vpicone I’m not sure this issue was ever resolved but it was closed.

**Comment by mjabbink** [comment]
Also is happening here
https://www.ibm.com/brand/systems/watson/brand/color#illumination

<img width="514" alt="Screen Shot 2021-06-26 at 12 31 44 AM" src="https://user-images.githubusercontent.com/32881239/123503030-f354a480-d615-11eb-812f-6b5f2579d9e9.png">

**Comment by vpicone** [comment]
closed by [3f8c1b8](https://github.com/carbon-design-system/design-language-website/commit/3f8c1b8df018fae7111b5223c2be5a62f6513960)
