### ISSUE TITLE
Add mobile images

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#98]
~blocked until we get an updated image component~
~https://github.com/carbon-design-system/gatsby-theme-carbon/issues/249~
<hr>
Icons page: Mobile:
— In many images, we have made mobile friendly svgs to be able to see and read images better. We do this a bunch in UI icons, App icons, Pictograms pages. They are 1:1 aspect ratio svgs used in DL mobile. Please visit https://www.ibm.com/design/language/elements/icons and view on mobile phone.
<br><Br>

**We need to update images across the entire site w/ mobile friendly images where needed. Will most likely need to cross reference w/ current site unless someone has a better idea.**

**Comment by emyarod** [comment]
should be unblocked by https://github.com/carbon-design-system/gatsby-theme-carbon/pull/294

**Comment by emyarod** [comment]
> We do this a bunch in UI icons, App icons, Pictograms pages

are these the only pages that need this component?

**Comment by alisonjoseph** [comment]
I'm going to update this issue, I think we might need to check all the pages
